### ISSUE TITLE
Messages hard-coded in english in js

### ISSUE THREAD

**Issue by Binnette** [SSilence/selfoss#1000]
Hi some message are hard-coded in english, so they are not translated (in french for me).
![2017-11-27 23_28_30-selfoss 169](https://user-images.githubusercontent.com/6597721/33293014-8ebb5848-d3cb-11e7-90e1-b0b1228a4031.png)

Examples of hard-coded english messages in javascript file (with code source):

-var refreshed=**'Sources have been refreshed'**...
-selfoss.ui.showMessage(refreshed,**'Reload list'**...
-selfoss.ui.showError(**'Cannot refresh sources: '**...

Possible french translation:
- 'Les sources ont été rafraichies'
- 'Recharger la liste'
- 'Impossible de rafraichir les sources : ' (in french there is a white space before colon ':')

**Comment by jtojnar** [comment]
Hmm, I thought I had opened an issue for this but apparently we only have one for [spout fields](https://github.com/SSilence/selfoss/issues/987). This one should be easy to fix at least.
