### ISSUE TITLE
Valid RSS feed fails

### ISSUE THREAD

**Issue by poVoq** [SSilence/selfoss#1007]
Hello.

I am trying to use the following feed with Selfoss:
https://www.wsup.com/blog/feed/
But it fails with:
`error loading feed content: https://www.wsup.com/blog/feed/ is invalid XML, likely due to invalid characters. XML error: Mismatched tag at line 1, column 47 `

But according to the W3C check here: https://validator.w3.org/feed/ it is a valid RSS feed.

Thanks for looking into the issue.

**Comment by jtojnar** [comment]
This is most likely caused by the web site being misconfigured. For me, the feed fails with `cURL error 22: The requested URL returned error: 400 Bad Request`. Looking into the HTTP response body confirms my suspicions:

```http
HTTP/1.1 400 Bad Request
Server: nginx
Date: Thu, 21 Dec 2017 05:06:22 GMT
Content-Type: text/html
Content-Length: 1393
Connection: keep-alive
Last-Modified: Wed, 06 Aug 2014 12:28:14 GMT
ETag: "19531c-571-4fff51b201380"
Host-Header: 192fc2e7e50945beb8231a492d6a8024

<html>
<head>
<style type="text/css">
	body{background-color:#f4f9fa}
	.centered{text-align:center}
	.container{border:1px solid #e2e2e2;width:1200px;margin:50px auto}
	.header{height:120px;background-color:#fbfdfd;padding-top:40px;}
	.header h1{font: bold 130% Arial, Helvetica, sans-serif;
color:#5278af;margin:0;padding:0}
	.header h2{font: bold 80% Tahoma, Verdana, sans-serif;
color:#5278af;margin:0;padding:0}
	.line{height:15px;background-color:#eef6f7}
	.error-container{background-color:#fff;font:normal 80% Tahoma, Verdana,
sans-serif;color:#000;text-align:justify;padding:30px}
	.error-container li{padding-bottom:10px}
	.error-container a:link, .error-container a:visited{font:normal 100%
Tahoma, Verdana, sans-serif;color:#5278af;text-decoration:underline}
	.error-container a:hover{color:#5278af;text-decoration:none}
</style>
<title>Access Denied</title>
</head>
<body>
<div class="centered">
	<div class="container">
		<div class="header">
			<h1>The page you are trying to access is restricted due to a security rule.</h1>
	<br>
			<h2>If you believe the security rule is affecting the normal operation of your website, contact your host support team and provide detailed instructions how to recreate this error.
<br>
They will be able to assist you with rectifying the problem and adjusting the security configuration if needed.</h2>
		</div>
	</div>
</div>

</body>
</html>
```

**Comment by jtojnar** [comment]
Pretending that selfoss is a web browser might circumvent the ill-behaved protection:

```diff
--- a/helpers/WebClient.php
+++ b/helpers/WebClient.php
@@ -51,6 +51,7 @@
      * @return string the user agent string for this spout
      */
     public static function getUserAgent($agentInfo = null) {
+        return 'Mozilla/5.0 (X11; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0';
         $userAgent = 'Selfoss/' . \F3::get('version');
 
         if (is_null($agentInfo)) {
```

**Comment by poVoq** [comment]
Sadly that doesn't seem to make a difference.

**Comment by jtojnar** [comment]
Could you tell me the version of selfoss you are using and spout that was used for the feed?

**Comment by poVoq** [comment]
Latest stable 2.17 and "RSS Feed" spout.

**Comment by jtojnar** [comment]
Do you have CURL support enabled in PHP? If you are not sure, you can add `var_dump(function_exists('curl_exec')); die;`, for example, to the top of `common.php`.

After some testing, it seems that without CURL, SimplePie does not handle the `Access Denied` error correctly.

**Comment by poVoq** [comment]
I'm running Selfoss on a OVH basic shared web-server with php7.1, but cURL seems to be supported, see:
http://fpm7.1-check.cluster015.ovh.net/phpinfo.php

**Comment by poVoq** [comment]
Started working now, I guess they fixed their website. Thanks!
