### ISSUE TITLE
some  times images or not storing 

### ISSUE THREAD

**Issue by pratheepchowdhary** [SSilence/selfoss#1008]
Some time images are not storing  but  image name in database 
Previously worked with same code in other hosting there works good 
But now with same code problem happens 
To store images sometimes

**Comment by jtojnar** [comment]
What version of selfoss are you using? There were some improvements of favicon handling in the development version. Could you also share the URL of some of the sources where this happens?

**Comment by pratheepchowdhary** [comment]
but previously worked same code in other hosting 
While I migrated to digital ocean with Ubuntu 16.4 droplet
I have this issue up to 2000 thumbnails are storing perfectly and than rises this issue of not storing the  thumbnails but the fails name stored to data base
Is any apache configuration and permissions required please send me
This issues if the images more 2000-3000 images store perfectly and then this issue

**Comment by jtojnar** [comment]
Are you saying that no new images get saved but you still see the ones stored before migration? Then the directory permissions are the most likely culprit, `data/favicons` and `data/thumbnails` need to be writeable to the HTTP or PHP server user.

**Comment by pratheepchowdhary** [comment]
http://www.androidhunt.in/newspost/

**Comment by pratheepchowdhary** [comment]
![screenshot_2017-12-22-16-51-36](https://user-images.githubusercontent.com/13903537/34296386-896155b6-e738-11e7-9e72-bb991558aad4.png)

**Comment by pratheepchowdhary** [comment]
which is image not available

**Comment by pratheepchowdhary** [comment]
sorry 
Thumbnails are creating but automatically deleted after some hours around 6 hours images deleted 
Please help me to avoid this

**Comment by jtojnar** [comment]
That does not make sense. Can you go chat to https://gitter.im/fossar/selfoss
