### ISSUE TITLE
How does the filter for a source work.

### ISSUE THREAD

**Issue by Voidi** [SSilence/selfoss#1016]
In the settings for a source you can define a 'Filter'.
Since i cannot find anything about this in the documentation, what is this setting determined to do?

**Comment by jtojnar** [comment]
It accepts a regex that is matched against title and content of the item.

**Comment by Voidi** [comment]
Thanks.
Is there an existing function to filter categories? If not, please consider this as a feature request.

**Comment by jtojnar** [comment]
Unfortunately that is not possible at the moment (see https://github.com/SSilence/selfoss/issues/753). For now, you can try to look if the site has a category specific feeds – they are sometimes available, even though often hidden.
