### ISSUE TITLE
Mark as read automatically

### ISSUE THREAD

**Issue by KewlCat** [SSilence/selfoss#1018]
When opening an element (by clicking on its title), mark it automatically as read, because since I'm interacting with it, I'm almost certainly reading it.

**Comment by aslmx** [comment]
This is something which can be configured.


See selfoss Homepage:

auto_mark_as_read 	
set this to 1 for automatically marking items as read after open/read them.

**Comment by KewlCat** [comment]
Oh ! Sorry I forgot to RTFM. Too impatient to use it, I didn't configure it :-/

**Comment by jtojnar** [comment]
Closing since the feature exists.
