### ISSUE TITLE
The entry-share buttons have no title

### ISSUE THREAD

**Issue by KewlCat** [SSilence/selfoss#1020]
The "share" buttons have no title, and while I may recognize Google+, Twitter, Facebook, maybe Pocket and e-mail, I have absolutely no idea what the other two are. Having a popup appear when leaving the mouse cursor over the buttons would be nice, even if it's as basic as "share with [name of the service]"

**Comment by jtojnar** [comment]
This was fixed in https://github.com/SSilence/selfoss/pull/1035
