### ISSUE TITLE
Failed to retrieve image

### ISSUE THREAD

**Issue by toonn** [SSilence/selfoss#1024]
Since updating to 2.18 I haven't been getting thumbnails for youtube videos. I believe these are the relavant log messages:
```
[2018-03-06 21:01:06] selfoss.ERROR: failed to retrieve image https://i4.ytimg.com/vi/SuXh18jS5r4/hqdefault.jpg, {"exception":"[object] (Ddeboer\\Transcoder\\Exception\\ExtensionMissingException(code: 0): iconv at /srv/http/selfoss/vendor/ddeboer/transcoder/src/IconvTranscoder.php:16)
[stacktrace]
#0 /srv/http/selfoss/vendor/ddeboer/transcoder/src/Transcoder.php(62): Ddeboer\\Transcoder\\IconvTranscoder->__construct('UTF-8')
#1 /srv/http/selfoss/vendor/fossar/guzzle-transcoder/src/GuzzleTranscoder.php(24): Ddeboer\\Transcoder\\Transcoder::create()
#2 /srv/http/selfoss/helpers/WebClient.php(36): Fossar\\GuzzleTranscoder\\GuzzleTranscoder->__construct()
#3 /srv/http/selfoss/helpers/WebClient.php(76): helpers\\WebClient::getHttpClient()
#4 /srv/http/selfoss/helpers/Image.php(99): helpers\\WebClient::request('https://i4.ytim...')
#5 /srv/http/selfoss/helpers/ContentLoader.php(301): helpers\\Image->loadImage('https://i4.ytim...', 'jpg', 500, 500)
#6 /srv/http/selfoss/helpers/ContentLoader.php(197): helpers\\ContentLoader->fetchThumbnail('https://i4.ytim...', Array)
#7 /srv/http/selfoss/helpers/ContentLoader.php(35): helpers\\ContentLoader->fetch(Array)
#8 /srv/http/selfoss/controllers/Index.php(181): helpers\\ContentLoader->update()
#9 /srv/http/selfoss/vendor/bcosca/fatfree-core/base.php(1806): controllers\\Index->update(Object(Base), Array, 'controllers\\\\Ind...')
#10 /srv/http/selfoss/vendor/bcosca/fatfree-core/base.php(1627): Base->call(Array, Array, Array)
#11 /srv/http/selfoss/index.php(80): Base->run()
#12 {main}
"}
[2018-03-06 21:01:06] selfoss.ERROR: thumbnail generation error: https://i4.ytimg.com/vi/SuXh18jS5r4/hqdefault.jpg
```
I also noticed similar messages about favicons:
```
[2018-03-06 21:01:06] selfoss.ERROR: failed to retrieve image https://www.youtube.com/favicon.ico, {"exception":"[object] (Ddeboer\\Transcoder\\Exception\\ExtensionMissingException(code: 0): iconv at /srv/http/selfoss/vendor/ddeboer/transcoder/src/IconvTranscoder.php:16)
[stacktrace]
#0 /srv/http/selfoss/vendor/ddeboer/transcoder/src/Transcoder.php(62): Ddeboer\\Transcoder\\IconvTranscoder->__construct('UTF-8')
#1 /srv/http/selfoss/vendor/fossar/guzzle-transcoder/src/GuzzleTranscoder.php(24): Ddeboer\\Transcoder\\Transcoder::create()
#2 /srv/http/selfoss/helpers/WebClient.php(36): Fossar\\GuzzleTranscoder\\GuzzleTranscoder->__construct()
#3 /srv/http/selfoss/helpers/WebClient.php(76): helpers\\WebClient::getHttpClient()
#4 /srv/http/selfoss/helpers/Image.php(99): helpers\\WebClient::request('https://www.you...')
#5 /srv/http/selfoss/helpers/Image.php(75): helpers\\Image->loadImage('https://www.you...', false, false)
#6 /srv/http/selfoss/spouts/rss/feed.php(253): helpers\\Image->fetchFavicon('https://www.you...', true)
#7 /srv/http/selfoss/helpers/ContentLoader.php(177): spouts\^Mss\\feed->getIcon()
#8 /srv/http/selfoss/helpers/ContentLoader.php(35): helpers\\ContentLoader->fetch(Array)
#9 /srv/http/selfoss/controllers/Index.php(181): helpers\\ContentLoader->update()
#10 /srv/http/selfoss/vendor/bcosca/fatfree-core/base.php(1806): controllers\\Index->update(Object(Base), Array, 'controllers\\\\Ind...')
#11 /srv/http/selfoss/vendor/bcosca/fatfree-core/base.php(1627): Base->call(Array, Array, Array)
#12 /srv/http/selfoss/index.php(80): Base->run()
#13 {main}
"}
```

Is this missing "iconv" extension something I should install? How exactly, I'm not familiar with php?

**Comment by jtojnar** [comment]
Yes, the error is caused by missing both `mbstring` and `iconv` extensions, though at least iconv is [supposed](https://secure.php.net/manual/en/iconv.installation.php) to be enabled by default. What PHP version and operating system are you using?

We do not really need it for downloading images so we can fix it there but it is needed for some other features (FultextRSS, Facebook…)

**Comment by jtojnar** [comment]
Could you to change `vendor/fossar/vendor/fossar/guzzle-transcoder/src/GuzzleTranscoder.php` according to https://github.com/fossar/guzzle-transcoder/pull/2/files#diff-e1d642b163cde3afc55e84f8ac963038?

You should be able to use the following command:

```bash
curl -L https://github.com/fossar/guzzle-transcoder/pull/2.patch | patch -p1 -d vendor/fossar/guzzle-transcoder/
```

**Comment by toonn** [comment]
It's arch linux, `php 7.2.3`. What exactly does the patch do? I figured I"d follow [this](https://github.com/SSilence/selfoss/wiki/Example-step-by-step-installation-using-nginx-and-SQLite) again and I found a line with `extension=iconv.so` that was commented. I can't find a similar line for `mbstring` though, there's mentions of it spread throughout `php.ini`, how do I enable that properly?

**Comment by toonn** [comment]
Would I need to remove the entries without images from the database so selfoss tries to fetch them all over again?

**Comment by jtojnar** [comment]
> How do I enable that properly?

For some reason, the `extension=mbstring` is [removed from `php.ini`](https://git.archlinux.org/svntogit/packages.git/tree/trunk/php.ini.patch?h=packages/php&id=0c02b7595ac0c6530d2559acf10b078dd959713d#n44), it [should be available](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/php&id=0c02b7595ac0c6530d2559acf10b078dd959713d#n78), though. It [might be](https://bbs.archlinux.org/viewtopic.php?pid=510308#p510308) compiled-in, try `php -m | grep mbstring` to verify.

> Would I need to remove the entries without images from the database so selfoss tries to fetch them all over again?

Most likely.

> And where exactly did you get that mbstring is missing? I can't find anything about it in my logs.

I read it here https://github.com/ddeboer/transcoder/blob/e56652fe3b97908def6f53d97498952bbf13a9f6/src/Transcoder.php#L58. Though it might have failed for a different reason. You might try moving `$transcoders[] = new MbTranscoder($defaultEncoding);` before the `try` block to see the error.

But with the patch, the `Transcoder` will not be created for images (the `convertResponse` function will terminate before).

**Comment by toonn** [comment]
It's actually working without the patch after uncommenting iconv. Do you still need me to test it? I think updating the wiki to include enabling iconv would be the best solution since you said it's still needed for FulltextRSS, etc.

One thing I haven't been able to find is what the various types actually do (as opposed to what they're supposed to do). FulltextRSS doesn't give me everything I expect when I've tried it.

Also, I would like to make use of the reddit rss feeds, specifically on a search request, but the api is throttled and the requests always fail. Is there a way to change the useragent selfoss uses or provide oauth authentication tokens for specific feeds?

**Comment by jtojnar** [comment]
It would be nice if you could test it. It is still a minor optimization that makes sense. Or I will just spin up Arch VM later, I am curious why it does not find the mbstring extension.

FullTextRSS spout replaces the content from feed items by a content extracted from the URL using a library called [Graby](https://github.com/j0k3r/Graby). The extraction is [rule based](https://github.com/j0k3r/graby-site-configso) so it is possible it is not perfect for some websites. You can also save custom rules to `data/fulltextrss/custom`. I will add the descriptions to the docs. 

Do you mean the reddit spout? You can add normal credentials and the spout will use cookie authentication. I would love to add OAuth support, as using passwords is not optimal, but registering an application is a serious hassle (see for example the Twitter spout).

The reddit spout works for me, though. How many reddit feeds do you have? You mention a search request, could you share the URL you entered into the spout?

I will try to add a rate control either way.

**Comment by toonn** [comment]
I hadn't noticed the reddit spout. I've changed the feed, will report back if it works or not.
Rate control wasn't the issue since I only refresh once an hour, it's just that the public reddit api is probably horribly overloaded.

There's other spouts I'd like to see documented, "with images" and its ilk.

**Comment by jtojnar** [comment]
* Enclosures are RSS feature to embed multimedia into feed items: https://m.wikipedia.org/wiki/RSS_enclosure. The spout will insert the image enclosures after the content.
* RSS Feed Images is just a normal RSS spout that will also set the first enclosure thumbnail in the item or image from the item content as the entry’s thumbnail.

**Comment by toonn** [comment]
Thank you for the explanations, I had no idea about enclosures and a wrong idea about the RSS Feed Images.
It seems like the reddit spout has gotten me past the throttling problem but I think it expects a different JSON structure or something.
Spout [url](https://www.reddit.com/r/GameDeals/search?q=free+OR+100+nsfw%3Ayes&restrict_sr=on&sort=new&t=all).
```
[2018-03-09 09:17:59] selfoss.ERROR: error loading feed content for r/GameDeals {"exception":"[object] (GuzzleHttp\\Exception\\ParseException(code: 0): Unable to parse JSON data: JSON_ERROR_SYNTAX - Syntax error, malformed JSON at /srv/http/selfoss/vendor/guzzlehttp/guzzle/src/Message/Response.php:148)
[stacktrace]
#0 /srv/http/selfoss/spouts/reddit/reddit2.php(105): GuzzleHttp\\Message\\Response->json()
eddit2->load(Array)s/helpers/ContentLoader.php(99): spouts\
#2 /srv/http/selfoss/helpers/ContentLoader.php(53): helpers\\ContentLoader->fetch(Array)
#3 /srv/http/selfoss/controllers/Sources.php(290): helpers\\ContentLoader->updateSingle('53')
#4 /srv/http/selfoss/vendor/bcosca/fatfree-core/base.php(1806):controllers\\Sources->update(Object(Base), Array, 'controllers\\\\Sou...')
#5 /srv/http/selfoss/vendor/bcosca/fatfree-core/base.php(1627): Base->call(Array, Array, Array)
#6 /srv/http/selfoss/index.php(80): Base->run()
#7 {main}
"}
```
Should I open a new issue about this?

**Comment by toonn** [comment]
I opened a new issue about the JSON parse error since it was probably buried here. My original issue was solved here so I'm closing this one. Feel free to reopen for bookkeeping for the milestone  or something of course.
