### ISSUE TITLE
JavaScript error

### ISSUE THREAD

**Issue by fmunch** [SSilence/selfoss#1030]
Hello,

Since 2.18 I have many JavaScript errors:
```
Uncaught TypeError: selfoss.ui.refreshEntryStatuses is not a function
    at Object.success (all.js?v=1520262850:1085)
    at fire (all.js?v=1520262850:187)
    at Object.fireWith [as resolveWith] (all.js?v=1520262850:193)
    at done (all.js?v=1520262850:538)
    at XMLHttpRequest.<anonymous> (all.js?v=1520262850:554)
```

This probably happens after every update of the sources, but does not seem to affect the overall behavior of the application.

[selfoss-db.js](https://github.com/SSilence/selfoss/blob/master/public/js/selfoss-db.js#L64) calls `selfoss.ui.refreshEntryStatuses` (defined in [selfoss-ui.js](https://github.com/SSilence/selfoss/blob/master/public/js/selfoss-ui.js#L88)). cfb5d29 changed the function name from `refreshItemStatuses` to `refreshEntryStatuses` in both files, but [e55ef1b](https://github.com/SSilence/selfoss/commit/e55ef1b5cc544c379ca78884c69b0494543f6e04#diff-826272eaeca0b3caec43718cec5fc351L87) reverted the change in selfoss-ui.js only.

**Comment by niol** [comment]
This failure prevents the ui from being updated if you've read some items on another device (shows read items as read and updates unread counts) while selfoss was open on another.
You seem to have sorted this out, maybe you can submit a pull request?
