### ISSUE TITLE
No Items in feed

### ISSUE THREAD

**Issue by tokudan** [SSilence/selfoss#1038]
The following feed seems to be added just fine and the name is recognized, but items never show up:
http://ocremix.org/torrents/rss
I do not see any errors in data/logs/default.log.

Just to avoid misunderstandings: OCRemix publishes only their own content.

**Comment by jtojnar** [comment]
The feed works fine for me:

![image](https://user-images.githubusercontent.com/705123/39266546-912f1712-48ca-11e8-8d3b-fcf60904f104.png)

What version of selfoss and spout do you use? Do you see anything in the log when you set `logger_level=DEBUG` in your `config.ini` and change `DEBUG` to `1` in `common.php`, after refreshing the source?

**Comment by jtojnar** [comment]
Actually, it looks like the articles are all quite old, so selfoss probably removes them. You can increase `items_lifetime` in your `config.ini` (it defaults to 30).

**Comment by tokudan** [comment]
... it was the lifetime. Thanks for noticing my error :)
