### ISSUE TITLE
Unable to run selfoss after 2.18 update

### ISSUE THREAD

**Issue by ShachMaT** [SSilence/selfoss#1039]
Hi,

After update from 2.17 to 2.18 i am unable to run app due to error:
`selfoss.ERROR: Undefined property: helpers\View::$loggedin`

Page stops loading midway:
```html
<!-- navigation search input just for smartphone version -->
<div id="nav-search" role="search">
<input type="search" id="nav-search-term"> <input type="button" id="nav-search-button" value="search">
<hr>
</div>

an error occured
```

I got the package from homepage. Update instruction were followed to the point.

From what i found this is the [changed line](https://github.com/SSilence/selfoss/commit/bfda0740fa7f3e9ae04bd26b54ef815ab46e896b#diff-939c7b7e0eb87dcc72393d9638be4534L37) that removed `$loggedin` variable.

Even if i login by displaying login form with CSS after successful authentication i get blank page with `an error occured` and HTTP Response `405 Method Not Allowed`

2.17 worked like a charm.

**Comment by jtojnar** [comment]
Thanks for reporting. I guess `$this->loggedin === true` is not needed there, since user should always be considered authenticated when authentication is disabled. cc @niol

**Comment by ShachMaT** [comment]
Sadly this problem goes deeper.

Even if removed the check in [this](https://github.com/SSilence/selfoss/blob/0d75b5cde9c99517dd81d045d8a35a1208b48e99/templates/home.phtml#L145) file this cause error `$this->content;` ([here](https://github.com/SSilence/selfoss/blob/0d75b5cde9c99517dd81d045d8a35a1208b48e99/templates/home.phtml#L173)) is not set and page still fails to load.

My instance is not public if that changes anything.

**Comment by jtojnar** [comment]
Hmm, I forgot to enable `error_reporting` on my dev server. Now, I can see the error too.

The `content` part should be removed as well, it is not used since 41a68b91e41deed50dfbb5485f8ebbd9d8653e0d.

**Comment by jtojnar** [comment]
Actually, I can get the notice trying to access a non-existing object property in `php -a`, but in selfoss, something absorbs it. We really should get rid of fatfree, it is completely unpredictable bowl of spaghetti.

**Comment by niol** [comment]
I cannot get the errors but I'm proposing a fix. Please test and report back for other errors.
