### ISSUE TITLE
Selfoss 2.18 does not work with PHP 7.2

### ISSUE THREAD

**Issue by sideeffect42** [SSilence/selfoss#1049]
I used the release tarball from the [Selfoss homepage](https://selfoss.aditu.de) to set up a Selfoss installation on top of PHP 7.2.
This would not work because of this bug https://github.com/bcosca/fatfree-core/issues/238.

After updating the fatfree-core package using Composer Selfoss works with PHP 7.2.
The release tarball on the website should be updated so that Selfoss can be used with PHP 7.2. Thanks :-)

**Comment by Razor-13** [comment]
> After updating the fatfree-core package using Composer Selfoss works with PHP 7.2.

How to do that? I can't get selfoss to work with PHP 7.2

**Comment by jtojnar** [comment]
> How to do that?

See the Git-tracked source code in the [download section](https://github.com/SSilence/selfoss#download) of the README file.

However, I have pushed an update (a1f711256560e5be92f224e7207d04e1632a48de), so you can just download the [preview version](https://bintray.com/fossar/selfoss/selfoss-git/2.19-a1f7112) and use it as you would a standard release. Do not forget to check the [NEWS](https://github.com/SSilence/selfoss/blob/5630b802267f72740ce3e5b38c33813b85569416/NEWS.md#219--unreleased) file.
