### ISSUE TITLE
Fetching tumblr feeds fails in EU

### ISSUE THREAD

**Issue by max-te** [SSilence/selfoss#1050]
In the EU any tumblr page, including the rss feed, redirects you to their GDPR consent page, unless you have a consent cookie set. This results in `error loading feed content: http://tigsource.tumblr.com/rss is invalid XML, likely due to invalid characters. XML error: XML_ERR_NAME_REQUIRED at line 50, column 29`. See https://github.com/simplepie/simplepie/issues/587 for the related SimplePie issue.
For TinyTinyRSS there is [a plugin](https://github.com/GregThib/ttrss-tumblr-gdpr) which works around this.

**Comment by max-te** [comment]
Well, to be honest I don't know if the GDPR redirection is the actual issue; loading the feeds via curl with a Selfoss User-Agent-String I get the normal feed.
However with selfoss I get an error (with both the tumblr user spout and the rss feed spout) and the error is always line 50, column 29.

Let me see if I can get selfoss to give me a dump of the file it fails on.

**Comment by max-te** [comment]
Okay I can confirm that it does in fact give me the GDPR page.

**Comment by jtojnar** [comment]
I tried various user agents but to no avail. I contacted tumblr using their support form, hopefully they will fix it.

**Comment by jtojnar** [comment]
Oh, this one seems to work:

```patch
--- a/spouts/rss/feed.php
+++ b/spouts/rss/feed.php
@@ -143,7 +143,7 @@
         @$this->feed->set_cache_duration(1800);
         @$this->feed->set_feed_url(htmlspecialchars_decode($params['url']));
         @$this->feed->set_autodiscovery_level(SIMPLEPIE_LOCATOR_AUTODISCOVERY | SIMPLEPIE_LOCATOR_LOCAL_EXTENSION | SIMPLEPIE_LOCATOR_LOCAL_BODY);
-        $this->feed->set_useragent(\helpers\WebClient::getUserAgent(['SimplePie/' . SIMPLEPIE_VERSION]));
+        $this->feed->set_useragent(\helpers\WebClient::getUserAgent(['SimplePie/' . SIMPLEPIE_VERSION, 'like Googlebot']));
 
         // fetch items
         @$this->feed->init();
```

Kudos [FreshRSS](https://github.com/FreshRSS/FreshRSS/blob/3306a1679c2570c30d4b662c887b4a71ce147398/extensions/Tumblr-GDPR/extension.php).

**Comment by jtojnar** [comment]
I received a reply from Tumblr, they are working on it:

> I wanted to give you a quick status update on the issue you reported. Our engineers are actively working on this bug, but it’s going to take some more time to fully resolve. Thank you for your patience

**Comment by iBook140** [comment]
Didn’t work for me. Any other suggestions?

**Comment by jtojnar** [comment]
Apparently, Tumblr broke again. It needs to cointain  `Baiduspider`: https://github.com/FreshRSS/FreshRSS/pull/2053

**Comment by jtojnar** [comment]
It seems to work now.
