### ISSUE TITLE
manual troubleshooting for "invalid" feed

### ISSUE THREAD

**Issue by simonk9** [SSilence/selfoss#1051]
Hi,
the following feed is valid:
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.clearskysec.com%2Ffeed%2F

however, i get the following error:

2018-09-03 18:13:34error loading feed content: https://www.clearskysec.com/feed/ is invalid XML, likely due to invalid characters. XML error: Mismatched tag at line 7, column 15

how can i troubleshoot that, and fix that, as the feed is correct...

**Comment by niol** [comment]
This feed works fine on my installation.
In order to troubleshoot that, I would start by putting ```logger_level=DEBUG``` in ```config.ini```, run a feed update and look into ```data/log/default.log``` for clues.

**Comment by simonk9** [comment]
@niol thank you for the input, and for checking, i did some manual tests, and i suspect it is a User-Agent problem.

**Comment by simonk9** [comment]
it was indeed User agent issue, unfortunately changing the UA manually fixed the error for this feed, but 99% of the other feeds got broken.

**Comment by jtojnar** [comment]
I recommend removing SimplePie from the UA string: https://github.com/SSilence/selfoss/pull/1052/commits/c817b20b8e2239508dd1b144cee18ee443bbbd73
