### ISSUE TITLE
password ? what password?

### ISSUE THREAD

**Issue by Unixware** [SSilence/selfoss#1053]
documentation says there should be a mysite/selfoss/password , something that does not exist.. so?

**Comment by niol** [comment]
If I go to https://mysite.example.com/password it works. Without knowing your setup, it is difficult to help you further.

**Comment by Unixware** [comment]
thx I will try to figure out what's going on, I thought the password.html/php was a part of selfoss not webserver's .

**Comment by Unixware** [comment]
fuck, no luck here, what's the algorithm that I could use alternative? APR1-MD5 ? crypt()? thx

**Comment by niol** [comment]
The source is there: https://github.com/SSilence/selfoss/blob/master/controllers/Index.php#L104

If this does not work, your selfoss installation probably does not work. The one line explanations with colourful language you are providing are not enough for anyone to have a guess at what is failing. This cannot be an opened issue as is.

**Comment by Unixware** [comment]
good crypt(3) then , this will do, thx
