### ISSUE TITLE
Error importing OPML file

### ISSUE THREAD

**Issue by radek-sprta** [SSilence/selfoss#1055]
Hello,

I've just set up a Selfoss instance and everything seems to be working fine except OPML import. When I try to import my OPML file from OldReader, I get "The following feeds could not be imported" in a red rectangle with nothing else in it. Nothing shows up in the log.

**Comment by niol** [comment]
We need a failing OPML file or some verbose log output to be able to understand what is going on. Can you provide either?

**Comment by radek-sprta** [comment]
I can provide the OPML file. Do you have somewhere I could securely upload it?

**Comment by jtojnar** [comment]
You can send it to jtojnar@gmail.com and I can take a look at it.

**Comment by jtojnar** [comment]
The issue is caused by missing `text` attributes for the `outline` elements. The attribute is mandatory according to the [spec](http://dev.opml.org/spec2.html#textAttribute), so this is OldReader bug.

**Comment by radek-sprta** [comment]
Thanks for the swift response! I'll write an email to their support.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
