### ISSUE TITLE
Full-text RSS not working for specific websites

### ISSUE THREAD

**Issue by Binnette** [SSilence/selfoss#1067]
Hi @jtojnar, here is a discussion more than an issue...

If I well understand, selfoss use "Full-Text RSS" from [FiveFilters](http://fivefilters.org/content-only/). This software is licenced under AGPLV3. But they "disclose" the source code only if you buy it ([FAQ](http://fivefilters.org/content-only/faq.php)), so there is no public repository.

It seems OK to do so : [Do I need to provide access to source code under the AGPLv3 license?](https://opensource.com/article/17/1/providing-corresponding-source-agplv3-license)

But i'm not a huge fan of this way of doing. Also, they "serve" Full-Text RSS on their website, so they must "Disclose the source" ([AGPLV3](https://tldrlegal.com/license/gnu-affero-general-public-license-v3-(agpl-3.0))) but they don't... By the way, i'm not here to put them on trial...

So ! I'm looking for "free of charge disclosed source alternatives" 😉 

Note: current Full-Text RSS version is 3.9.1

| Repo | Comment | Version | Last update |
|------------|-------------|---------|-------------|
| [Full-Text-RSS old mirror](https://bitbucket.org/fivefilters/full-text-rss) | Seems to be FTR v3.5 | 3.5 | 2017-02-18 |
| [Full-Text-RSS old mirror](https://github.com/Dither/full-text-rss) | Seems to be FTR v3.2 | 3.2 | 2014-08-14 |
| [Graby](https://github.com/j0k3r/graby) | Fork of FTR v3.3 | 1.15.1 | Active ! |
| [Morss](https://github.com/pictuga/morss) | Requires Python. Do not remove adds. | ? | Active ! |
| [gpipe43](https://github.com/Boneflame/gpipe43) | Requires Python. | ? | Active ! |

I think that Graby and Morss are good alternatives. Maybe we can implement spouts whith them ? Morss requites Python, so maybe we can implement it as a "plugin" ?

Also which FTR version is embeded in selfoss ?

**Comment by jtojnar** [comment]
We actually use Graby since 2.18: https://github.com/SSilence/selfoss/pull/897

The relevant repo for issues is https://github.com/j0k3r/graby-site-config/issues

**Comment by Binnette** [comment]
This is great. So i'm gonna change spout description and the readme also. Do you agree ?

Spout description, from "RSS Feed (with Full-Text RSS)" to "RSS Feed (with Graby)"

Readme, from "Credit - FullTextRSS: http://help.fivefilters.org/customer/portal/articles/223153-site-patterns" to "Credit - Graby: https://github.com/j0k3r/graby"

**Comment by Binnette** [comment]
Ok to remove credits from "readme .md" file. But we need to put them in another file, maybe "credit.md".
Because, when I "git clone" a repo, i want to know what librairies are used. And i don't want to go on another website far away from the source code to have this information.

**Comment by jtojnar** [comment]
The spout name was changed in d344dc4d8da00d13ae2be81d4e0f4421d43e4ea7, credits will be handled in #979.
