### ISSUE TITLE
Have a way to get the current version via the API.

### ISSUE THREAD

**Issue by aminecmi** [SSilence/selfoss#1069]
Hi,

The master version/future release (2.19) has some breaking changes with tags handling.

As the users using my app are not using an up to date Selfoss version, having some way to simply get the current version would greatly help.

Thanks !

**Comment by niol** [comment]
The version is present in the HTML head of the homepage. I can propose a pull request adding an api call, please tell me what should be implemented.

**Comment by aminecmi** [comment]
@niol not sure about this, but it would be great to have some route that is accessible without login, and returns at least the version, and maybe have this route return some global settings if one day there is some.

**Comment by jtojnar** [comment]
https://github.com/SSilence/selfoss/pull/1137 adds `/api/version` endpoint and starts using semver for versioning API (separately from selfoss version). Does that work for you @aminecmi?

**Comment by aminecmi** [comment]
@jtojnar I'll have to test it, but that should do it. Thanks !

**Comment by jtojnar** [comment]
It is now in master.
