### ISSUE TITLE
Better support for firefox for android web manifest

### ISSUE THREAD

**Issue by aslmx** [SSilence/selfoss#1076]
Now that i wrote the below, some Pre-scriptum: i hope this is not covered elsewhere and i solved something which was already resolved somewhere ;)

When switching smartphones (which i apparently sometimes need to do), i always struggle to get that selfoss bookmark onto my homescreen with a proper label (not containing the number of unread itmes) and proper FavIcons.

When i created some shortcuts yesterday, I noticed that on these pages, firefox for Android shows a "add to homescreen" button in the address bar.
Selfoss (2.18) does not.

So i googled and found out what a website must supply in order to have the browser show this button.

It is not so hard in theory. You need a Webmanifest file and you have to link it in your HTML

https://developer.mozilla.org/en-US/docs/Web/Manifest

So i checked the current source code (as far as i understand this github thing) and there seem to be some manifest things, but i'm not sure whether they'd cover this feature too. 

I quickly hacked together this Manifest:
`
{
  "background_color": "purple",
  "description": "Selfoss",
  "display": "fullscreen",
  "icons": [
    {
      "src": "https://mydomain.tld/selfoss/icon-128x128.png",
      "sizes": "128x128",
      "type": "image/png"
    }
  ],
  "name": "Selfoss",
  "short_name": "Selfoss",
  "start_url": "/selfoss"
}

`

And added this lines into templates/home.phtml (~ at around line 25 seems to be a nice place)

`
   

        <link rel="manifest" href="https://mydomain.tld/selfoss.webmanifest">
`

I had some issues with the manifest file being in the selfoss folder. I suspect this is some Mod-rewrite Magic that prevents the file from being found. Whatever i tried, the file was always 404'd. So i moved the file into my webroot and changed the link in the template. Now it works!

I'm half too stupid and half too lazy to download the current development branch, properly integrate (and resolve the mod-rewrite stuff (well i suspect)) and then raise a pull request. 

So i kindly ask, whoever is able to integrate this manifest thing properly: would you mind integrating this... or better review and do it properly ;) 

Thanks!

**Comment by jtojnar** [comment]
This is part of https://github.com/SSilence/selfoss/pull/1014

**Comment by aslmx** [comment]
i suspected that this might cover it. 
But i was not sure...

Thanks for confirming then! :)

**Comment by jtojnar** [comment]
#1014 was merged.
