### ISSUE TITLE
Invalid hive key '#lang_no_title' (Firefox only?)

### ISSUE THREAD

**Issue by averageunicorn** [SSilence/selfoss#1087]
Hi! Not sure if this is the right place to ask about this, but since I can't figure it out on my own, I though I'd try.

I can't access Selfoss from Firefox (version 65.0 on Manjaro), it just says "Internal Server Error – Invalid hive key '#lang_no_title'".
It works fine in Chromium.
I could access it from Firefox in the past, but that was on an older version of Firefox and a different distro.

The error log looks like this, again only errors when I try it from Firefox:
```
2019/02/06 12:24:56 [error] 29371#29371: *263 FastCGI sent in stderr: "PHP message: Invalid hive key '#lang_no_title'
PHP message: [common.php:21] Base->set()
PHP message: [index.php:3] require()" while reading response header from upstream, client: …, server: …, request: "GET / HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "…"
```

Is this a Selfoss thing or a Firefox thing or something else?

I'm on Selfoss version 2.18, using nginx on Ubuntu 16.04.

**Comment by jtojnar** [comment]
That looks like issue in Norwegian translation that was just fixed on master. You can either update to [development build](https://github.com/SSilence/selfoss#download), or delete the `#lang_no_title` line from `public/lang/no.ini`.

**Comment by averageunicorn** [comment]
Ah, thank you! Deleting that line fixed it.
