### ISSUE TITLE
reroute() uses SERVER_NAME as base instead

### ISSUE THREAD

**Issue by lsafelix75** [SSilence/selfoss#1088]
Hi,

I encounter this strange behaviour of F3 lately. Both $f3->reroute('/en') and and $f3->reroute('en') have different behaviours. With  $f3->reroute('/en'), the rerouted URL has the 'base url' change to SERVER_NAME defined in NGINX ini, whilst $f3->reroute('en') maintain the 'base url'. Is this an expected bahavior?

**Comment by jtojnar** [comment]
Opened upstream https://github.com/bcosca/fatfree/issues/1140
