### ISSUE TITLE
Cannot view all items

### ISSUE THREAD

**Issue by tuur29** [SSilence/selfoss#1089]
#1014 added the functionality to work offline and it's great. 

However I can no longer access my old read items. I can see the amount of items next to the newest menu item (16/1641) and see those 16 items loaded after the upgrade, more are downloaded when I refresh my sources. But I cannot see all (non-offline) items. They do show when searching.

This problem might be limited to my fork, but the intended functionality isn't clear to me which makes this very hard to debug. Should the application be downloading them in the background or load them when I view /newest/all or am I missing something else?

**Comment by niol** [comment]
As a workaround, you can always disable offline by logging out.
Regarding items that are not in the offline db, selfoss should know when items are to be found online only. It should switch from querying the offline db to requesting `/?offset...` on the server automatically. 
The intent is to have unread and starred items available offline, and then cleanup items older by 10 days, not unread, not starred. Maybe there's a bug somewhere, but I've tested this numerous times.

When you say that you cannot access your old read items, is it that the "more" button does not show?

**Comment by tuur29** [comment]
Aah then it's working as intended. It's only syncing items from the last 10 days + unread and starred. Is there a reason why you don't just sync all items?

I can access them in normal mode just fine, thanks.

**Comment by niol** [comment]
Syncing all items is too much for offline storage (especially on mobile devices), given that users may have a large number of items.
Regarding accessing old read items, let me repeat myself: you should not have to log out and log in again without offline storage to read them. If that's the case, there's a bug I need to look into: selfoss should switch from querying the offline db to requesting on the server automatically.

**Comment by tuur29** [comment]
Alright.
I looked around for a possible cause and found my problem happens after reloading the page with devtools opened and the "disable cache" flag enabled on the network tab. Once I do this, the only way to fix it is to login again.
I've tested this on master and the problem pops up there as well.

**Comment by niol** [comment]
Opening devtools and disabling cache should not modify the behaviour. When you say that you cannot access your old read items, is it that the "more" button does not show?

**Comment by tuur29** [comment]
That is correct. I have `auto_stream_more` enabled with `items_perpage=50` with 40 items synced. Changing either of these settings have no effect on the problem. After loading 40 items the more buttons doesn't show.

**Comment by niol** [comment]
I'll look into this. Maybe `auto_stream_more` enabled or `items_perpage > ` items sync is causing problems.

**Comment by niol** [comment]
OK this was a problem with `items_perpage > ` items synced, the following should fix this:

```patch
--- a/public/js/selfoss-db.js
+++ b/public/js/selfoss-db.js
@@ -594,7 +594,7 @@ selfoss.dbOffline = {
                     }
 
 
-                    if (seek && !ascOrder && !alwaysInDb
+                    if (!ascOrder && !alwaysInDb
                     && entry.datetime < selfoss.dbOffline.newestGCedEntry) {
                         // the offline db is missing older entries, the next
                         // seek will have to find them online.
```

Does that work for you?

**Comment by tuur29** [comment]
Ah yes, that fixed it. Thanks!

**Comment by niol** [comment]
fixed in https://github.com/SSilence/selfoss/commit/dec4c4f32723fca28819c0e785fbde370b92f9bf
