### ISSUE TITLE
Pregenerate all.css and all.js

### ISSUE THREAD

**Issue by nijave** [SSilence/selfoss#1097]
Is there a way to pregenerate all.js and all.css in public/? I'd like to keep these files read-only by the web server

**Comment by niol** [comment]
Dropping a php script like this (adapted from `index.php`) in root and running it using the php interpreter should work:
```php
<?php

chdir(__DIR__);
require __DIR__ . '/common.php';

// Load custom language
$lang = $f3->get('language');
if ($lang != '0' && $lang != '') {
    $f3->set('LANGUAGE', $lang);
}

/** @var stdClass JS client package manifest */
$clientPackage = json_decode(file_get_contents(__DIR__ . '/public/package.json'));

// define js files
$js = $clientPackage->extra->requiredFiles->js;
if (file_exists('user.js')) {
    $js[] = 'user.js';
}
$f3->set('js', $js);

// define css files
$css = $clientPackage->extra->requiredFiles->css;
if (file_exists('user.css')) {
    $css[] = 'user.css';
}
$f3->set('css', $css);

$view = new \helpers\View();
```

Note that you may have a problem from favicons, logs, sqlite database, which are still written by the webserver user to the selfoss directory.

**Comment by jtojnar** [comment]
Also note that with https://github.com/SSilence/selfoss/pull/1096, the assets will no longer be generated dynamically

**Comment by nijave** [comment]
Thanks guys--running a Docker container and trying to have as much prepared ahead of time as possible
