### ISSUE TITLE
Review of current share button

### ISSUE THREAD

**Issue by Binnette** [SSilence/selfoss#1105]
Hi, here is a quick review of the "share" buttons:
![image](https://user-images.githubusercontent.com/6597721/57799713-fb13a080-774f-11e9-870f-1b02a4cff840.png)

We have:

- Google+ => but Google+ is dead since since april 2019 (https://plus.google.com/)
- Twitter, Facebook, Pocket, Delicious, Mail =>

I think that we can remove Google+ and instead add a button "copy to clipboard". This new button will copy the link to the original article in clipboard. Then users can paste the link every where : in a document, in a mail, in a messenger ans so on. What do you think ?

**Comment by jtojnar** [comment]
Yeah removing g+ is a good idea.
Copy to clipboard sounds good too, though that one is a more complicated since we need to come up with a UI to let the user know that the link was copied.

Also related #719

**Comment by aslmx** [comment]
Quick (and not yet educated) thought: why not use the kind of Toast notification that is used to indicate errors (e.g. the errors that are shown when an item can't be marked as read etc.)

**Comment by jtojnar** [comment]
Yup, that was my thinking as well.

If anyone has a capacity to tackle this, it should be pretty easy.

**Comment by jtojnar** [comment]
https://github.com/SSilence/selfoss/pull/1121 removed the G+ & del.icio.us, so we can focus on the copy button.
