### ISSUE TITLE
[development branch] mark read without offline storage

### ISSUE THREAD

**Issue by herrxyz** [SSilence/selfoss#1107]
when I do not want to use "offline storage", I can not mark items as read.
If I click "mark as read", it just dont do it. after reloading (by selecting a filter or reloading the page) the following red error appears: "cannot mark/unmark item: error"
selfoss 2.19-5c5beba and some versions before

**Comment by niol** [comment]
I cannot reproduce.
Is something shown in ``data/logs/default.log``?
When you get the red error "cannot mark/unmark item: error", what's the body of the response to the ``POST`` request? You can view this [using your web browser developer tools](https://stackoverflow.com/questions/15603561/how-can-i-debug-a-http-post-in-chrome).

**Comment by herrxyz** [comment]
in log: "[2019-05-22 17:49:39] selfoss.ERROR: HTTP 403 (POST /items/sync)"
in POST
`
Request URL: https://www.xxx.de/selfoss/mark/297492
Request Method: POST
Status Code: 500 
Remote Address: 62.108.32.130:443
Referrer Policy: no-referrer
cache-control: no-cache, no-store, must-revalidate
content-type: text/html; charset=UTF-8
date: Wed, 22 May 2019 15:50:32 GMT
expires: Thu, 01 Jan 1970 00:00:00 +0000
pragma: no-cache
server: nginx
status: 500
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
:authority: www.xxx.de
:method: POST
:path: /selfoss/mark/297492
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9,de;q=0.8
content-length: 0
cookie: PHPSESSID=xxxx
origin: https://www.xxx.de
user-agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
x-requested-with: XMLHttpRequest
`

**Comment by herrxyz** [comment]
browser-console also shows
/selfoss/items/sync:1 Failed to load resource: the server responded with a status of 403

**Comment by niol** [comment]
What's the response body of the ``POST`` request that leads to a 500 response? Logs?

**Comment by herrxyz** [comment]
in log, there is nothing else
in console
`
POST https://www.xxx.de/selfoss/mark/297556 500
send @ all.js?v=1558086675:578
ajax @ all.js?v=1558086675:554
(anonymous) @ all.js?v=1558086675:1786
dispatch @ all.js?v=1558086675:296
elemData.handle @ all.js?v=1558086675:283
`
in response (hope this is the thing you requested)
`
{"status":"Internal Server Error","code":500,"text":"Fatal error: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead.","level":0}
`

**Comment by niol** [comment]
This should happen also with offline mode activated, but the error is hidden. This is not related to offline mode. Did you install from tarball or from git? If you installed from tarball, did you issue ``composer update``?
I'm not sure what's wrong here, you're installation seems a bit broken, the ``403`` response to the ``sync`` request means you're not logged in but the login screen should show.

**Comment by jtojnar** [comment]
We have seen

> "Fatal error: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead.

few times before

https://github.com/SSilence/selfoss/issues/990
https://github.com/SSilence/selfoss/issues/643

Perhaps the HTTP request is missing `Content-Type` header or POST data? Could you check that in the developer console as well?

**Comment by herrxyz** [comment]
i installed it from https://bintray.com/fossar/selfoss/selfoss-git using zip-file

in my case, this problem only occurs if I disable "offline storage", if I logout and enable it again everything works well

**Comment by niol** [comment]
Can you provide some server log of it working well?

**Comment by herrxyz** [comment]
don't know which log exactly you need :-(

both parts were created when I enabled offline-storage, marked an unread item as read and reloaded the page

access log:
```
XXXIPXXX - - [29/May/2019:17:52:58 +0200] "GET /selfoss/favicons/915af7dfa902340df891d9f91379292d.png HTTP/1.0" 200 6365 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
XXXIPXXX - - [29/May/2019:17:53:00 +0200] "POST /selfoss/items/sync HTTP/1.0" 200 778 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
XXXIPXXX - - [29/May/2019:17:53:01 +0200] "GET /selfoss/tagslist HTTP/1.0" 200 954 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
XXXIPXXX - - [29/May/2019:17:53:01 +0200] "POST /selfoss/items/sync HTTP/1.0" 200 720 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
XXXIPXXX - - [29/May/2019:17:54:16 +0200] "POST /selfoss/mark/299506 HTTP/1.0" 500 887 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
XXXIPXXX - - [29/May/2019:17:54:22 +0200] "GET /selfoss/favicons/d94a087b497932b52121f08f0e6a108c.png HTTP/1.0" 200 875 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
XXXIPXXX - - [29/May/2019:17:54:10 +0200] "GET /selfoss/Update HTTP/1.0" 200 766 "-" "Wget/1.18 (linux-gnueabihf)"
XXXIPXXX - - [29/May/2019:17:54:42 +0200] "POST /selfoss/mark/299511 HTTP/1.0" 500 887 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
XXXIPXXX - - [29/May/2019:17:55:00 +0200] "POST /selfoss/items/sync HTTP/1.0" 200 778 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
XXXIPXXX - - [29/May/2019:17:55:01 +0200] "GET /selfoss/tagslist HTTP/1.0" 200 955 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
XXXIPXXX - - [29/May/2019:17:55:01 +0200] "POST /selfoss/items/sync HTTP/1.0" 200 720 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
```


error_log:
```
[Wed May 29 17:52:30.475520 2019] [fcgid:warn] [pid 4533] [client XXXIPXXX:44497] mod_fcgid: stderr: [Unknown:0] 
[Wed May 29 17:52:57.646036 2019] [fcgid:warn] [pid 4533] [client XXXIPXXX:44622] mod_fcgid: stderr: Fatal error: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead.
[Wed May 29 17:52:57.646137 2019] [fcgid:warn] [pid 4533] [client XXXIPXXX:44622] mod_fcgid: stderr: [Unknown:0] 
[Wed May 29 17:54:17.259659 2019] [fcgid:warn] [pid 26140] [client XXXIPXXX:44986] mod_fcgid: stderr: Fatal error: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead.
[Wed May 29 17:54:17.259833 2019] [fcgid:warn] [pid 26140] [client XXXIPXXX:44986] mod_fcgid: stderr: [Unknown:0] 
[Wed May 29 17:54:42.585480 2019] [fcgid:warn] [pid 4660] [client XXXIPXXX:45121] mod_fcgid: stderr: Fatal error: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead.
[Wed May 29 17:54:42.585596 2019] [fcgid:warn] [pid 4660] [client XXXIPXXX:45121] mod_fcgid: stderr: [Unknown:0] 
```
both logs are from server and not from selfoss/data/logs/default.log as there is nothing logged if there is no problem

**Comment by niol** [comment]
OK so this fails in the same way with offline storage enabled (see the ``500`` status code to ``/selfoss/mark/id`` request). So this is not related to offline storage.

What's the value of ``always_populate_raw_post_data`` in your ``php.ini``?

**Comment by herrxyz** [comment]
unfortunately I can not read php.ini (shared hosting)
but during my search for it, I recognized my php version was outdated.
with newer version (now on 7.3.5) it works again when I disable offline storage
-> to solve this problem: use newer php version
thank you very much for your helping attitude :)
