### ISSUE TITLE
load list error: error internal server error

### ISSUE THREAD

**Issue by oxxz** [SSilence/selfoss#1112]
i installed selfoss today and just got it up running, except for an error im getting. when i enter my selfoss instance, i immediatly get an red border at the top of the page saying `load list error: error internal server error`. when i checked the log i found this

```
[2019-06-24 19:25:28] selfoss.ERROR: could not find driver {"exception":"[object] (PDOException(code: 0): could not find driver at /var/www/html/vendor/bcosca/fatfree-core/db/sql.php:519)
[stacktrace]
#0 /var/www/html/vendor/bcosca/fatfree-core/db/sql.php(519): PDO->__construct('sqlite:data/sql...', NULL, NULL, Array)
#1 /var/www/html/daos/sqlite/Database.php(33): DB\\SQL->__construct('sqlite:data/sql...')
#2 /var/www/html/daos/Database.php(25): daos\\sqlite\\Database->__construct()
#3 /var/www/html/daos/Tags.php(24): daos\\Database->__construct()
#4 /var/www/html/controllers/Index.php(48): daos\\Tags->__construct()
#5 /var/www/html/vendor/bcosca/fatfree-core/base.php(1806): controllers\\Index->home(Object(Base), Array, 'controllers\\\\Ind...')
#6 /var/www/html/vendor/bcosca/fatfree-core/base.php(1627): Base->call(Array, Array, Array)
#7 /var/www/html/index.php(80): Base->run()
#8 {main}
"}
```
if im looking at line 519 in sql.php i see a line that doesnt say much to me `$this->pdo=new \PDO($dsn,$user,$pw,$options);`.

im running this on ubuntu 18.04 vps with nginx and sqlite and as i understand with sqlite i shouldnt put any db info in the config. db_database, db_username, db_password, db_port and db_prefix is empty.

it may be something very obvious so someone, but as im not very experienced with this kind of stuff i have no idea what the problem could be. if there is any more info i forgot im glad to provide it! and to be clear, i havent even added any feeds or anything. this was the first state i got on the website

**Comment by jtojnar** [comment]
Missing driver means that PHP sqlite module is missing. Do you have [`php-sqlite3`](https://packages.ubuntu.com/search?keywords=php-sqlite3) package installed?

**Comment by niol** [comment]
You seem to be missing the php sqlite extension.
`sudo apt install php-sqlite3` should fix this.

**Comment by oxxz** [comment]
@jtojnar @niol wow, that was kind of embarrasing, i think i installed sqlite3 and not php-sqlite3, now the message is gone. thanks for two unbelievable fast answers :D
