### ISSUE TITLE
Use Tags as folders

### ISSUE THREAD

**Issue by Offerel** [SSilence/selfoss#1113]
After importing a OPML file from Inoreader, it has also imported my folders from Inoreader as Tags. Thats great so far.

But now I have seen that the sources are displayed independently of the tags in the sidebar. 

I wanted to ask if it is possible to use the displayed tags as folders, so that you can expand/collapse the different tags and see the sources underneath that tag in the sidebar, instead of the separate source area.

**Comment by jtojnar** [comment]
This is not currently possible.

Also a duplicate of https://github.com/SSilence/selfoss/issues/786
