### ISSUE TITLE
Optionally disable SSL check for dedicated feeds

### ISSUE THREAD

**Issue by Offerel** [SSilence/selfoss#1115]
Could you please add a option for every subscription, so that i can disable curl SSL check for that dedicated feed? I didn't want to disable it completely, but i have subscribed to some sites, where the domain doesn't match in the SSL certificate. This feeds are broken for me. I cant retrieve the content.

The option should be disabled by default (so that ssl cert is checked)

**Comment by niol** [comment]
This is the same as #1099 and maybe #1109 . The site operators should really fix their sites.

**Comment by Offerel** [comment]
Lol, yes indeed. Curl error number is in my case 52 instead of 60 or 62.

**Comment by jtojnar** [comment]
I am vary of adding options that reduce security since it is nearly impossible to relay severity of such choice due to [warning fatigue](https://en.wikipedia.org/wiki/Alarm_fatigue).

Let’s track possible implementations through plug-ins in #1099.
