### ISSUE TITLE
selfoss iframe support?

### ISSUE THREAD

**Issue by Koroush-Net** [SSilence/selfoss#1116]
Hello

Does this script allow you to add iframe to published news?
Can you give me examples of sites that have used this script?
Currently the latest available version can be installed in php 7.2?

Also, I have a WordPress site. Can I display some of the news (headlines and links) on my site?

https://selfoss.aditu.de/forum/index.php?id=1379

Thanks

**Comment by jtojnar** [comment]
Selfoss is not a script but a web application. It cannot be embedded to other sites using frames for security reasons (we are using [`X-Frame-Options` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options) set to `SAMEORIGIN`).

I use the [latest build](https://github.com/SSilence/selfoss#download) on PHP 7.2 without any issues.

For WordPress integration, you will probably need to create a plug-in.
