### ISSUE TITLE
No icon on google news alert feed

### ISSUE THREAD

**Issue by Themroc** [SSilence/selfoss#1123]
After adding rss feed
https://www.google.de/alerts/feeds/18120933104492874959/12861401000818240705
i got no favicon.

**Comment by jtojnar** [comment]
IMHO that is a correct behaviour, as `getHtmlUrl()` method should return a webpage associated with the feed, see also the [RSS specification](https://cyber.harvard.edu/rss/rss.html):

> Element | Description | Example
> -- | -- | --
> link | The URL to the HTML website corresponding to the channel. | http://www.goupstate.com/


This corresponds to Atom’s `link[@rel=alternate]` ([relevant spec](https://tools.ietf.org/html/rfc4287#section-4.2.7.2)).

I think we should fix the Image helper to use `getXmlUrl()` when `getHtmlUrl()` returns null. Or maybe the spout’s `getIcon()` method. Not sure at the moment, the whole favicon handling is an unruly spaghettuous mess.

**Comment by jtojnar** [comment]
By the way, it is possible to request links other than `rel=alternate` by passing `self` as a [second argument](https://simplepie.org/wiki/reference/simplepie/get_link#relation) to the `SimplePie::get_link()` function.

**Comment by Themroc** [comment]
Yeah, you're right, didn't notice that. So, in this case there is no official website belonging to the feed, thus load() shouldn't pretend otherwise.
But the Image helper can't help here, because getIcon() only calls it if there's a $htmlUrl present. How about
```
    public function getIcon() {
        if ($this->faviconUrl !== null) {
            return $this->faviconUrl;
        }

        $this->faviconUrl = null;
        $imageHelper = $this->getImageHelper();
        if (! ($htmlUrl = $this->getHtmlUrl()) ) {
            $ue = parse_url($this->getXmlUrl($this->params));
            $htmlUrl = $ue['scheme'] . '://' . $ue['host'];
        }
        if ($imageHelper->fetchFavicon($htmlUrl, true)) {
            $this->faviconUrl = $imageHelper->getFaviconUrl();
            \F3::get('logger')->debug('icon: using feed homepage favicon: ' . $this->faviconUrl);
        } else {
            $feedLogoUrl = $this->feed->get_image_url();
            if ($feedLogoUrl && $imageHelper->fetchFavicon($feedLogoUrl)) {
                $this->faviconUrl = $imageHelper->getFaviconUrl();
                \F3::get('logger')->debug('icon: using feed logo: ' . $this->faviconUrl);
            }
        }

        return $this->faviconUrl;
    }

```
should fix the issue in the least invasive way (not tested). BTW, how about something like

    public function getXmlUrl(array $params = null) {
        if (! is_array($params))
            $params = $this->params;
        return isset($params['url']) ? html_entity_decode($params['url']) : null;
    }

(also not tested), wouldn't that be nice?

**Comment by Themroc** [comment]
Ooops... no, that doesn't work, $params is not the same as $this->params...

**Comment by jtojnar** [comment]
Yeah, the spouts are suboptimal as well. For now, I recommend setting the `$this->xmlUrl` in the `load` method. In the future, I want to split out the item methods from spouts, and then I will convert each spout into a proper object (instead of the mix of static class and object it is now) and the `load` method will return an array of `Item` objects.

**Comment by Themroc** [comment]
You mean $this->htmlUrl, like in that ↑ PR. But, shouldn't it better be

```
    if (empty($this->htmlUrl)) {
            $ue = parse_url($url);
            $this->htmlUrl = $ue['scheme'] . '://' . $ue['host'];
    }
```
?

**Comment by jtojnar** [comment]
I meant `xmlUrl`, since you were talking about the URL of the feed (i.e. `link[@rel=self]`).

**Comment by Themroc** [comment]
Then we probably talked at cross purposes. I thought the issue is that htmlUrl is empty. xmlUrl seems to be fine, AFAICT.

**Comment by jtojnar** [comment]
Fixed in https://github.com/SSilence/selfoss/commit/53a3f7f69141fafefc27b0f0e8ae845d4082fd68. Thanks for the report and help.
