### ISSUE TITLE
Switching from stable to Development builds

### ISSUE THREAD

**Issue by PresGas** [SSilence/selfoss#1129]
Are there any things to do or account for as one switches from the stable 2.18 version to the development builds? Obviously a full backup is advised. 

For example, I know that some of my feeds are using FullTextRSS (according to the GUI) and you have switched to Grabby. Is there something to be done to facilitate the conversion? 

Let me know if there is documentation that I may have missed.

**Comment by jtojnar** [comment]
Selfoss should upgrade the database schema automatically, so the only issues would be backwards incompatibilities. We are maintaining up to date [change log](https://github.com/SSilence/selfoss/blob/master/NEWS.md) so you should check out the changes just like when upgrading to a stable version. In your case, most notably, the minimum PHP version has been raised, the Selfoss Android app is no longer supported (Reader for Selfoss is a good replacement), and some customization options [changed](https://github.com/SSilence/selfoss/blob/master/NEWS.md#customization-changes).

**Comment by PresGas** [comment]
Thanks! I am not doing anything special with my installation WRT customization. I switched my php to 7.x some time ago. Glad to see the long article change!!
