### ISSUE TITLE
Feed autodiscovery broken

### ISSUE THREAD

**Issue by akash07k** [SSilence/selfoss#1130]
I've just installed SelfOss from latest master branch and configured everything.
But when I try But when I try to import existing opml / try to add a new feed, I get some errors like "xml contains invalid characters" etc.
What can be the issue?
and, when can we expect 2.19 release?

**Comment by jtojnar** [comment]
Do you think you could share the OPML file? You can use my private mail jtojnar@gmail.com if you don't want to share publicly. Or you could try to check the feed with https://validator.w3.org/feed/.

As for the new release, I intended to finish it during the summer but other work got in the way. The main blocker is the script caching in the offline mode, which I am not completely happy about.

**Comment by akash07k** [comment]
@jtojnar jtojnar
I've attached the xml.
Also, checked with the w3validator, no issues found.
Please check.
Changed the extention because .xml files are not allowed.
[selfoss-subscriptions (1).txt](https://github.com/SSilence/selfoss/files/3614077/selfoss-subscriptions.1.txt)

**Comment by akash07k** [comment]
@jtojnar 
But I really like selfoss.
It has changed my life completely.
you guys have developed a very excellent piece of software.

**Comment by jtojnar** [comment]
What feeds specifically do fail for you?

**Comment by akash07k** [comment]
All the feeds, except rss-ndtv

**Comment by jtojnar** [comment]
Hmm, AndroidAuthority does not seem to declare the feed anywhere. You will need to set the URL manually: https://www.androidauthority.com/feed/

But for the other sites, it should work. For some reason the SimplePie autodiscovery does not work on them.

**Comment by akash07k** [comment]
Hmm, I agree. but then why is it working properly in 2.18? this OPML is exported by selfoss 2.18 version itself.

**Comment by jtojnar** [comment]
I would guess this might be the culprit: https://github.com/SSilence/selfoss/pull/1052

Or less likely, the SimplePie. I will try to take a look later. For now, you can use the direct link to the feed.

**Comment by akash07k** [comment]
But it's not possible to find the direct link to the feed for every
website. Even, there are many websites for which miniflux and other
applications can't fetch feeds, but selfoss is able to do so. But due
to this issue in this latest branch, it's becoming difficult.

**Comment by jtojnar** [comment]
Selfoss internally uses SimplePie with [autodiscovery](https://web.archive.org/web/20110607232437/http://diveintomark.org/archives/2002/08/15/ultraliberal_rss_locator), points 1 through 5. For majority pages, point 2 is sufficient, and in Firefox, this [extension](https://addons.mozilla.org/en-US/firefox/addon/awesome-rss/) will allow you to get the feed using point 2.

It definitely needs to be fixed, though.

**Comment by akash07k** [comment]
Ok, .

**Comment by jtojnar** [comment]
`git-bisect` indeed points to 17d3029, and commenting out the following line fixes autodiscovery:

https://github.com/SSilence/selfoss/blob/158c90dbedacc48d1f69f3a9fc23c23a49d23325/spouts/rss/feed.php#L124

I suspected it could be wonky, but since I primarily use direct links to feeds, I did not notice a regression during extended testing.

As for why, the class is not documented properly and perhaps SimplePie expects some response field (e.g. headers) in a different format. I will need to dig deeper.

**Comment by jtojnar** [comment]
I confirmed that https://github.com/SSilence/selfoss/pull/1131 fixes the issue on all sites in your OPML file except for https://androidauthority.com. But it seems like that did not work on 2.18 either.

**Comment by akash07k** [comment]
yes, I just checked, androidauthority is not working on 2.18 either.
Also, there's a site: https://beebom.com and it is nlso not working.

**Comment by jtojnar** [comment]
I opened a pull request with a fix for AndroidAuthority:

https://github.com/simplepie/simplepie/pull/621

For now, you can apply it locally to `vendor/simplepie/simplepie/library/SimplePie/Locator.php`.

**Comment by jtojnar** [comment]
Hmm, I cannot find a link to that site’s feed anywhere on the site. Could you try contacting them and asking them to add `rel=alternate` link pointing there?

**Comment by akash07k** [comment]
Ok, fine.

**Comment by jtojnar** [comment]
Upgraded to SimplePie version supporting autodiscovery AndroidAuthority in cf73db2c.

**Comment by akash07k** [comment]
Thanks bro
