### ISSUE TITLE
Problematic feeds

### ISSUE THREAD

**Issue by toonn** [SSilence/selfoss#1140]
I have three feeds that fail because of XML errors but not the understanding to look into this. Are these feeds broken? Can selfoss be more lenient in its parsing of XML?

Problematic url Nr. 1: http://haskell.1045720.n5.nabble.com/Haskell-Haskell-prime-ft3195138.xml
Error:
```
error loading feed content: http://haskell.1045720.n5.nabble.com/Haskell-Haskell-prime-ft3195138.xml is invalid XML, likely due to invalid characters. XML error: Invalid character at line 396, column 13
```

Problematic url Nr. 2: https://buttercupfestival.tumblr.com/rss
Error:
```
error loading feed content: https://buttercupfestival.tumblr.com/rss is invalid XML, likely due to invalid characters. XML error: XML_ERR_NAME_REQUIRED at line 50, column 29
```

Problematic url Nr. 3: http://www.fragilestory.com/rss
```
error loading feed content: http://www.fragilestory.com/rss is invalid XML, likely due to invalid characters. XML error: > required at line 15, column 364
```

Is the problem that these aren't actually feeds? Any way to figure out feed urls if they're not linked on the site?

**Comment by jtojnar** [comment]
First one is not well-formed XML, see: https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fhaskell.1045720.n5.nabble.com%2FHaskell-Haskell-prime-ft3195138.xml

Second is a known issue of Tumblr requiring GDPR consent of machines: #1050 In the past, changing user agent to GoogleBotʼs bypassed the detection. It stopped working after few weeks. I suggest you contact Tumblr support – maybe if lot of people complain, they will fix it.

The last one redirect me to a web site and I do not see any mention of RSS feed there, or on the blog (checking the source code). Maybe they switched to a new content management system and do not provide feed anymore.

**Comment by toonn** [comment]
Thank you for looking into this so quick.

Too bad, nabble generates these from mailing lists, I'll contact support but I'm not expecting much response from their side.

Oh, tumblr, how do you always manage to come up with ways to become less and less useful?

I see you're right about fragile, sad to see yet another webcomic turn away from rss. I guess I'll have to turn to scheduled scraping : /

I'm closing this because it's clearly not something that can be fixed on selfoss' side. Keep up the good work! ❤️
