### ISSUE TITLE
Update Fatfree-core dependency for PHP 7.4

### ISSUE THREAD

**Issue by Flameborn** [SSilence/selfoss#1157]
Currently, Selfoss's command-line feed updater does not work with PHP 7.4, due to a deprecation discussed in https://github.com/bcosca/fatfree-core/issues/286

Updating the dependency should solve this issue, as the master branch has a committed fix.

**Comment by jtojnar** [comment]
Thanks for reporting. Done in https://github.com/SSilence/selfoss/pull/1158.
