### ISSUE TITLE
Cannot mark all visible item: error Internal Server Error

### ISSUE THREAD

**Issue by GutHib** [SSilence/selfoss#1166]
Hi,

It seems like Selfoss will throw an error if the number of articles it is supposed to mark as read is too high. In my testing, 700 articles still worked fine, but 1035 articles got me an Internal Server Error.

For this and other purposes, it would be nice if Selfoss had a true "mark all read" button (affecting not only the articles on screen, but all articles in the database). Just the same, a button to clean out the database and remove all articles would be great.

Thanks!

**Comment by jtojnar** [comment]
Thanks for reporting. This is already tracked in https://github.com/SSilence/selfoss/issues/1037. And mark all as read in https://github.com/SSilence/selfoss/issues/279.

**Comment by niol** [comment]
This feels like what I was trying to fix in 2497f8188db5b759bf6977f77509a0bea414ffa9 but only for offline.

**Comment by jtojnar** [comment]
Pretty sure just encoding the data as JSON should fix that.
