### ISSUE TITLE
Adding Github releases, how? 

### ISSUE THREAD

**Issue by TobiasDev** [SSilence/selfoss#1172]
Hello, 
I have tried adding GitHub releases to my selfoss but I cant figure what link to use, and what the branch means, etc? Could someone maybe explain to me how to get the RSS feeds for Github relases to work?

**Comment by jtojnar** [comment]
I recommend using extension such as [Awesome RSS](https://addons.mozilla.org/en-US/firefox/addon/awesome-rss/) to discover feeds. That will give you URL such as https://github.com/SSilence/selfoss/releases.atom. You can then add it as a regular RSS feed.

**Comment by jtojnar** [comment]
As the name suggests, the *GitHub: commits* spout is for tracking all commits in a given branch. It is somewhat redundant, as GitHub does provide regular RSS feeds the *RSS feed* spout can handle.

**Comment by TobiasDev** [comment]
Oooohhhh. Suddenly makes sense. Thanks for the answer!
