### ISSUE TITLE
Sources are empty

### ISSUE THREAD

**Issue by dgsiegel** [SSilence/selfoss#1174]
Even though I have hundres of items stored, sometimes the settings view only lists the ones with errors and not all of my sources. As it only happens sometimes, I guess this is related to specific errors of individual feeds?
![Screenshot_2020-03-01 selfoss (21)](https://user-images.githubusercontent.com/4396895/75634030-4b3def80-5c0a-11ea-84ca-a2f66582eafd.png)

Removing 

```
        <!-- error messages -->
        <?php if (isset($this->source) && isset($this->source['error'])) : ?>
        <li class="source-error">
            <?= $this->source['error']; ?>
        </li>
        <?php endif; ?>
```

in `templates/source.phtml` seems to solve this issue, so I guess it seems that the error message is not properly escaped.

**Comment by jtojnar** [comment]
Hmm, weird, I thought we escape the messages when saving them into the database. Does using `<?= htmlspecialchars($this->source['error']); ?>` fix the issue?

**Comment by dgsiegel** [comment]
Yeah that works.

**Comment by jtojnar** [comment]
Could you share an example of the error message that trips it up?

**Comment by dgsiegel** [comment]
It seems to be this feed:

http://feeds.arstechnica.com/arstechnica/open-source/

`2020-03-02 09:00:02error loading feed content: Client error: `GET http://feeds.arstechnica.com/arstechnica/open-source/` resulted in a `404 Feed not found error: FeedBurner cannot locate this feed URI.` response: <html> <head> <style type="text/css"> a:link, a:visited { color: #000099; text-decoration: underline; } a:hover { (truncated...) `

**Comment by jtojnar** [comment]
Thank you for reporting this.

**Comment by dgsiegel** [comment]
Thanks for fixing it so quickly!
