### ISSUE TITLE
Share buttons not shown in Firefox 74.0 on Linux Mint

### ISSUE THREAD

**Issue by cpu2910** [SSilence/selfoss#1176]
When previewing an article there a no share buttons visible.
In Chromium 80.0 o
![chromium80](https://user-images.githubusercontent.com/30260653/78399457-32ec3680-75f5-11ea-8c6a-a60e700c6397.jpg)
![firefox74](https://user-images.githubusercontent.com/30260653/78399460-341d6380-75f5-11ea-9e07-70cfafac93b2.jpg)

n the same PC everythings ok, also in Firefox for Android 68.6
Browsercache cleared and browser restarted.

Server: Ubuntu Server 18.04.4 LTS
Apache2.4.29
php 7.2.24
maria-db 10.1.44
Selfoss 2.19 f0759b2

**Comment by cpu2910** [comment]
I found this in the console from firefox:
Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: moz-extension://2c693d39-dd10-4647-946e-40364e3313a8/browser-polyfill.min.js
Source-Map-Adresse: browser-polyfill.min.js.map

Maybe the bug mentioned at the bottom of this page:
https://developer.mozilla.org/en-US/docs/Tools/Debugger/Source_map_errors is the reason?

I have no idea how to fix this...

**Comment by jtojnar** [comment]
Could you also try the private browsing mode? In the past, I had some issues clearing the ServiceWorker cache in Firefox.

What do you see when you enter `selfoss.shares` into the browser console? Especially the `initialized` and `enabledShares` keys. Maybe also try entering `selfoss.shares.getAll()`.

**Comment by jtojnar** [comment]
The NetworkError seems to be triggered by a Firefox extension due to a Firefox bug but it should not affect web pages.

**Comment by cpu2910** [comment]
In private browsing mode it's the same,
but in the inspector I found this code(see image), so the share buttons are in the code, but not visible.
![screenshot](https://user-images.githubusercontent.com/30260653/78402642-3be00680-75fb-11ea-8407-047b22da4442.jpg)

output from the console for selfoss.shares:
![screenshot](https://user-images.githubusercontent.com/30260653/78402977-d9d3d100-75fb-11ea-8212-81c5eb85b25f.jpg)

**Comment by jtojnar** [comment]
Interesting, that looks like the `else` branch in

https://github.com/FortAwesome/Font-Awesome/blob/4e6402443679e0a9d12c7401ac8783ef4646657f/js-packages/%40fortawesome/fontawesome-svg-core/index.es.js#L1590-L1600

is firing.

`autoA11y` seems to be on by default so I wonder why it does not seem to trigger for me. Will investigate more.

**Comment by cpu2910** [comment]
ok, too difficult for, I'm not a programmer... ;-)
But I will help with screenshots and else...

**Comment by jtojnar** [comment]
Actually, it does trigger for me. But that should not affect whether the icon is displayed.

Could you try checking out the styles in the Rules panel for the `<svg>` and `<button>`? There would have to be some rule like `display: none;`, `visibility: hidden;` or similar.

![Styles of svg element](https://user-images.githubusercontent.com/705123/78416072-71e6b000-7626-11ea-967d-4dd5152da669.png)

![Styles of button element](https://user-images.githubusercontent.com/705123/78416147-136e0180-7627-11ea-880b-cc947ba4303a.png)

**Comment by cpu2910** [comment]
Here we go...
![screenshot1](https://user-images.githubusercontent.com/30260653/78423072-120efa00-7664-11ea-82a2-aae2c33d7d38.jpg)
![screenshot2](https://user-images.githubusercontent.com/30260653/78423074-13402700-7664-11ea-939d-b4ca835d8c38.jpg)

**Comment by cpu2910** [comment]
mine is a new installation of 2.19.
Maybe I'm missing some css-files compared to my old 2.18?
Just an idea....
root@ubuntu:/var/www/html# find selfoss* -iname '*.css'
selfoss/vendor/bcosca/fatfree-core/code.css
selfoss/public/style.6cf4e278.css
selfoss-2.18/vendor/bcosca/fatfree-core/code.css
selfoss-2.18/public/css/fonts.css
selfoss-2.18/public/css/reset.css
selfoss-2.18/public/css/style.css
selfoss-2.18/public/node_modules/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.css
selfoss-2.18/public/node_modules/@fancyapps/fancybox/dist/jquery.fancybox.css
selfoss-2.18/public/node_modules/spectrum-colorpicker/spectrum.css
selfoss-2.18/public/all.css

**Comment by jtojnar** [comment]
Hmm, nothing in the part of rules I see. Could you try to open the developer tools into a separate window

![image](https://user-images.githubusercontent.com/705123/78423247-5f3f9b80-7665-11ea-8dca-26086872891f.png)

so that more of the styles is visible?

![image](https://user-images.githubusercontent.com/705123/78423271-8302e180-7665-11ea-8cf9-375aff2cee14.png)

One thing that comes to mind, do you use some kind of content blocking extension like AdBlock Plus or uMatrix. Now I vaguely recall AdBlock’s social networks list hiding the sharing buttons for me, even though they are just links, not tracking buttons. That did not affect e-mail sharing, IIRC.

**Comment by jtojnar** [comment]
We merged the CSS files into a single file in 2.19 so that looks right.

**Comment by cpu2910** [comment]
That's it, I'm using Ublock Origin. Normally it shows a counter at the icon, but there's nothing.
I switched it off and the share buttons are back again..
So simple....
Sorry for the troubles, thank you for your help.
Btw: I think SelfOss is a great project, thank you again for that!
