### ISSUE TITLE
Error using PHP 7.4

### ISSUE THREAD

**Issue by ajjackaus** [SSilence/selfoss#1180]
I recently upgraded my website to PHP 7.4 and when I load Selfoss I get the following error.
Internal Server Error
Fatal error: Module 'sqlite3' already loaded

If I revert to 7.2 or 7.3 the problem goes away.

**Comment by jtojnar** [comment]
Hi, are you running 2.18 or a development build? I am afraid that 2.18 might not work but [development builds](https://github.com/SSilence/selfoss#download) run for me without a hitch on 7.4.

**Comment by ajjackaus** [comment]
I am running 2.18. Maybe I should change to a dev build. Many thanks.

 

 

AJ Jack

**Comment by jtojnar** [comment]
Closing as a duplicate of https://github.com/SSilence/selfoss/issues/1157.
