### ISSUE TITLE
Snapshot: 2.19-76452b0 - Issues

### ISSUE THREAD

**Issue by sonicnkt** [SSilence/selfoss#1186]
Just tried the latest snapshot and noticed several issues.

The biggest one is that when selfoss updates it adds the same items all over again. So the same item gets added again and again everytime you update your feeds (Tried with RSS and RSS (Fulltext). 

i tried it with a completely clean setup and the issues still happens (sqlite db)

![selfoss-feeds-issue](https://user-images.githubusercontent.com/5454622/80921669-f8062b80-8d77-11ea-8ff4-5cec2108151b.jpg)

Another isssue i noticed is with the favicon of a specific feed that is not correct. It grabbed the correct favicon of the homepage with an older snapshot i was running before but now gets a completely different logo from the page. This icon somehow shows up even for other feeds (screenshot above).

![selfoss-favicon-issue](https://user-images.githubusercontent.com/5454622/80921686-1e2bcb80-8d78-11ea-8bb7-19716d2d99fb.jpg)

You can see the correct icon in the browser tab on the top.  (GameS...)

Gamestar.de, https://www.gamestar.de/news/rss/news.rss

**Comment by jtojnar** [comment]
The icon comes from the feed logo which you can see in https://www.gamestar.de/news/rss/news.rss (it you have some feed preview extension installed). We will need to improve the heuristics still, see #1183.

The duplication is something I did not encounter yet, must be a recent regression. Will investigate.

Thanks for reporting.

**Comment by sonicnkt** [comment]
Ah sorry, did not check that. A check to see if the feed embedded icon is "squarish" is a good solution i think.

**Comment by jtojnar** [comment]
Thanks, the duplication should be resolved in f3993503.
