### ISSUE TITLE
Add offline reading support

### ISSUE THREAD

**Issue by xavez** [SSilence/selfoss#119]
I know appcache is a bitch, but support for offline reading in browsers that support it would be great.

**Comment by niol** [comment]
I've worked on this and it is usable for me. Any feedback would be welcome. I'll make a pull-request when I've used it a bit more. https://github.com/niol/selfoss/tree/ppr/offline

**Comment by jtojnar** [comment]
This has been implemented in https://github.com/SSilence/selfoss/pull/1014
