### ISSUE TITLE
Unexpected die when there is a PHP startup error.

### ISSUE THREAD

**Issue by phith0n** [SSilence/selfoss#1192]
As I know, PHP startup error will not affect the normal application. But when I use *selfoss* in a virtual host service(I am not able to modify the PHP.INI), an unexpected error is thrown:

```
Fatal error: PHP Startup: Unable to load dynamic library 'imagick.so' (tried: /opt/cpanel/ea-php73/root/usr/lib64/php/modules/imagick.so (libMagickWand.so.5: cannot open shared object file: No such file or directory), /opt/cpanel/ea-php73/root/usr/lib64/php/modules/imagick.so.so (/opt/cpanel/ea-php73/root/usr/lib64/php/modules/imagick.so.so: cannot open shared object file: No such file or directory))
```

Because there is a startup error checker in the Fatfree framework: <https://github.com/bcosca/fatfree-core/pull/125>, the application will be exit when a start error exists.

You can disable the checker `error_reporting(0)` to solve this problem.

**Comment by jtojnar** [comment]
Ugh, I really hate it when F3 does “smart” things like this without a sensible way to disable the behaviour.

Fortunately, if I am parsing the code correctly, there should be no code path that has the error handler set up and error reporting disabled so just plopping `error_reporting(0)` before the following should be fine:

https://github.com/SSilence/selfoss/blob/defe8424991468c416e19243469cb7ce87b22d51/src/common.php#L18

**Comment by phith0n** [comment]
Yep

**Comment by jtojnar** [comment]
I opened a PR with a fix: https://github.com/SSilence/selfoss/pull/1195
