### ISSUE TITLE
throw item doesn't mark it as read

### ISSUE THREAD

**Issue by davidoskky** [SSilence/selfoss#1193]
I just upgraded from 2.18 to 2.19-defe842.
The upgrade went well as I followed the instructions, although when I press t or T to throw an item, the item gets marked as read and the next article is opened.
The problem is that when I reload the page, those articles aren't marked as read anymore.
There is no problem of this kind whenever I mark the article as read through the shortcut m or clicking the icon.

**Comment by jtojnar** [comment]
Thanks for reporting, this should be fixed in a46ed9180601016be0e7ad41ec536cda8435d795.
