### ISSUE TITLE
Loglevel ingored for /dev/stderr output?

### ISSUE THREAD

**Issue by sonicnkt** [SSilence/selfoss#1196]
I updated my homeserver a few weeks back and put everything into docker containers.
Im using https://github.com/TrafeX/docker-php-nginx to run the latest nightly built of selfoss (selfoss-2.19-9f41abb.zip).

This container pipes every output of its services into the docker logs, im now facing the issues that selfoss seems to pipe the whole debug output into /dev/stderr regardless of the loglevel set in the config.ini, this setting seems to apply only to the builtin logging method 

Since im using graby for many rss feeds these logs grow huge quite fast. 

I have reported this here https://github.com/TrafeX/docker-php-nginx/issues/37 before but it seems to be a issues with selfoss itself and not the docker container.

**Comment by jtojnar** [comment]
How did you set up your logging configuration, especially `logger_destination` and `logger_level`?

**Comment by jtojnar** [comment]
Hmm, never mind, I can reproduce it. Looks like Graby logger got disconnected from the main logger during refactoring. Thanks for bringing this to my attention.
