### ISSUE TITLE
Selfoss shows blank page

### ISSUE THREAD

**Issue by heull001** [SSilence/selfoss#1199]
I try to run Selfoss on Apache and PHP 7.4. The database was created, but Selfoss doesn't work. It shows a blank page, I can't even login.

Selfoss Version is 2.19-3e93a10

There are no error-messages in logfile.

**Comment by jtojnar** [comment]
Thanks for reporting.

1. Do you see anything in the browser console (<kbd>F12</kbd> → Console)?
2. What is the status of the page in the Network panel in the developer page?
3. Do you see anything in the source code (<kbd>ctrl</kbd>-<kbd>u</kbd>)?

**Comment by heull001** [comment]
# 1.
> WarnungLaden fehlgeschlagen für das <script> mit der Quelle "domain.tld/js.d6b27834.js".
> domain.tld:1:1

# 2.
> TypGrößeÜbertragenZeitNicht-blockierte Zeit
> 5html2,00 KB2,45 KB0,18 s0,18 s
> Antworten aus dem Cache: 0Anfragen gesamt: 5Größe: 2,00 KBÜbertragene Größe: 2,45 KBZeit: > 0,18 SekundenNicht-blockierte Zeit: 0,18 Sekunden

# 3.
> <!doctype html>
> <html>
> <head>
> <meta charset="utf-8">
> <title>selfoss</title>
> <meta name="referrer" content="no-referrer"><meta name="viewport" content="width=device-width, user-scalable=yes, initial-scale=1">
> <meta name="viewport" content="initial-scale=1, user-scalable=yes" media="(device-height: 568px)">
> <meta name="application-name" content="selfoss">
> <meta name="apple-mobile-web-app-capable" content="yes">
> <meta name="mobile-web-app-capable" content="yes"><link rel="apple-touch-icon-precomposed" href="icon-128x128.7be57b65.png">
> <link rel="icon" type="image/png" href="icon-32x32.15a3e8ca.png">
> <link rel="shortcut icon" type="image/x-icon" href="favicon.97cdf3fd.ico"><meta name="theme-color" content="#191718">
> <link rel="stylesheet" href="style.2e171850.css"><link rel="manifest" href="selfoss.webmanifest">
> </head>
> <body> 
> <div id="message"></div> 
> <script src="js.d6b27834.js">
> </script>
> </body>
> </html>

Do you need any translation?

**Comment by heull001** [comment]
Damn, many tags are filtered by Github, but I think <script src="js.d6b27834.js"> </script> in body could be the most important information.

**Comment by jtojnar** [comment]
Is there a status code in the network panel? What do you see if you try to visit `domain.tld/js.d6b27834.js`?

Do you have the `.htaccess` file in the selfoss directory? Another thing to check if Apache’s `mod_rewrite` is enabled.

**Comment by heull001** [comment]
Oh no, fixed, that's painful. "AllowOVerride All" was missing in the server-configuration ...
