### ISSUE TITLE
OPML import doesn't work

### ISSUE THREAD

**Issue by heull001** [SSilence/selfoss#1200]
I'm migrating Selfoss to another Server. So I exported an OPML-File from the old, selfoss 2.18.
Now I try to import on the new, 2.19-3e93a10, and get the Message: "Unexpected happened." Clicking on "details" brings "{}".

Error-log:
[2020-06-13 11:21:16] selfoss.ERROR: HTTP 403 (GET /sources)                                                            
[2020-06-13 11:22:14] selfoss.ERROR: Call to undefined function controllers\Opml\simplexml_load_file() {"exception":"[ob
ject] (Error(code: 0): Call to undefined function controllers\\Opml\\simplexml_load_file() at selfosspath/src/controllers/Opml/Import.php:72)                                                                           
[stacktrace]                                                                                                            
0 selfosspath/vendor/bcosca/fatfree-core/base.php(1927): controllers\\Opml\\Import->add()      
1 selfosspath/vendor/bcosca/fatfree-core/base.php(1727): Base->call()                          
2 selfosspath/index.php(57): Base->run()                                                       
3 {main}                                                                                                               
"}

**Comment by jtojnar** [comment]
Hmm, do you have a PHP xml extension installed? According to https://www.php.net/manual/en/simplexml.installation.php it should be [`php-xml`](https://packages.debian.org/sid/php-xml) package on Debian.

We should of course improve the error message or use a fallback library when SimpleXML is not found.

**Comment by jtojnar** [comment]
Thanks for reporting, I have added a check that should make the fix clearer.
