### ISSUE TITLE
set password

### ISSUE THREAD

**Issue by seyo-IV** [SSilence/selfoss#1207]
im trying to set a password but it wont accept the one in config.ini... when i set it i get the logoin screen but it allways says password or username incorrect. config.ini is readable by the user that runs php and nginx.

**Comment by jtojnar** [comment]
What version of selfoss do you use? Did you create the password hash using selfoss’s tool (`https://your_selfoss_url.com/password`)?

**Comment by seyo-IV** [comment]
sry noob question i generated the hash, waht do i do with the hash then?

**Comment by seyo-IV** [comment]
sry im dumb, i generated the hash and set it in the config.ini, sry again for my noobnes.
