### ISSUE TITLE
Auto-scroll to currently open article

### ISSUE THREAD

**Issue by gavrochelegnou** [SSilence/selfoss#154]
When using the shortcut "t", it would be nice to have the page autoscroll to the top of the next article. This would allow to have the maximum reading area available for articles and to always have the title of the articles at the same reading spot.
Would be great in "mobile" version to have a button "Mark as read and open the next article"(throw)

**Comment by Poorchop** [comment]
Can someone make scrolling animations a user preference? When I'm going through a huge list of stories and I start cilcking on things, selfoss jumps all over the place and if I'm not paying too much attention, I can kind of get lost as to where I am on the page. A slower, smoother scroll animation would make it much easier to rapidly go through large lists of the unread stories.
