### ISSUE TITLE
Option to filter out (already marked as) read articles / starred articles

### ISSUE THREAD

**Issue by GLLM** [SSilence/selfoss#187]
Hi all !

A button/posibility to see switch back and forth from only unread articles to all articles would be great !

Same for starred items vs. all items.

My first post/git/anything on GitHub, so please forgive me if I've done it wrong !
Super duper RSS server btw !

Cheers,
GLLM

**Comment by jtojnar** [comment]
I am not convinced this feature is used often enough to warrant cluttering the screen. Two taps should be all right.
