### ISSUE TITLE
Make selfoss navigable

### ISSUE THREAD

**Issue by makkes** [SSilence/selfoss#243]
Currently when you're navigating around in the application the URL in the browser's address bar doesn't change (except for the "#sources" fragment which btw. doesn't work also).

It would be really helpful to have working URLs for different areas of the application. Examples:
- https://domain/newest
- https://domain/unread
- https://domain/tag/some_tag

Could be "https://domain/#newest" also but I'd prefer using the History API for this because fragments cause various problems and are ugly.

**Comment by jtojnar** [comment]
Fixed in #869
