### ISSUE TITLE
Internal Server Error  Undefined index: SERVER_ADDR

### ISSUE THREAD

**Issue by bluenenschloss** [SSilence/selfoss#318]
Updating to latest 2.7-SNAPSHOP leads to the above mentioned Server Error when updating my feeds (http://rss.example.com/update.php). Clean install and importing feeds does not solve this problem.

Clean installing w/o importing feeds.opml and adding heise feed manually gives the same error.

/data/logs/default.log:
05-06-13 9:52:52 Debug start OPML import 
05-06-13 9:52:52 Debug   OPML import: successfully imported "9to5Mac"
05-06-13 9:52:52 Debug   OPML import: successfully imported "AFP548"
05-06-13 9:52:52 Debug   OPML import: successfully imported "Apple Presse"
05-06-13 9:52:52 Debug   OPML import: successfully imported "Apple Support"
05-06-13 9:52:52 Debug   OPML import: successfully imported "AppleInsider"
05-06-13 9:52:52 Debug   OPML import: successfully imported "GameStar"
05-06-13 9:52:52 Debug   OPML import: successfully imported "Golem"
05-06-13 9:52:52 Debug   OPML import: successfully imported "Heise"
05-06-13 9:52:52 Debug   OPML import: successfully imported "MacMark"
05-06-13 9:52:52 Debug   OPML import: successfully imported "MacUpdate"
05-06-13 9:52:52 Debug   OPML import: successfully imported "selfoss releases"
05-06-13 9:52:52 Debug   OPML import: successfully imported "topicdesk"
05-06-13 9:52:52 Debug   OPML import: successfully imported "TUAW"
05-06-13 9:52:52 Debug   OPML import: successfully imported "Tutsi"
05-06-13 9:52:52 Debug finished OPML import

**Comment by jtojnar** [comment]
This might be problem with IIS 6 – it provides `LOCAL_ADDR` instead of `SERVER_ADDR`. If this occurs on newer versions of IIS, please re-open.
