### ISSUE TITLE
Invalid routing pattern: GET /

### ISSUE THREAD

**Issue by thedragon013** [SSilence/selfoss#36]
Hello,

since the previous version did not work for me, I gave it a try with 2.0

This is what I get in my error.log:
/<path to>/selfoss/index.php:47 Base->route('GET /','controllers\Index->home')

Any ideas ?

Thanks.
Dragon013

**Comment by jtojnar** [comment]
The issue re-appeared for me after upgrade to PHP 7.1.11, opened an issue upstream https://github.com/bcosca/fatfree-core/issues/231

**Comment by jtojnar** [comment]
Apparently it is caused by cross-contamination by PCRE symbols from Apache.
