### ISSUE TITLE
a new API endpoint using GET, where RSS browser plugins direct the browser to add a feed to selfoss e.g. myserver.com/selfoss/subscribe/%s where "%s" contains the feed URL to be subscribed

### ISSUE THREAD

**Issue by chr15m** [SSilence/selfoss#363]

**Comment by aslmx** [comment]
I have come to the point where i really would love this feature too.

Has something changed in the last 3 years? Is it implemented? Is it planned to be implemented?

thx

**Comment by jtojnar** [comment]
I will try to implement this the way I mentioned on [#622](https://github.com/SSilence/selfoss/issues/662#issuecomment-105634002).

**Comment by chr15m** [comment]
@jtojnar \o/

**Comment by aslmx** [comment]
very good. can't wait for it...

**Comment by jtojnar** [comment]
Actually, after some experiments with the selfoss front end code, I have decided to code a new front end instead.

**Comment by jtojnar** [comment]
Also this is a duplicate of #254

**Comment by aslmx** [comment]
Any news on that topic. are you going to merge your changes @jtojnar

**Comment by jtojnar** [comment]
Closing as a duplicate.

As for my alternative client, I was actually working on it last month and it is approximately 80 % done but I will probably not have time to finish it, at least until summer.
