### ISSUE TITLE
Customize social links

### ISSUE THREAD

**Issue by Riduidel** [SSilence/selfoss#367]
I would like, as an example, to have the delicious social link replaced by the bookmarking site I use (called shaarli and hosted on the machine that also host selfoss).

For that, the list of links displayed in the `item.phtml` template file should be configurable (I don't know how, so I'm ready to use any implementation).

**Comment by jtojnar** [comment]
This has been possible for a long time. See e.g. https://github.com/fossar/selfoss/blob/master/NEWS.md#customization-changes
