### ISSUE TITLE
facebook/youtube rss feeds break sometimes

### ISSUE THREAD

**Issue by mcnesium** [SSilence/selfoss#436]
is it a facebook resp. youtube bug or one inside selfoss, that while most of the feeds work well, a few of them show the same error in the source view?

fb:

> error loading feed content: This XML document is invalid, likely due to invalid
> characters. XML error: XML_ERR_NAME_REQUIRED at line 9, column 30

yt:

> error loading feed content: This XML document is invalid, likely due to invalid 
> characters. XML error: Not well-formed (invalid token) at line 1, column 1

**Comment by jtojnar** [comment]
Closing as Facebook is broken and YouTube spout uses new source.
