### ISSUE TITLE
Still no filter?

### ISSUE THREAD

**Issue by Koopzington** [SSilence/selfoss#449]
I just wanted to know if you still don't have the intention to add a filter functionality like mentioned in #15 since i'd really appreciate such a thing.
Everything i'd personally need would be just a blacklist of words which shouldn't show up in the titles and therefore shouldn't be added to the unreaded items list...

But i guess you'd also need to add a whitelist and both configurable for global AND for each single source once you'd have started implementing filters...

**Comment by niol** [comment]
This has been implemented in 2.13.
