### ISSUE TITLE
RSS feed update notifications

### ISSUE THREAD

**Issue by PhrozenByte** [SSilence/selfoss#453]
Use web sockets or periodic AJAX requests to track RSS feed updates. This would be useful for features like marking entries as read by filters (see #279) or keeping the user up-to-date by showing the number of unread entries within the page title. Furthermore the user mustn't reload the page to check for new entries.

I strongly recommend delta updates.

**Comment by niol** [comment]
Wasn't this addressed by bbf47e786c63c8e505b40113e12f19f4c306c8a4?

**Comment by PhrozenByte** [comment]
Yes @niol
