### ISSUE TITLE
Filter items based on title with a blacklist

### ISSUE THREAD

**Issue by tuur29** [SSilence/selfoss#460]
I made a very easy blacklist feature in my forked repo.

It's useful for when you subscribe to a website that only offers a main feed. It filter's out the items of which the title contains certain set of words.

It's working fine but since I'm not so good at this it's quite slow and not integrated with the system at all (eg. I use a simple array as blacklist).

So perhaps you could consider integrating a similar feature (in which the words are stored in a database, the items aren't just skipped but hidden etc...).

**Comment by niol** [comment]
This has been implemented in 2.13.
