### ISSUE TITLE
Handle instapaper 301

### ISSUE THREAD

**Issue by koehn** [SSilence/selfoss#508]
Most of my Instapaper feeds started looking like this today:

<?xml version="1.0" standalone="yes"?> <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd"> 301 Moved Permanently
301 Moved Permanently

I'll try to figure out how to get SelfOSS to follow the redirect.

**Comment by jtojnar** [comment]
This will be fixed in #883.
