### ISSUE TITLE
Ability to make Selfoss the feed handler of your browser

### ISSUE THREAD

**Issue by GLLM** [SSilence/selfoss#511]
Could be a great addition, so that whenever I click on a feed's url, Firefox (or Chrome, or any capable browser) suggest I subscribt to this feed with Selfoss ... and once approved, directly sends me to the "Add source" page, with the URL already loaded !

"Competitor" https://github.com/readerself/readerself does this ;)

++

**Comment by iNaD** [comment]
Possible duplicate of #363 ? That seems to be how most browsers are handling this behaviour.

**Comment by jtojnar** [comment]
Indeed a duplicate, closing.
