### ISSUE TITLE
Too Many Mysql connections

### ISSUE THREAD

**Issue by tuur29** [SSilence/selfoss#514]
About every 2 months I get the following error message when trying to open selfoss:

"Internal Server Error
SQLSTATE[08004] [1040] Too many connections"

It only started after I installed selfoss so I'm guessing it's the cause.
It seems like some MySQL connections aren't closed. I took a quick peek but couldn't discover anything.
I must admit I never use the logout button, perhaps that is it? If it is, is there a way that the connections are closed after a period of inactivity, or you resume a session after you reopen the page?

**Comment by niol** [comment]
Maybe this has been fixed by https://github.com/SSilence/selfoss/commit/9ac07cbb7d7675aaf650d10b04f69463fa9863a2 in 2.13.

**Comment by jtojnar** [comment]
Closing. If it is still occurring please reopen.
