### ISSUE TITLE
Heise Spout Fixed But How?

### ISSUE THREAD

**Issue by ghost** [SSilence/selfoss#517]
Hi Tobias,
just wanted to leave a quick note because you closed #499 with a notice that the Heise Spout issue was fixed in the latest snapshot.

I had a look at your fix but I'm not sure it does the trick. The issue is with the following line which is not part of your new try construct:

$content = $item->getContent();

This should be inside the try as well because it's the getContent itself that traps when the link can't be fetched!

Just want to make sure it's definitely fixed :-)

Cheers,
Martin

**Comment by wAmpIre** [comment]
Seems that this is not 100% fixed...

From default.log:

02-03-15 12:23:43 Error file_get_contents(http://www.heise.de/newsticker/meldung/Mac-i-Heft-1-2015-jetzt-im-Handel-2534915.html/from/atom10?wt_mc=rss.ho.beitrag.atom): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
