### ISSUE TITLE
Error 500 on a Uberspace setup

### ISSUE THREAD

**Issue by ghost** [SSilence/selfoss#549]
Hello,
I tried to install selfoss on a [uberspace](https://uberspace.de/) - but it does not work.

```
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, hallo@uberspace.de and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log. 
```

I found out that **the .htaccess is the reason** - especially the following lines.

```
RewriteCond %{QUERY_STRING} ^(.*)$
RewriteRule !.(js|ico|gif|jpg|png|css|asc|txt|eot|woff|ttf|ttf|svg)$ index.php?%1
```

So there is something wrong with these lines, but I didn't know what ^^

Kind regards from Germany,
Julian

**Comment by cblte** [comment]
> Thanks @heubergen and @mritzmann - this solved the problem.
> 
> Just in addition for users that want to install selfoss under a subdomain (e.g. `/var/www/virtual/USERNAME/SUBDOMAIN.DOMAIN.TLD/`)
> Change the line `#RewriteBase /selfoss` to `RewriteBase /` :-)

Thank you very much!
