### ISSUE TITLE
Pressing 'v' opens in the background

### ISSUE THREAD

**Issue by floxyz** [SSilence/selfoss#55]
It would be really cool if Selfoss could be configured so that by pressing 'v' the tab opens in the background.
I am using Chrome and I am not 100% sure if this is a Selfoss thing or a Chrome issue. If I could get some hints where to look I could help!

**Comment by jtojnar** [comment]
I implemented a config option `open_in_background_tab=1` that allows this, though it does not work in Chromium: https://github.com/fossar/selfoss/pull/1354
