### ISSUE TITLE
Unvalid auth

### ISSUE THREAD

**Issue by gllmhyt** [SSilence/selfoss#581]
As said under commit 9d3d04bdf5f0dba157166d71f61d6dd9fa930333, there's some problems with this patch on my Nginx / PHP-FPM combo. Over HTTPS, it's working fine : I can login, and so on, with no problem. But over HTTP, having deleted the cookie related and purged the cache, I cannot login.

``` log
10-08-14 12:55:36 Debug session does not contain valid auth
```

**Comment by elamperti** [comment]
I'm still having problems with this, using a similar server setup. `$_SERVER['HTTPS']` is set but empty.
