### ISSUE TITLE
Multi-user support

### ISSUE THREAD

**Issue by auzias** [SSilence/selfoss#589]
I really like your workand would like to improve it [more](https://github.com/SSilence/selfoss/pull/585).
I got two ideas (which are two needs too), I would like to know which one the community would rather have:
1. Firefox App,
2. Multi-users support.

Btw, a twitter account for selfoss might be handful sometimes ;)
Have a nice day!

**Comment by jtojnar** [comment]
Closing in favour of #882 since this is quite broad.
