### ISSUE TITLE
Filter in the text?

### ISSUE THREAD

**Issue by debby1** [SSilence/selfoss#592]
Hi, I would like to know if on selfoss there is the feature filter in the text.

I need a Rss reader on server to receive many feeds from Facebook pages of companies and site webs, but only about some and specific things.

For example: I need to know news only about "recipes", so I would like to read only posts from Facebook pages with the word "recipe" in the text, and not all rest of posts..

Is this possibile? Thank you very much in advance

**Comment by niol** [comment]
This can be closed: fixed in 2.13.
