### ISSUE TITLE
worng dirrection scroll bar OSX

### ISSUE THREAD

**Issue by Ricain** [SSilence/selfoss#598]
Hi there :)

Scrolling in general is fine, but the tags section and sources section are scrolling the wrong side.

**Note:** scrolling compared to Windows on Macs is reversed.

I am using Selfoss 2.12 and I am using Firefox 33.1 on OSX 10.10.1.

Thank

**Comment by jtojnar** [comment]
Maybe this could be fixed with https://developers.google.com/web/updates/2017/03/custom-scrollbar

**Comment by jtojnar** [comment]
This was apparently fixed in [malihu custom scrollbar plugin](https://github.com/malihu/malihu-custom-scrollbar-plugin) 3.0.9.

**Comment by Ricain** [comment]
Thank :)
