### ISSUE TITLE
install error: public/all-v2.13-SNAPSHOT.js

### ISSUE THREAD

**Issue by planetoid** [SSilence/selfoss#601]
When I tried to install selfoss, I met the error message in the log file:

      Error file_put_contents(/path/to/selfoss/public/all-v2.13-SNAPSHOT.js): 

The file does not exists!

Thanks for your time.

**Comment by jtojnar** [comment]
@planetoid Could you close the issue then?

**Comment by niol** [comment]
This can be closed: not a bug.
