### ISSUE TITLE
Windows Phone 8.1: Can not mark/unmark item

### ISSUE THREAD

**Issue by RogerSik** [SSilence/selfoss#614]
Hello,

sometimes I get the error ,,Can not mark/unmark item" with the Internet Explorer on my Windows Phone 8.1.

It doens't matter if I have Wifi or Mobile Internet activated. Also I can't replicated the bug. These bug only occurs sometimes.

**Comment by RogerSik** [comment]
It look so
![screenshot](https://cloud.githubusercontent.com/assets/165814/5871176/7c0339b2-a2d9-11e4-9a5d-8a74e997ff7f.jpg)

**Comment by SSilence** [comment]
Hi Roger, ist dein Provider all-inkl.com?

**Comment by RogerSik** [comment]
Hello SSilence, 
no my provider is o2 Germany.

**Comment by niol** [comment]
I added some more debugging info in the message. Can you describe your server setup? Is selfoss runnning behind some kind of proxy on your hosting setup?

**Comment by RogerSik** [comment]
I have an Ubuntu 14.10 server with Apache 2.4.10.

Selfoss isn't running behind some kind of proxy. 

Maybe its a browser problem? I think that because with my Windows 8.1 PC (Firefox) and Windows 8.1 tablet (IE) I dont have this problem. This problem only appears on my Windows Phone.

**Comment by niol** [comment]
And when this happens, do you have a hit recorded in your apache2 logs?

**Comment by danieljkemp** [comment]
I have seen this issue occur (very rare) on android 5 with Firefox. A
refresh of the page fixed the issue so I didn't look deeper. Server is
running on centos 7/apache 2.4. If I see it happen again I will take a look
at my logs.

**Comment by RogerSik** [comment]
No I have no errors recorded in the apache2 logs. 

It is shown that my windows phone has accesed the selfoss site.

**Comment by niol** [comment]
I cannot reproduce with my setup (debian, apache, mod_php on ssl) and Windows Phone 8.1.

Do you get a line like the following in the apache logs at the exact time you are shown the error?

```
192.168.51.2 - - [24/Jan/2015:11:29:26 +0100] "POST /selfoss/mark/136278 HTTP/1.1" 200 731 "https://foo.net/selfoss/" "Mozilla/5.0 (Windows Phone 8.1; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; Lumia 625; Orange) like Gecko"
```

Were you able to apply #615 to get more info in the error message?

**Comment by RogerSik** [comment]
Hi niol,

yes i such a line too in the apache logs. 

I cloned your selfoss repository to look if i get more infos in the error message. But with your repository I cant access selfoss. 

I get the error 
---
Not Found

The requested URL /r/index.php was not found on this server.
---

**Comment by RogerSik** [comment]
Hi,

i change the files from your commit in my local selfoss installation but the error info message is the same
![wp_ss_20150124_0001](https://cloud.githubusercontent.com/assets/165814/5888945/6e17fe62-a411-11e4-85ec-aeac30fdbfee.jpg)

**Comment by niol** [comment]
You should delete de minified js for the new js code to be taken into account:
```
rm -f public/all-*.js
```

**Comment by RogerSik** [comment]
Hi,

I removed the files which you said and deleted the cache on my windows phone. But the same error appears on my windows phone without additional information's.
________________________________
Von: niol<mailto:notifications@github.com>
Gesendet: ý25.ý01.ý2015 11:16
An: SSilence/selfoss<mailto:selfoss@noreply.github.com>
Cc: Roger Sikorski<mailto:roger@sikorski.cc>
Betreff: Re: [selfoss] Windows Phone 8.1: Can not mark/unmark item (#614)


You should delete de minified js for the new js code to be taken into account:

rm -f public/all-*.js

**Comment by niol** [comment]
Can you provide the line in your apache logs at the exact time you get the error?

**Comment by RogerSik** [comment]
Hello niol,

sorry for the late reply.

I looked now and I saw that when the error occur that nothing is logged. Event at access or error apache logs.

Example I looked thourgh 6 arcticles. The 6. arcticles got the error. In the log only appears the first 5 accesses.

**Comment by niol** [comment]
Is there a proxy between your client and selfoss?

**Comment by RogerSik** [comment]
When I'm at home yes when I'm not at home then not. 



But the problem also occurs when I'm not using the proxy.

**Comment by niol** [comment]
I have no clue about what is wrong. But if apache does not log some kind of error, there is a good chance this is not a bug in selfoss.

**Comment by RogerSik** [comment]
This issue doens't appear more. I'm not sure if 2.14 or the activation of mod_headers in apache solved this. 

Greetings
Roger
