### ISSUE TITLE
do not format long articles in columns

### ISSUE THREAD

**Issue by niol** [SSilence/selfoss#629]
42e0ed4bfd3a95353fb3f458363eff0acc2ae691 reverts a7f24906f9df3329a8d6fdd0088049e766b0f068 . This was a valuable feature to me. How to fix?

**Comment by josefnpat** [comment]
I just installed selfoss and am looking for a way to do this as well;

Can I apply that patch and get the results I am looking for, or is this issue too old?

![http://i.imgur.com/T61pPcl.png](http://i.imgur.com/T61pPcl.png)

**Comment by niol** [comment]
This should still work.

**Comment by martinsauter** [comment]
Another option that might work for you is to modify the default css by putting "user.css" in the main selfoss directory. I for example prefer 2 instead of 3 colums and thus have the following code in "user.css":

```
    .entry-content {
        -moz-column-count: 2;
    }
```
That's all I have in that file so perhaps it'll work for you to set count to 1 here.

**Comment by niol** [comment]
That did it, therefore closing.

**Comment by jtojnar** [comment]
I am not sure why was it reverted, scrolling up and down makes no sense to me.
