### ISSUE TITLE
"This XML document is invalid" message for valid RSS feed

### ISSUE THREAD

**Issue by flurischt** [SSilence/selfoss#637]
Hi 
using selfoss 2.12 the feed below yields the following error message:
"2015-04-10 14:37:32error loading feed content: This XML document is invalid, likely due to invalid characters. XML error: SYSTEM or PUBLIC, the URI is missing at line 1, column 48
speichern • abbrechen ".

Feed: http://misto.ch/feed/

According to http://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fmisto.ch%2Ffeed%2F this is a valid RSS feed.

**Comment by flurischt** [comment]
I get the same message for the also valid feed: http://blog.bbv.ch/feed/

**Comment by niol** [comment]
Those two Wordpress websites are returning an HTTP error code ```406 Not acceptable``` if using the user agent ```SimplePie```. That is to say that those RSS feeds are configured to refuse to answer to the library that selfoss is using to parse RSS feeds.

However, selfoss wrongly reports about an XML issue. The following simple patch may fix this. Also, maybe https://github.com/simplepie/simplepie/issues/393 should be reopened. I'll run with this for a while and see how it goes.

```diff
diff --git a/libs/SimplePie.php b/libs/SimplePie.php
index 7349448..1c093cc 100644
--- a/libs/SimplePie.php
+++ b/libs/SimplePie.php
@@ -6844,6 +6844,7 @@ class SimplePie_File
                                curl_setopt($fp, CURLOPT_URL, $url);
                                curl_setopt($fp, CURLOPT_HEADER, 1);
                                curl_setopt($fp, CURLOPT_RETURNTRANSFER, 1);
+                               curl_setopt($fp, CURLOPT_FAILONERROR, 1);
                                curl_setopt($fp, CURLOPT_TIMEOUT, $timeout);
                                curl_setopt($fp, CURLOPT_CONNECTTIMEOUT, $timeout);
                                curl_setopt($fp, CURLOPT_REFERER, $url);
 ```

**Comment by niol** [comment]
This can be closed: fixed in master.
