### ISSUE TITLE
Random internal server errors after adding some feeds

### ISSUE THREAD

**Issue by Poorchop** [SSilence/selfoss#643]
I tried really hard to get selfoss working on my server and after a lot of messing around, things finally seemed to be up and running. However, it seems that after adding certain feeds, things go haywire and selfoss breaks down completely. I added a GitHub feed and some comic feeds, but after adding an NPR feed, I kept getting the following error when trying to manually refresh (IP and server information redacted):

`[error] 2155#0: *57 FastCGI sent in stderr: "PHP message: Fatal error: Call to undefined function imagecreatefromstring()" while reading response header from upstream, client: [IP], server: [server], request: "GET /update HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "[server]"`

Now when I try to delete the NPR feed or any feed for that matter, I get a message in my web browser that says "Error deleting source: Internal Server Error" and the following error in my logs:

`[error] 2155#0: *57 FastCGI sent in stderr: "PHP message: Fatal error: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead" while reading response header from upstream, client: [IP], server: [server], request: "POST /source/delete/3 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "[server]"`

I'm guessing the second error message is kind of irrelevant to the issue at hand.

I've also noticed that even when selfoss works initially before everything breaks down, it doesn't display any favicons or thumbnails. Data/favicons and data/thumbnails are always empty after adding feeds, so clearly some things are amiss. I really wish I knew what I was going wrong because I just can't seem to get selfoss completely working.

I'm using nginx and sqlite on Arch.

**Comment by niol** [comment]
For the ```imagecreatefromstring``` , can you help me reproduce by providing spout info?

For the cannot edit source problem, this is the same as #565 .

**Comment by Poorchop** [comment]
I am using the default "RSS Feeds" spout. I can successfully add my personal GitHub feed and [this feed](https://feeds.feedburner.com/PoorlyDrawnLines). Once I added the [NPR News feed](http://www.npr.org/rss/rss.php?id=1001) and I tried to refresh, that's when I started getting error messages and had to reinstall from scratch.

The first time this happened, I tried with a few other feeds, so if you can't replicate by adding those feeds, I can give you some others to try. Also in case it helps at all, I am using the [default nginx config](https://github.com/SSilence/selfoss/wiki/nginx-configuration) except I have excluded the initial upstream block, and I changed the the fastcgi_pass line to `fastcgi_pass 127.0.0.1:9000;`. I kept getting 502 Bad Gateway when listening on /var/run/php5-fpm.sock, and it only worked when I listened on 127.0.0.1:9000.

**Comment by niol** [comment]
Do you have the ```php5-gd``` extension installed and loaded?

**Comment by Poorchop** [comment]
@niol that solved the issue. I didn't have the extension enabled in my php.ini. I'm guessing that the GitHub and initial comic feeds I loaded don't have any favicons or images that selfoss was trying to load, but when it encountered a feed where the opposite was true, it just caused a bunch of issues.

The install process was much more detailed and complicated in my web server than the documentation lets on. I did a proper writeup on the forums, but I think it would a good idea if the official docs went more in depth. I didn't even realize php-gd was necessary for images until I was going through the wallabag installation process and noticed the requirement during the plugin check step.

Thanks for your help all the same.

**Comment by niol** [comment]
It would be great if you could propose enhancements to the docs as pull requests.

**Comment by Poorchop** [comment]
Sure, just need a little time. For now, I have a detailed guide on the help forums that should suffice for any other users who experience the same problems. I'm guessing that there isn't a repo for the website and that SSilence manages it himself, but I will propose changes to the readme in the main repo.

**Comment by niol** [comment]
The website is in the ```_docs``` directory of the repo.

**Comment by Poorchop** [comment]
@niol I have installed selfoss in multiple distros now in multiple different environments (SELinux enabled, etc.). The install process has been different every single time. Rather than cluttering the home page with very verbose install instructions that aren't applicable to every distro, I think a wiki entry for specific step-by-step instructions in Fedora or CentOS would be nicer, and the main website can just include a link to the wiki entry right above the current install instructions. What do you think?

**Comment by niol** [comment]
Go on, and if something needs to be retrieved back to the homepage, we'll do it then.
