### ISSUE TITLE
Tag filtering works with partial matches

### ISSUE THREAD

**Issue by GrumpyChunks** [SSilence/selfoss#65]
Say I have two tags, `football` and `foo`. Filtering by the tag `foo` matches both of the tags.

I've got round this by making the following mod to daos\mysql\Items.php (line 172)

```
        // tag filter
        if(isset($options['tag']) && strlen($options['tag'])>0) {
            $params[':tag'] = array("%,".$options['tag'].",%", \PDO::PARAM_STR);
            $where .= " AND (','|| sources.tags || ',' LIKE :tag) ";
```

**Comment by jtojnar** [comment]
PR link for reference: https://github.com/SSilence/selfoss/pull/68
