### ISSUE TITLE
Fehler nach update von 2.12 auf 2.13

### ISSUE THREAD

**Issue by guzzisti** [SSilence/selfoss#651]
Hi,

Version 2.12 lief bei mir bisher problemlos, gestern hab ich Version 2.13 eingespielt laut Updateanleitung, seitdem läuft selfoss nicht mehr.

Ich nutze die sqlite-DB, welche bei mir Version 6 hat. Das ganze läuft auf einem NAS mit PHP 5.5.
Bei Aufruf der Seite steht im Log mit DEBUG Einstellungen folgendes:
05-11-15 3:21:18 Debug set cookie on ... expiring in 2592000 seconds
05-11-15 3:21:18 Debug logged in using valid session
05-11-15 3:21:18 Debug Establish database connection
05-11-15 3:21:20 Error Undefined index: title

Auf der Seite steht dann nur "Ein Fehler ist aufgetreten". Sobald ich alle Sourcen aus der DB lösche, geht die Seite zumindest wieder auf. Beim Bearbeiten von Sourcen kommt dann aber der Exception-Banner mit "Internal Server Error".

Auch wenn ich von selfoss eine neue leere Db anlegen lasse, kann ich keine Sourcen hinzufügen. Im Log steht dann:
05-11-15 3:35:14 Debug set cookie on ... expiring in 2592000 seconds
05-11-15 3:35:14 Debug logged in using valid session
05-11-15 3:35:14 Debug Establish database connection
05-11-15 3:35:14 Error PDO: no such column: sourceicons.source

Hat jemand ne Idee was hier schief ist?

Gruß

**Comment by guzzisti** [comment]
Nachtrag:
Rollback auf Version 2.12 und alles läuft wieder mit der vorhandenen DB.

Gruß

**Comment by niol** [comment]
If you speak English, maybe I can help you. I can understand that you have problems displaying the source list and that you are using sqlite. This works fine on my setup. Which sqlite version are you using?

**Comment by guzzisti** [comment]
Hi,

i try this in english :)

I´m using selfoss 2.12 for some time now, running it on an qnap nas with Apache2, PHP 5.5.21 and SQLite 3.4.1. Version 2.12 works really well.

I tried to update to version 2.13 using the update procedure explained in the readme. After that, selfoss wont work anymore with the existing database. It shows a blank page with a single line of text meaning "an error occured".
The log says:
05-11-15 3:21:18 Debug set cookie on ... expiring in 2592000 seconds
05-11-15 3:21:18 Debug logged in using valid session
05-11-15 3:21:18 Debug Establish database connection
05-11-15 3:21:20 Error Undefined index: title

I moved my existing database to another location and let selfoss create a new one. The main page now shows as expected, but clicking the "manage sources" button only brings up the exception banner saying "Internal Server Error". 
The following lines can be found in the log after this procedure:
05-11-15 3:35:14 Debug set cookie on ... expiring in 2592000 seconds
05-11-15 3:35:14 Debug logged in using valid session
05-11-15 3:35:14 Debug Establish database connection
05-11-15 3:35:14 Error PDO: no such column: sourceicons.source

After all i reverted back to 2.12 and everything is running fine again, even with my existing database.

Kind regards
guzzisti

**Comment by niol** [comment]
For the first problem, I do not know. A line number where the error occurs may help.
For the second problem, I suspect your old (2007) sqlite version is responsible because it has been running fine for me. Is upgrading sqlite3 an option on your device?

**Comment by guzzisti** [comment]
You seem to be right, i moved the installation to my hosted webspace and everything seems to work fine.
I will do some further research when i have some spare time for that.

kind regards

**Comment by jtojnar** [comment]
Closing due to clean-up. Please re-open if still relevant.

**Comment by guzzisti** [comment]
Hi again,

it has been quite a long time, but i finally figured out whats going wrong.
Everything is fine with SQLite 3.11.0 on my webhost, but with SQLite 3.4.1 on my nas the error still occurs.

The issues is caused by the SELECT-Statement in function getWithIcon() in daos/mysql/Sources.php/. I will try to find out if there is a solution that works with old SQLite-versions as well.

kind regards

**Comment by guzzisti** [comment]
Hi again,

i managed to fix this issue by adding a custom method to daos/sqlit/Source.php:
  ```
  /**
     * returns all sources including last icon
     *
     * @return mixed all sources
     */
    public function getWithIcon() {
        $ret = \F3::get('db')->exec('SELECT DISTINCT
                sources.id, sources.title, sources.tags, sources.spout,
                sources.params, sources.filter, sources.error, sources.lastentry,
                items.icon AS icon
            FROM ' . \F3::get('db_prefix') . 'sources AS sources
            LEFT OUTER JOIN ' .\F3::get('db_prefix'). 'items AS items
            ON sources.id = items.source
            ORDER BY ' . $this->stmt->nullFirst('sources.error', 'DESC') . ', lower(sources.title)');

        return $ret;
    }
```
As SQLite 3.4 is roughly 10 years old i´m not sure if there is any need to support this old stuff. I´d rather urge my nas manufactorer to update their packages.
kind regards

**Comment by jtojnar** [comment]
It would be nice if the query were rewritten to something that does not trip older versions of SQLite, maybe replace the inner select with join?

```sql
SELECT
	sources.id, sources.title, sources.tags, sources.spout,
	sources.params, sources.filter, sources.error, sources.lastentry,
	sourceicons.icon AS icon
FROM sources AS sources
LEFT OUTER JOIN
    (SELECT items.source, icon
     FROM items INNER JOIN
	    (SELECT source, MAX(id) as maxid
		    FROM items
		    WHERE icon IS NOT NULL AND icon != ''
		    GROUP BY source) AS icons
     ON items.id=icons.maxid
    ) AS sourceicons
  ON sources.id=sourceicons.source
ORDER BY sources.error DESC, lower(sources.title);
```

The execution plan seems to be the same, though.

**Comment by guzzisti** [comment]
This was what i have done to fix my issue, replace subselect with join. 

As my sqlite database grows performance slowly drops over time. I´m currently reviewing the database structure and statements. Maybe i can contribute a pull request later on for better performance when using sqlite. 

I´ll close this issue for now as noone except of me run into this problem.

kind regards
