### ISSUE TITLE
Error PDOStatement: ERROR:  column "filter" of relation "sources" already exists

### ISSUE THREAD

**Issue by jeffcasavant** [SSilence/selfoss#656]
Using PostgreSQL as a backend, Selfoss 2.13 runs once but always crashes after that.  
Workaround:
* Commenting out lines 178-183 in daos/pgsql/Database.php
* Manually setting the version row to 6

**Comment by niol** [comment]
Does the ```filter``` column get created in the ```sources``` table? Do you have some error message in your pgsql logs or in selfoss logs?
Where does it crash?

**Comment by jeffcasavant** [comment]
The filter column gets created and is there.  The selfoss logs show the error message I've set as the title of this issue.  

By "crash" I mean that selfoss no longer runs in the browser (I get the generic "An error occurred" message at that point).

**Comment by jtojnar** [comment]
Someone forgot to upgrade database version in pgsql source: compare [pgsql](https://github.com/SSilence/selfoss/blob/2.13/daos/pgsql/Database.php#L117) and [mysql](https://github.com/SSilence/selfoss/blob/2.13/daos/mysql/Database.php#L106). Update [hook](https://github.com/SSilence/selfoss/blob/2.13/daos/pgsql/Database.php#L180) is then called on a version of database that is already up to date.

**Comment by jeffcasavant** [comment]
Does that do it?

**Comment by niol** [comment]
This is called only if table version does not exist. So your fix does not feel right. The problem is with the ```else```. I'll try to come up with a fix.

**Comment by jeffcasavant** [comment]
In my case, the table version did not exist; it was created on the first run and then subsequently it would hit that else clause.  I suspect this fix is still necessary since the MySQL database.php has version 6.  There's definitely more to do I think (for the case when it's an upgrade).

**Comment by jeffcasavant** [comment]
This fix should be everything we need since version 5 would not have the column, but would have the version table; the only case we need to worry about is when we're creating the database schema for the first time, and it's set to version 5 mistakenly.
