### ISSUE TITLE
Automatically fetch feed title

### ISSUE THREAD

**Issue by Poorchop** [SSilence/selfoss#662]
A lot of RSS readers that I've used will automatically pull in the title once the URL is pasted. I think this would be a great addition to selfoss.

**Comment by dubbl** [comment]
Good idea, I'll look into that tomorrow.

**Comment by dubbl** [comment]
Okay, this is actually not that trivial.
As selfoss support a range of input sources, not only simple RSS, every spout would have to have a function like autofill() that gets the required information, either the RSS URL to grab the title from, or, for example if its a Tumblr sprout the username (the title then could always be "[username] tumblr").

Another thing that is different from spout to spout is when the autofill function should be called. For RSS its when the RSS URL field is changed, for the Tumblr spout it's when the username field is changed etc., but that could be solved via a flag for the field. Then you would have to check whether the user already wrote something in the title field and then make an ajax request to the autofill function.

It's not impossible, but before starting I would like to have some feedback from other contributors and @SSilence himself on whether to do this and other maybe nicer ways to do it.

**Comment by jtojnar** [comment]
The **add source** form itself is overly complicated. The title can be pre-filled most of the time so maybe two step form would be a nicer solution.

Every spout would have `matches()` method which would return true if the source can be parsed by the spout.

![selfoss-rss](https://cloud.githubusercontent.com/assets/705123/7820269/a3b8ea00-03e7-11e5-8698-32851610a3d7.png)

The selfoss would call `matches()` method and change the form to the correct spout (based on mime type, content, or URL).

![selfoss-youtube](https://cloud.githubusercontent.com/assets/705123/7820270/a3bb867a-03e7-11e5-9377-72c828af13ec.png)

To bypass this, user could click advanced button.

![selfoss-advanced](https://cloud.githubusercontent.com/assets/705123/7820268/a3b5629a-03e7-11e5-9cf4-4200b90cb201.png)

**Comment by Poorchop** [comment]
@jtojnar I like that idea but that sounds like a tremendous amount of work for the sake of implementing my request. There's also the question of how the feed title would be pulled in. I'm guessing the text between `<title></title>` could just be parsed if it's available. That's also trusting feed to not have anything crazy going on like weird characters or an obscenely long title (unless a method is implemented for automatic truncation). Additionally, if the entire xml document or whatever has to be loaded in order to search for the title node, that could slow selfoss down a bit. The other option would just be to load the document in chunks instead of opening the entire file all at once, but that could introduce a whole set of other issues. Hopefully this makes sense.

@dubbl assuming that the HTML title tags are used, wouldn't this standardize pulling in titles regardless of the spout that is being used?

**Comment by niol** [comment]
I'm currently testing something I implemented. Comments welcome.

**Comment by dubbl** [comment]
That looks good, however I would still prefer an instant ajax request for a single parse of the resource once the user has unfocused for example the URL field. That way we could make sure that the resource exists, can be parsed and autofill the title or inform the user that something is wrong with the resource.

**Comment by Poorchop** [comment]
Thank you to everyone who worked on this.
