### ISSUE TITLE
Scroll to the title when opening an entry

### ISSUE THREAD

**Issue by fmunch** [SSilence/selfoss#665]
Since 0b44581cc362d2d6379ec2f312d9637f5b59c7c3, when opening an entry on a desktop browser, it automatically scrolls to the entry title.
This behavior is really annoying when trying to read every new entries alphabetically, starting from the bottom.
Would it at least be possible to disable this behavior in config.ini?

**Comment by niol** [comment]
Maybe it should be automatically disabled if ```unread_order=desc```.

**Comment by niol** [comment]
Now there is ```scroll_to_article_header``` that you can set to ```0```.
