### ISSUE TITLE
Spaces in tags results in "subtags" with regard to unread count

### ISSUE THREAD

**Issue by Poorchop** [SSilence/selfoss#667]
If I create a tag called "news" and another tag called "tech news", then the unread count for the "news" tag will reflect the combined total from feeds tagged "news" and "tech news". For example:

* create an RSS feed (Feed A) with the tag of "news"
* create another RSS feed (Feed B) with the tag of "tech news"
* Feed B has 5 unread stories
* Feed A has 1 unread story

| Feed name | Unread count |
|-----------|--------------|
| Feed A    |       6      |
| Feed B    |       5      |

I'm not 100% sure if this is what's happening since I have too many stories to manually count now, but either way, the unread count for Feed A is incorrect. Obviously Feed A should have an unread count of 1.

**Comment by jtojnar** [comment]
This should fix it. I tested it on sqlite, hopefully someone will check mysql.

**Comment by Poorchop** [comment]
Thanks @jtojnar.
