### ISSUE TITLE
Block Wordpress emojis

### ISSUE THREAD

**Issue by mcnesium** [SSilence/selfoss#671]
Wordpress ships those stupid smilie faces with v4.2 and they are rendered pretty large in selfoss. It gets annoying, when you have bloggers who really like emojis:
![pie3ohn2](https://cloud.githubusercontent.com/assets/476060/7983208/0c284acc-0abe-11e5-99f4-30b4ff06633e.png)
Besides selfoss I haven't found anything else where there are actually images loaded with an img-tag: 

```
﻿﻿<img src="http://s.w.org/images/core/emoji/72x72/1f600.png" ref="http://s.w.org/images/core/emoji/72x72/1f600.png" alt="😀">
```

but neither I found any code about that in the repo. So regard this more as an appeal for help than a bug report or a feature request. How can I get rid of that stupid junk, that besides being annoying also unaskedly calls home from inside my local news reader?

**Comment by niol** [comment]
If your problem is with the emoji being wrongly sized, are there width and height attributes in the item source?

If your problem is privacy related, use ```anonymizer``` in ```config.ini```.

If your problem is with selfoss autoloading external images or external images filtering, this is a feature request.

**Comment by mcnesium** [comment]
wrongly sized: no, that would be easy to add some css to style.css

privacy: also no, I do use `anonymizer`, but that does not play with integrated images, but see #612 for that matter ;)

external images: not exactly, but close. Trying to find out whether the images are actually loaded externally

Problem rephrased: Where does the HTML for those images come from? In the [RSS-feed](http://www.markushenke.de/feed/) there is just that unicode character.

**Comment by niol** [comment]
Selfoss only filters HTML from the feed content. In the feed you supply, I can see the ```<img>``` tags for the emojis in the ```<content:encoded>``` element of the RSS items. So there it is. Selfoss does not add anything.

**Comment by mcnesium** [comment]
I see, okay. Wow, even worse, they are not even loaded using https. So this actually *is* in the feed and therefore the blogs maintainer is in charge. 

One way to get rid of them would be to add some css like

     img[src^=http://s.w.org/images/core/emoji] { display: none; }

but thats pretty special and would be more like a plugin (or a spam filter, for that matter). Any other ideas?

**Comment by niol** [comment]
Selfoss could also filter out those images. Also, images could be loaded only on demand by clicking on it (new selfoss option). Just some random ideas.

**Comment by jtojnar** [comment]
Closing since the images are now inlined. Hiding them can be done using `user.css`.
