### ISSUE TITLE
Generic Share buttons via config.ini

### ISSUE THREAD

**Issue by aslmx** [SSilence/selfoss#680]
This is a feature request - but also a thread discussing how to implement it in case i will manage to do it eventually myself in case no one else does ;-)

I just implemented myself a "Download PDF" button which simply sends the current item source to a webservice that converts the page into a nice pdf (for your reference: www.printfriendly.com, but there are plenty of others). Works quite well, but the effort is quite high for the average user.

I thought about adding the addition to my branch and pull request it, but i first thought i'd discuss whehter it is possible to find a generic solution which lets the user configure ANY share button via the config.ini.

I had to change selfoss at 4 places to make the extra button. I'm not that experienced with state of the art javascript/web development and did not yet fully understand the way how selfoss sourcecode actually works.

How would you best implement this generic share buttons? I thought the feature should look like this in the config.ini
example: share to pdf

sharebutton_name1=Share to PDF
sharebutton_key1=p
sharebutton_image1=images/buttonpdf.png
sharebutton_url1=http://thefanciestpdfserviceintheworld.com/?url=

so whatever piece of code could simpyl try to iterate of the sharebutton_***x keys in the config.ini and "render" the buttons accordingly.

My problems are: how to start the iteration?
e.g. the Image/icon for the buttons are declared in a .css file which is not processed by PHP
Or the javacscript which actually puts the functionality to the buttons. How could i iterate the configuration here?

I would really appreciate if someone with more experience would simply implement this, but i'm open for sugesstions and then try to do it myself... 

I think there are numerous use cases. e.g. there is also a webservice that converts a webpage to epub and then sends it do your Amazon Kindle (i never tried it because i'm converting them to PDF and then send them to my kindle myself ;-) and maybe other things like rarely used social networks that let users share URLs... 

thanks for your help!
br
aslmx

**Comment by bbeardsley** [comment]
In master (2.14 snapshot) I've started refactoring share functionality to make it easier to do what you're wanting to do.  Started with the javascript and I still need to do more on the php side...

**Comment by aslmx** [comment]
Thanks for that.

I tried to understand your changes and so far i understand that this would only miss the dynamic css generation and the config parsing, right?

I'm new to github and dont know how to find out whether the branch(?)commit(?) you linked is actually merged into master, is it? Then i would fork it and try to work on the parts that are missing but it would take a while....

**Comment by bendem** [comment]
It is in master, you can see it because the branch name is under the commit description (the `#650` next to the branch name is the PR the commit comes from).

![](http://i.imgur.com/Tp9lHxD.png)

**Comment by bbeardsley** [comment]
on my test site I have removed the icons from the CSS and instead generate them as img tags in the php. Seems to be working well - haven't got a pull request ready yet though.
