### ISSUE TITLE
Ads are included inside some feeds

### ISSUE THREAD

**Issue by aminecmi** [SSilence/selfoss#683]
Here is a capture.

Some articles contains ads. [Imgur](http://i.imgur.com/gsyTyui.png)
Is there a way to get rid of them ?

**Comment by niol** [comment]
There is no obvious way to distinguish ads from images in feed items. Maybe images from another domain could be loaded only on demand? This would not handle all cases though.

**Comment by alfredbuehler** [comment]
Yes, it might be difficult.
But filtering them on the client side with _Adblock Plus_ works for me.

**Comment by aminecmi** [comment]
@niol if all is left is the images, doesn't that mean that the element containing them was cleaned/stripped/removed ?

@alfredbuehler the problem occurs on the mobile app, so no adblock plus.

**Comment by niol** [comment]
Ads in feed items are usually images. selfoss removes iframes.

**Comment by aminecmi** [comment]
Oh, I didn't think of that. So the images are in the feed as images, and not iframe (or something else).
I see now :)

**Comment by jtojnar** [comment]
I think this is another use case for #858
