### ISSUE TITLE
Mark as read button or option to disable scroll on item open

### ISSUE THREAD

**Issue by nijave** [SSilence/selfoss#685]
I used to double-click items to mark them as read if I wasn't interested in reading them. The latest update automatically adjusts the window scroll when you click an item so you can't just double-click it to mark as read.

I'm suggesting:
a. Add an option to disable scrolling on click
-or-
b. Add an option to enable a mark as read button somewhere to prevent having to open an article to mark it as read

*\* Offending code is selfoss-events-entries.js line 100

**Comment by niol** [comment]
There is now ```scroll_to_article_header```.

**Comment by jtojnar** [comment]
Indeed, introduced in f9150a591daff6e28936fa11878e43ddf27faa95. It seems to be broken by fce1db92240a40648485f272532e77129f6645b6, though.

**Comment by jtojnar** [comment]
Fixed in #889
