### ISSUE TITLE
db_prefix not working on MySQL

### ISSUE THREAD

**Issue by tortlepp** [SSilence/selfoss#686]
I set up selfoss with MySQL and used `db_prefix=selfoss_` . The setup of the database was done correctly, in phpMyAdmin I could see selfoss_items and the other tables. But after login I got a blank page with the message "Ein Fehler ist aufgetreten".

In the log I found these messages:
```
07-10-15 23:44:21 Debug logged in using valid session
07-10-15 23:44:21 Debug Establish database connection
07-10-15 23:44:21 Error PDOStatement: Table 'DATABASE.items' doesn't exist
```

Without the prefix (`db_prefix=`) the problem did not occur.

**Comment by niol** [comment]
This is fixed, can be closed.

**Comment by tortlepp** [comment]
Thanks a lot! After the update to 2.14 db_prefix works fine.
