### ISSUE TITLE
Facebook Page RSS Feed deprecated

### ISSUE THREAD

**Issue by mcnesium** [SSilence/selfoss#687]
https://developers.facebook.com/docs/apps/changelog#v2_3

<q>Page RSS Feed endpoint - at https://www.facebook.com/feeds/page.php is now deprecated and will stop returning data from June 23, 2015. Developers should call the Graph API's /v2.3/{page_id}/feed endpoint instead. This returns JSON rather than RSS/XML.</q>
This means that we are no longer able to have Facebook in selfoss, right?

**Comment by auzias** [comment]
Yes, it is. I had this problem, I don't have fb but follow(ed) public fan page. Now We just can't, unless our RSS-feed parse JSON too.

Maybe a new feature to implement ?

**Comment by mcnesium** [comment]
Maybe its time to go to the barricades for us to make everyone go back to their own websites
