### ISSUE TITLE
update.php is missing

### ISSUE THREAD

**Issue by hfroese** [SSilence/selfoss#689]
after last git update update.php is missing.

**Comment by bbeardsley** [comment]
It was renamed to cliupdate.php

**Comment by hfroese** [comment]
Nice to know ;-)

**Comment by drasill** [comment]
Wow, this should indeed be either documented, or aliased !

I was starting to believe the bloggers were all on holidays ;-)

**Comment by niol** [comment]
Documentation was updated. Where did I miss something?

**Comment by drasill** [comment]
You didn't.
But the lack of update was not obvious before 2-3 days for me, and the cron was silenced (`>dev/null 2>&1`).

I don't know how you could warn the user when deploying/git-pulling/updating ? or maybe create an `update.php` which calls `cliupdate.php` for legacy crons.

Anyway, thank you for this software I use daily !

I suppose you can close this issue.

**Comment by niol** [comment]
I can't close the issue but you can.

You should not silence the output of the cron call. It is silent unless there is an error. Then you can be notified of problems.

Thanks for following up.

**Comment by gerundt** [comment]
Maybe we should add a line like "*Change update.php to cliupdate.php in cron jobs scripts*" at the **Update** section from the readme?

**Comment by nicos68** [comment]
Also, it would be nice to update [this page] (https://github.com/SSilence/selfoss/wiki/Installing-on-Raspberry-Pi-with-lighttpd) of the wiki.
Apart from that, thanks for the software, I just deployed it on my raspberry pi, works like a charm :)

**Comment by jtojnar** [comment]
Closing since most people probably managed to upgrade already.
