### ISSUE TITLE
Selfoss does not parse valid RSS 2.0 feed

### ISSUE THREAD

**Issue by lordastley** [SSilence/selfoss#692]
Selfoss v2.14 does not parse any items out of the following RSS feed (using source type "RSS Feed").
https://gist.github.com/lordastley/29c5f344d4f2dfbea993

http://feedvalidator.org/, TTRSS and Firefox's built in feed reader all parse this feed.

Selfoss _does_ parse items out of this incredibly similar feed from Yahoo Pipes.
https://gist.github.com/lordastley/a59ac1193ca75de5862c

**Comment by jtojnar** [comment]
It seems to work just fine for me on 2.14. Do you get any specific error message? Try enabling debug mode in common.php.

**Comment by lordastley** [comment]
Alright, this works on a fresh install. However, then adding the 2nd feed from Yahoo Pipes results in _that_ feed not returning any items. I suspect the identical GUIDs in the feeds are resulting in deduplication somewhere, however this solves my current issue. I'll just remove one of the two feeds from my install.
