### ISSUE TITLE
"error loading feed content: cURL error 60: SSL certificate problem: unable to get local issuer certificate"

### ISSUE THREAD

**Issue by AmrEldib** [SSilence/selfoss#693]
Some feeds can't be loaded because of this error message: 
error loading feed content: cURL error 60: SSL certificate problem: unable to get local issuer certificate
Examples: [Wallabag blog](https://www.wallabag.org/feeds/all.atom.xml), [Jake Archibald blog](http://jakearchibald.com/posts.rss)
Both links aren't valid in the [Feed Validator](http://validator.w3.org/feed/check.cgi) for similar reason: Server returned [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
Is this a problem with the feeds or with Selfoss (or underlying component)?

**Comment by martinsauter** [comment]
Sounds familiar. Have a look at https://github.com/SSilence/selfoss/pull/505#issuecomment-39122258

**Comment by AmrEldib** [comment]
Excellent, that resolved the problem. Thank you, please close the ticket

**Comment by niol** [comment]
You can close it yourself if this is resolved.

**Comment by AmrEldib** [comment]
wow, I totally missed that I can do that. Thanks!
