### ISSUE TITLE
"Error error loading feed content for $RSSFEED: fsockopen error:

### ISSUE THREAD

**Issue by spence91** [SSilence/selfoss#694]
I'm getting this error when trying to update a feed - not all feeds, just a few. That's all the error messaging I get, even when I've turned the logger_level to "DEBUG".

Has anyone else experienced this? I'm using php 5.6.10 - that I compiled myself running on Rpi - using a different RSS reader with the exact same URL comes back with the feed.

**Comment by niol** [comment]
You should use php-curl if you can.

If you can't, please apply the following patch and tell me the error number.

```diff
--- a/libs/SimplePie.php
+++ b/libs/SimplePie.php
@@ -6905,7 +6905,7 @@ class SimplePie_File
                                $fp = @fsockopen($socket_host, $url_parts['port'], $errno, $errstr, $timeout);
                                if (!$fp)
                                {
-                                       $this->error = 'fsockopen error: ' . $errstr;
+                                       $this->error = 'fsockopen error: ' . $errstr . '('.$errno.')';
                                        $this->success = false;
                                }
                                else
```

If the error number is ```0```, please remove the ```@``` before ```fsockopen```. You should get more debugging output.

**Comment by spence91** [comment]
Thanks for the fast reply. I *should* be able to re-compile with php-curl - although that takes the better part of a day on the Rpi!

In the meantime; I followed your instructions - I changed that line, got `0` as the error number, removed the `@` before `fsockopen`... but I don't get anymore debug info.

Feed URL is http://www.queryfeed.net/twitter?q=from%3Avivaldibrowser&geocode=

**Comment by niol** [comment]
Can you configure php to add more error logging: in ```php.ini```, ```error_reporting = E_ALL``` ? Does that give more info?

**Comment by spence91** [comment]
I already had that level of error reporting set, so there's no change in error reporting. I'll be recompiling PHP this weekend.

**Comment by niol** [comment]
I cannot reproduce so I cannot go further regarding this.

**Comment by spence91** [comment]
Thanks for taking the time to respond. I'll close the ticket
