### ISSUE TITLE
Can't update a specific source, error not enough precise

### ISSUE THREAD

**Issue by Keyhaku** [SSilence/selfoss#698]
Hi,

I’ve met a problem with the version 2.14 of Selfoss, here is the description :
## Symptom

On refresh/synchronise i had the following error from Selfoss : 

" Can not refresh sources  : Internal server error "

From my web server log i had :

"PHP message: gzdecode(): data error"

Yet, some sources were correctly synchronised.
## The Actual problem

In fact the error was caused by one single source : Superfuture

the exact url : http://superfuture.com/rss

Why ? Well I don’t know, to me the feed is exatcly like the others (I’ve also tried all the type of feed possible)
## What could be great to do ?

Of course find what is causing problem with this url, but imo the error could be better handled, is it possible to display a more precise message like " Problem with the source : 'URL' " ( Since you can't desactivate sources, i had to delete and reenter every single of my sources before i could find the one responsible)?
## System Running

Freebsd 10.2  with PHP 5.6
I Also tried the same url on a debian server, i had no error but the source was not synchronised ...

**Comment by niol** [comment]
I cannot reproduce. Can you get a line number for this error?

**Comment by jtojnar** [comment]
Closing – cleaning. Please reopen if the issue is still happening.
