### ISSUE TITLE
expose rss feed

### ISSUE THREAD

**Issue by Kidlike** [SSilence/selfoss#702]
I don't know if this exists already, couldn't find it anywhere.

Is it possible to expose all the incoming rss feeds to a new rss feed provided by selfoss ?

So, if your installation url is https://mydomain.com/selfoss, then expose all feeds to 
https://mydomain.com/selfoss/rss or something like that..

**Comment by bendem** [comment]
it's exposed at `/feed`

**Comment by Kidlike** [comment]
Peachy ! :D

**Comment by aminecmi** [comment]
Is there a specific ```/feed``` alternative to saved items ?

**Comment by niol** [comment]
Not that I know but very easy to add.

**Comment by aminecmi** [comment]
That would be extremely usefull!

**Comment by niol** [comment]
Looking at the code, this seems to already work: use ```/rss?type=starred``` or ```/feed?type=starred```.

**Comment by aminecmi** [comment]
So great! Thanks!
