### ISSUE TITLE
No thumbnail when guetting the items list.

### ISSUE THREAD

**Issue by aminecmi** [SSilence/selfoss#704]
I'm trying to implement my own android reader, but I'm facing a little problem.

When calling the /items route, ALL the thumbnails are empty.

Is this normal ?

**Comment by niol** [comment]
What do you mean? 404 error or empty files?

**Comment by aminecmi** [comment]
When calling this [route](https://github.com/SSilence/selfoss/wiki/Restful-API-for-Apps-or-any-other-external-access), the thumbnail field is always empty.

**Comment by niol** [comment]
The ```thumbnail``` field is only used for ```reddit2```, ```youtube```, ```rss/images``` et ```twitter/usertimeline``` spouts.

**Comment by aminecmi** [comment]
Ok, thanks. I wasn't aware of that.
