### ISSUE TITLE
The data could not be converted to UTF-8

### ISSUE THREAD

**Issue by drencrom** [SSilence/selfoss#706]
I added a new source today (http://www.space.com/home/feed/site.xml) and I got this error:

```
2015-09-25 14:00:12 error loading feed content: The data could not be converted to UTF-8. 
You MUST have either the iconv or mbstring extension installed. Upgrading to PHP 5.x (which 
includes iconv) is highly recommended. 
```

The site.xml file has `encoding="UTF-8"`. I have php 5.6.12 and the iconv.so extension is installed and not commented out in php.ini. I'm using selfoss 2.13.

¿Any Ideas?
Thanks

**Comment by f3bruary** [comment]
I get this for 2 feeds too.

**Comment by niol** [comment]
The space.com feed works well for me. I need to reproduce a failure to try to fix this.

**Comment by drencrom** [comment]
I had this problem for a few days but then it worked. I updated to 2.14 but I still had the problem there until it fixed itself.
Maybe @f3bruary can send the problematic feeds.

**Comment by niol** [comment]
This means the offending content is gone from the feed...

**Comment by jtojnar** [comment]
Closing. If it is still occurring please reopen.
