### ISSUE TITLE
add auto-refresh web

### ISSUE THREAD

**Issue by arckosfr** [SSilence/selfoss#708]
Hey,

i think add a web autorefesh (F5), is a good idea, i think we are some who have selfoss open all day long and the use of external plugin is not a good alternative i think :)

Thanks

**Comment by niol** [comment]
Better is asynchroneous polling which is already implemented. Also, the item list is reloaded if it is empty. What are you missing?

**Comment by arckosfr** [comment]
actually when all item was readed, the list is not reloaded, the feed yes by cron tab, but the list no
or maye is miss something

**Comment by niol** [comment]
The list reloads if there are no items in it. Maybe new items should be appended to the list... I could not come up with good conditions for this.
