### ISSUE TITLE
feat. req.: Share with anything on Android

### ISSUE THREAD

**Issue by aslmx** [SSilence/selfoss#719]
Hi,

regularly i want to send the link to an feed item from the mobile selfoss via either text message or jabber/xmpp client.

Is there a simple way to integrate a configurable (share setting) button that will share the textline of the URL to the Android share handler (what ever it is called) so that it easily possible to share the URL with any application that handles text? 

would be a very great help and time saver!

Now i need to close the item/article, tap+hold the feed-items favicon and then copy the link, open whatever application and paste it. It also "destroys" the "workflow" when you use "foward ->" button...

**Comment by aslmx** [comment]
just learnt that this seems to be a browser thing. While the Samsung default browser does not offer a share menu for links, android-firefox does and hence allows me to easily share the URL of a feed item.

I guess the feature request is then depending on a (non existing?) API between html/js and the browser.

can probably be closed if no one else has an idea how this could be easily implemented on selfoss side without the dependency to rely on a specific browser software on client side.

**Comment by jtojnar** [comment]
I am not aware of any API for this.

**Comment by jtojnar** [comment]
There is [Navigator.share](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share) now, see https://github.com/SSilence/selfoss/pull/1017.

**Comment by aslmx** [comment]
that sounds promising. can't wait for 2.19 :)
