### ISSUE TITLE
Security of authentication

### ISSUE THREAD

**Issue by jannickfahlbusch** [SSilence/selfoss#721]
According to the [Dev-Wiki](https://github.com/SSilence/selfoss/wiki/Restful-API-for-Apps-or-any-other-external-access#authentication) i have to send the username & password in every request to selfoss.

I would consider this as insecure, because the consequence of this is, that the password needs to be stored in plaintext in the browser cache.

Wouldn't it be better, if there were something like an `sessionToken` which would be used for authentication after the initial login?

**Comment by niol** [comment]
Yes, it would be better. This is only true for the API, the user interface uses standard PHP sessions.
