### ISSUE TITLE
Apache 2.4 Order Command Deprecated

### ISSUE THREAD

**Issue by zendritic** [SSilence/selfoss#722]
Hello, this is my first contribution to Github, so I apologize if my etiquette is bad.

On my server running:
Open Suse "20150909 (Tumbleweed)"
Apache 2.4
PHP 5.6.13
MySQL 15.1

I get a 500 error after installing Selfoss and setting up the database. The logs say this:

`.htaccess: Invalid command 'Order', perhaps misspelled or defined by a module not included in the server configuration`

After some research, it seems 'Order' is deprecated. The line in the .htaccess file that comes bundled with Selfoss is 

`<FilesMatch ".(ini)$">`
`Order allow,deny`
`Deny from all`
`</FilesMatch>`

If this is changed to:

`<FilesMatch ".(ini)$">`
`Require all granted`
`</FilesMatch>`

Selfoss loads successfully. I'd suggest a simple edit, but I'm not sure how to make this compatible with older versions of Apache.

Thank you,
Z

**Comment by niol** [comment]
This would rather be ```Require all denied``` because the goal of the rule is to deny public access of configuration files.
This also could work by enabling ```mod_access_compat```.
Anyway I use apache 2.4, I think very few people use apache 2.2 now, so I can propose a patch for this.
