### ISSUE TITLE
Error 500 when getting items by tags

### ISSUE THREAD

**Issue by drasill** [SSilence/selfoss#729]
Hi,

when listing items for one tag, I've got a 500 error : "an error occured".

The error.log shows `PDOStatement: bind or column index out of range`.

I'm using sqlite, and the git/master version.
Listing "all items" does work.

**Comment by drasill** [comment]
The culprit seems to be 1dca4d76f29ebb396bd28f219ef7781656134534.

**Comment by niol** [comment]
Yes, this should not have been merged:
- it has only been tested with MySQL
- I could not understand what is being fixed
- it moves the join logic into PHP which I've never seen as good practrice,
- it leads to worse performance if one has many tags.
I suggest to revert the commit.

**Comment by SSilence** [comment]
I reverted this commits.

**Comment by drasill** [comment]
Thanks !
