### ISSUE TITLE
[Question] How to pass the POST parameters to the API?

### ISSUE THREAD

**Issue by jlnostr** [SSilence/selfoss#734]
Hi,
I have one question that is barely documented in the Wiki. **In which format do I need to submit the parameters?**

For example, I'm trying to add a subscription, so I perform a POST request to `../source`. All the required fields are submitted as JSON object like the following example.

``` json
{
    "title": "Neues Deutschland",
    "spout": "spouts\\rss\\feed",
    "tags": "",
    "params": {
        "url": "http://neues-deutschland.de/rss/neues-deutschland.xml"
    }
}
```

However, selfoss only returns HTTP code 400 with the message `{"title":"no data for title given"}`. **And how can I transmit the credentials of the user in the example above, if there are any?**

**Comment by jtojnar** [comment]
Parameters are spout specific, `rss\feed` in particular only requires [`url` parameter](https://github.com/SSilence/selfoss/blob/c3841a00c165a6d7cc92131f8e359bb9a6a403cb/spouts/rss/feed.php#L54).

[Authentication](https://github.com/SSilence/selfoss/wiki/Restful-API-for-Apps-or-any-other-external-access#authentication) is documented on wiki.

Not sure why it doesn’t accept title though.

**Comment by jlnostr** [comment]
Yes, authentication is documented but I'm not a fan of submitting the credentials via GET parameter. I prefer the POST parameter, how can I achieve this? Maybe you could show a valid HTTP request, so I know what's my fault here :-)
Thanks in advance!

**Comment by jtojnar** [comment]
You can send the credentials in either `GET` or `POST` parameter.

**Comment by jlnostr** [comment]
Yes, I've understand this. Is this the correct JSON object I need to submit?

```json
{
    "username": "user",
    "password": "passw0rd",
    "title": "Neues Deutschland",
    "spout": "spouts\\rss\\feed",
    "tags": "",
    "params": {
        "url": "http://neues-deutschland.de/rss/neues-deutschland.xml"
    }
}
```

**Comment by jtojnar** [comment]
It looks like it doesn’t work with JSON after all, it parses [url-encoded data](https://github.com/SSilence/selfoss/blob/9e6347bceab6c78d77bab9a01966e23749e74dd7/controllers/Sources.php#L131). The following request works for me:

```
curl -X POST 'http://sellfoss/source?username=foo&password=bar' \
-H 'Host: selfoss' \                                      
--data 'title=Neues+deuschland&tags=&filter=&spout=spouts_rss_feed&url=http%3A%2F%2Fneues-deutschland.de%2Frss%2Fneues-deutschland.xml
```

**Comment by jlnostr** [comment]
Thanks! That's what I wanted to know - you helped me a lot :)

**Comment by jtojnar** [comment]
@SSilence Is `/source` not being a JSON API intentional? Or am I missing something?

**Comment by aminecmi** [comment]
Interested in this too.

**Comment by jlnostr** [comment]
@SSilence Any update on this? Passing the parameters as url-encoded data is odd when the rest of the API is JSON based.

**Comment by jtojnar** [comment]
Are there even any API URLs that accept JSON? Some return JSON responses but it looks like they consistently only accept GET/POST parameters.

**Comment by jlnostr** [comment]
Which should be improved IMO.
