### ISSUE TITLE
an error occured: could not find driver

### ISSUE THREAD

**Issue by mcnesium** [SSilence/selfoss#739]
```
$ php ./cliupdate.php
could not find driver
- libs/f3/db/sql.php:399 PDO->__construct()
- daos/sqlite/Database.php:40 DB\SQL->__construct()
- daos/Database.php:31 daos\sqlite\Database->__construct()
- daos/Items.php:31 daos\Database->__construct()
- helpers/ContentLoader.php:33 daos\Items->__construct()
- cliupdate.php:8 helpers\ContentLoader->__construct()
an error occured: could not find driver

/var/www/domain/selfoss/libs/f3/db/sql.php:399
/var/www/domain/selfoss/daos/sqlite/Database.php:40
/var/www/domain/selfoss/daos/Database.php:31
/var/www/domain/selfoss/daos/Items.php:31
/var/www/domain/selfoss/helpers/ContentLoader.php:33
/var/www/domain/selfoss/cliupdate.php:8
```

What kind of driver could this be? This is on Selfoss Tag 2.14, Debian Testing, PHP Version 7.0.2-1 and mysqlnd 5.0.12-dev - 20150407

**Comment by niol** [comment]
This happened to me because selfoss could not read the config file and was defaulting to sqlite which was not installed on my system. Can you check that the ```config.ini``` permissions are right for the user that is running ```cliupdate.php```?

**Comment by mcnesium** [comment]
The file is owned by web server user. It neither does it using www-data nor with root itself.

    root@srv:/var/www/selfoss# ls -la ./config.ini
    -rw-rw-r-- 1 www-data mcnesium 827 Jan 26 15:46 ./config.ini

    root@srv:/var/www/selfoss# php ./cliupdate.php
    could not find driver
    - libs/f3/db/sql.php:399 PDO->__construct()
    - daos/sqlite/Database.php:40 DB\SQL->__construct()
    - daos/Database.php:31 daos\sqlite\Database->__construct()
    - daos/Items.php:31 daos\Database->__construct()
    - helpers/ContentLoader.php:33 daos\Items->__construct()
    - cliupdate.php:8 helpers\ContentLoader->__construct()
    an error occured: could not find driver

    /var/www/selfoss/libs/f3/db/sql.php:399
    /var/www/selfoss/daos/sqlite/Database.php:40
    /var/www/selfoss/daos/Database.php:31
    /var/www/selfoss/daos/Items.php:31
    /var/www/selfoss/helpers/ContentLoader.php:33
    /var/www/selfoss/cliupdate.php:8
    
    root@srv:/var/www/selfoss# sudo -u www-data php ./cliupdate.php
    could not find driver
    - libs/f3/db/sql.php:399 PDO->__construct()
    - daos/sqlite/Database.php:40 DB\SQL->__construct()
    - daos/Database.php:31 daos\sqlite\Database->__construct()
    - daos/Items.php:31 daos\Database->__construct()
    - helpers/ContentLoader.php:33 daos\Items->__construct()
    - cliupdate.php:8 helpers\ContentLoader->__construct()
    fopen(/var/www/selfoss/data/logs/default.log): failed to open stream: Permission denied
    - helpers/Logger.php:83 fopen()
    - common.php:42 helpers\Logger->log()

This is not primarily a bug report, but rather a call for help, as I might have misconfigured something.

**Comment by jtojnar** [comment]
Could you also check which `php.ini` file is used when running the php from CLI?

    php --info | grep "Configuration File"

On some systems, different config file is used and it usually does not include many extensions.

**Comment by mcnesium** [comment]
the php.ini in `/cli/` and `/fpm/` are exactly the same. Also, I do use the sqlite database, so mysql should not be a thing at all.

**Comment by PhrozenByte** [comment]
Does Selfoss in general work and is just the cli updater broken? Does the web updater (i.e. clicking the Refresh button) work?

**Comment by mcnesium** [comment]
Actually I had not tried until now. I am moving to a new server and just copied the entire path over. Now I tested, and the login screen appears properly, but after entering the login data, a blank page appears, and in the error.log it says the same:

    2016/02/11 16:35:15 [error] 24359#24359: *4 FastCGI sent in stderr: "PHP message: could not find driver
    PHP message: - selfoss/libs/f3/db/sql.php:399 PDO->__construct()
    PHP message: - selfoss/daos/sqlite/Database.php:40 DB\SQL->__construct()
    PHP message: - selfoss/daos/Database.php:31 daos\sqlite\Database->__construct()
    PHP message: - selfoss/daos/Tags.php:31 daos\Database->__construct()
    PHP message: - selfoss/controllers/Index.php:39 daos\Tags->__construct()
    PHP message: - selfoss/index.php:97 Base->run()
    PHP message: fopen(/var/www/selfoss/data/logs/default.log): failed to open stream: Permission denied
    PHP message: - selfoss/helpers/Logger.php:83 fopen()
    PHP message: - selfoss/common.php:42 helpers\Logger->log()" while reading response header from upstream, client: 10.10.10.27, server: srv2.fritz.box, request: "GET /selfoss/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "srv2.fritz.box", referrer: "http://srv2.fritz.box/selfoss/"

Is selfoss actually ready for PHP7 yet?

**Comment by jtojnar** [comment]
The only problem I have encountered on PHP 7 so far is #731.

**Comment by jtojnar** [comment]
Actually do you have `extension=pdo_sqlite.so` line uncommented in your `php.ini`?

**Comment by jtojnar** [comment]
Closing to clean up, reopen if still relevant.

**Comment by foool** [comment]
I met the same problem in my machine with Ubuntu 16.04 OS and PHP7.0 , and fixed it by installing the sqlite driver for PHP7 environment. The command is `sudo apt-get install php7.0-sqlite`

**Comment by jtojnar** [comment]
Would something like #944 help a bit?

**Comment by foool** [comment]
@jtojnar  Yes, it helps. It may be more helpful if you can add a hit in the front end.
