### ISSUE TITLE
Empty response when fetching 'tags' through API

### ISSUE THREAD

**Issue by f3bruary** [SSilence/selfoss#740]
When I browse to myselfossinstance.com/tags it returns [ ]. In the logs I see: "Error Unimplemented method for sqlite: numberOfUnreadForTag", but I don't know if it's related.

**Comment by niol** [comment]
``numberOfUnreadForTag`` was removed a while ago. Please check your installation and the version you are using.

**Comment by f3bruary** [comment]
I updated 10 minutes ago. The only thing I didn't replace during the update was the data dir

**Comment by jtojnar** [comment]
@niol [not completely](https://github.com/SSilence/selfoss/blob/master/controllers/Items.php#L149), apparently.

**Comment by PhrozenByte** [comment]
Introduced with #714 (this feature doesn't work for me anyway...)

**Comment by niol** [comment]
OK sorry I'm lagging behind git HEAD.

**Comment by PhrozenByte** [comment]
No, you're completely right, [`\daos\Items::numberOfUnreadForTag()` has been removed](https://github.com/SSilence/selfoss/search?utf8=%E2%9C%93&q=numberOfUnreadForTag), but #714 still uses it and introduces this bug. I'm not using the current HEAD either.

**Comment by niol** [comment]
This can be closed.
