### ISSUE TITLE
server returned [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error

### ISSUE THREAD

**Issue by sandyrewa** [SSilence/selfoss#746]
I try to validate my feed "https://www.specificfeeds.com/techcrunch"
but i got this error message "erver returned [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error"

When i try to validate same feed on my development server then this feed is validated.

**Comment by niol** [comment]
Is it a selfoss generated feed?
