### ISSUE TITLE
One feed not updated; everything else get updated

### ISSUE THREAD

**Issue by RogerSik** [SSilence/selfoss#761]
Hello,

since about three weeks one rss feed dont get updated.

http://feeds.feedburner.com/schnaeppchenfuchs

But when I visit this rss feed in my browser I see that there are newer entries and in selfoss are no error showed. Only that the last post is from 15 days before.

The owner of this homepage did a relaunch of the website. Maybe this helps?

Greetings
Roger

**Comment by jtojnar** [comment]
The feedburner works as proxy to the real RSS file on website’s server. It looks like when they redesigned the web site they forgot to change the link to the feed on their feedburner account and the original RSS location now redirects to the front page.

You can either let them know they forgot to update the feedburner or just use the RSS link they have in the footer: https://schnaeppchenfuchs.com/rss

**Comment by RogerSik** [comment]
Hi jtojnar thank you for your help.

I will use the rss link on the homepage.
