### ISSUE TITLE
No updating feeds on fresh installed Ubuntu 16.04 (PHP7)

### ISSUE THREAD

**Issue by RogerSik** [SSilence/selfoss#762]
Hello,

i have migrated my selfoss installation to a new Ubuntu 16.04 Server with Apache. 

Normaly I update the feeds with cliupdate over crontab. But I doens't recognize new updates. Same appears when I update it manually with my browser. 

Greetings

**Comment by RogerSik** [comment]
Hello,

after installing the package php-http the feed updating is working now.

Could this added as a requierement in the install readme?

**Comment by jtojnar** [comment]
Could you provide us with more details? What do you see in error log (or visit http://your-selfoss-instance/update) when you enable debug mode?

Do you use some special spouts? I do not have pecl-http installed and selfoss works just fine for me.

**Comment by wccrawford** [comment]
I had this same issue after upgrading my Ubuntu 14.04 to 16.04 and thus moving from php5 to php7.0.  Install php-http made it start downloading the feeds again, and php7.0-gd needed to be installed to process the images.

The debug log with neither of those installed for a feed that I knew had an item that wasn't being updated.

12864 07-20-16 16:09:48 Debug ---
12865 07-20-16 16:09:48 Debug start fetching source "Not Always Right (id: 204)
12866 07-20-16 16:09:48 Debug spout successfully loaded: spouts\rss\feed
12867 07-20-16 16:09:48 Debug fetch content
12868 07-20-16 16:09:48 Debug minimum date: 2016-06-20 16:09:48
12869 07-20-16 16:09:48 Debug start item fetching
12870 07-20-16 16:09:48 Debug destroy spout object
12871 07-20-16 16:09:48 Debug ---

After installing those 2 packages, it added the new item as an unread item as expected.

**Comment by Swoogan** [comment]
I also hit this issue after upgrading Ubuntu Server 14.04 to 16.04. I'm not using any spouts. Running `sudo apt install php-http` immediately fixed it. Running the `cliupdate.php` didn't produce any output (no errors) and there was nothing in `data/logs/default.log`.

I wouldn't have figured this out on my own. The documentation on the homepage says the requirement is "PHP 5.3 or higher with the php-gd extension enabled." In this case, that wasn't enough, but I also understand not knowing or being able to list _all_ the packages for each and every distro.

Anyway, `php-http` also installs `php7.0-xml php-xml php-pear`.

**Comment by jtojnar** [comment]
Closed, since requirements were updated.
