### ISSUE TITLE
https for the forum

### ISSUE THREAD

**Issue by auzias** [SSilence/selfoss#764]
A valid certificate for the [forum][http://selfoss.aditu.de/forum/) would be great!

I hear that some [free ones were available](https://letsencrypt.org/).

**Comment by gerundt** [comment]
If Tobias has a at least *PrivatPlus* at his hoster all-inkl.com he can use Let’s Encrypt:
https://dhue.de/freies-lets-encrypt-zertifikart-all-inkl/

**Comment by SSilence** [comment]
Thanks for the hint. I activated lets encrypt on this domain too.
