### ISSUE TITLE
Error code for feed: Invalid xml

### ISSUE THREAD

**Issue by ritzelbuerste** [SSilence/selfoss#778]
Feed: www.qiez.de/xml/rss
Selfoss: 2.15
Error Message: error loading feed content: This XML document is invalid, likely due to invalid characters. XML error: EntityRef: expecting ';' at line 62, column 109

**Comment by jtojnar** [comment]
The feed is not a well-formed XML document. Could you please report it to the site administrator so they could fix it?

Validation report: https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fwww.qiez.de%2Fxml%2Frss
