### ISSUE TITLE
API requests not working

### ISSUE THREAD

**Issue by AlexMeier99** [SSilence/selfoss#803]
Hi, i'am using selfoss on my own server since a few months and after seaching for a desktop client, i decided to try creating on my own.
But at after using a big amount of combinations of npm packages like request or request-json with electron and/or NW.js i am frustrated. Because i received just one result a html response telling me that the requested page need Javascript been enabled. When i type my selfoss adress plus /items like being explained in the API docs a see the usual JSON structure.
Help me please!

**Comment by jtojnar** [comment]
What are you trying to achieve? Do you want to get the HTML or JSON?

**Comment by AlexMeier99** [comment]
Thanks for asking, i forgot to mention. I would like to get pure JSON or if possible to parse befor HTML.
Is there a PHP class/function for doing that?



-------- Ursprüngliche Nachricht --------
Von: Jan Tojnar <notifications@github.com> 
Datum:24.09.2016  23:07  (GMT+01:00) 
An: SSilence/selfoss <selfoss@noreply.github.com> 
Cc: AlexMeier99 <alawissmartphone@gmail.com>,Author <author@noreply.github.com> 
Betreff: Re: [SSilence/selfoss] API requests not working (#803) 

What are you trying to achieve? Do you want to get the HTML or JSON?

**Comment by AlexMeier99** [comment]
This what i get when doing my REST API Request:
<html><body><script type="text/javascript" src="/aes.js" ></script><script>function toNumbers(d){var e=[];d.replace(/(..)/g,function(d){e.push(parseInt(d,16))});return e}function toHex(){for(var d=[],d=1==arguments.length&&arguments[0].constructor==Array?arguments[0]:arguments,e="",f=0;f<d.length;f++)e+=(16>d[f]?"0":"")+d[f].toString(16);return e.toLowerCase()}var a=toNumbers("f655ba9d09a112d4968c63579db590b4"),b=toNumbers("98344c2eee86c3994890592585b49f80"),c=toNumbers("7d15b314be9eb377575f55ca12c50b7a");document.cookie="__test="+toHex(slowAES.decrypt(c,2,a,b))+"; expires=Thu, 31-Dec-37 23:55:55 GMT; path=/"; location.href="http://myselfossdomain.com/selfoss/tags?i=1";</script><noscript>This site requires Javascript to work, please enable Javascript in your browser or use a browser with Javascript support</noscript></body></html>

**Comment by jtojnar** [comment]
What REST endpoint are you targeting? I cannot find “This site requires Javascript to work” anywhere in the code.

You can find all the requests along with their types in [index.php](https://github.com/SSilence/selfoss/blob/master/index.php#L53).

**Comment by jtojnar** [comment]
Do you use some kind of free hosting that injects ads into pages using JavaScript?

**Comment by AlexMeier99** [comment]
Hi thanks for answering me. I use a free hosting plan but they don't inject any Ads into my pages.
I tried do this http://alawistablet.ihostfull.com/selfoss/items and after many different methods and request a few days later this :http://alawistablet.ihostfull.com/selfoss/feed

**Comment by jtojnar** [comment]
It looks like your hosting uses JavaScript DoS protection or something. Just curling returns `403 Forbidden`:

```shell
$ curl http://alawistablet.ihostfull.com/selfoss/feed
<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

And if I add `User-Agent` header it will reveal the troublesome JavaScript:

```shell
$ curl  -H 'User-Agent: Mozilla/5.0' http://alawistablet.ihostfull.com/selfoss/feed
<html><body><script type="text/javascript" src="/aes.js" ></script><script>function toNumbers(d){var e=[];d.replace(/(..)/g,function(d){e.push(parseInt(d,16))});return e}function toHex(){for(var d=[],d=1==arguments.length&&arguments[0].constructor==Array?arguments[0]:arguments,e="",f=0;f<d.length;f++)e+=(16>d[f]?"0":"")+d[f].toString(16);return e.toLowerCase()}var a=toNumbers("b026324c6904b2a9cb4b88d6d61c81d1"),b=toNumbers("26ab0db90d72e28ad0ba1e22ee510510"),c=toNumbers("6d7fce9fee471194aa8b5b6e47267f03");document.cookie="__test="+toHex(slowAES.decrypt(c,2,a,b))+"; expires=Thu, 31-Dec-37 23:55:55 GMT; path=/"; location.href="http://alawistablet.ihostfull.com/selfoss/feed?i=1";</script><noscript>This site requires Javascript to work, please enable Javascript in your browser or use a browser with Javascript support</noscript></body></html>%
```

**Comment by AlexMeier99** [comment]
Ok, so the result is that API request aren't on this server?

**Comment by jtojnar** [comment]
You can try to ask the provider how to disable the protection. Or switch to a different one.

**Comment by aahco** [comment]
Dear Alex, did you get API REST work with ihostfull free host, if so please let me know how you solved your problem. I just get this problem and there is support from ihostfull to ask disable DoS protection.

Regards,
