### ISSUE TITLE
Error pulling from reddit

### ISSUE THREAD

**Issue by bouncingbunyip** [SSilence/selfoss#805]
I have added a reddit spout pulling from: https://www.reddit.com/r/SmarterEveryDay/  
When I refresh the listings I get the "internal error" popup.

In the default.log I see the following:
09-29-16 0:26:01 Debug start fetching source "Reddit Smarter(id: 5) 
09-29-16 0:26:01 Debug spout successfully loaded: spouts\reddit\reddit2
09-29-16 0:26:01 Debug fetch content
09-29-16 0:26:02 Error Trying to get property of non-object
/Users/jackal/Sites/selfoss/spouts/reddit/reddit2.php:142
/Users/jackal/Sites/selfoss/helpers/ContentLoader.php:89
/Users/jackal/Sites/selfoss/helpers/ContentLoader.php:46
/Users/jackal/Sites/selfoss/controllers/Index.php:201
/Users/jackal/Sites/selfoss/libs/f3/base.php:1305
/Users/jackal/Sites/selfoss/index.php:97

The row in the sources table looks like this (I've changed my username/password)
Reddit Smarter
spouts\reddit\reddit2
{&quot;url&quot;:&quot;\/r\/SmarterEveryDay\/&quot;,&quot;username&quot;:&quot;[user]&quot;,&quot;password&quot;:&quot;[pass]&quot;}
NULL
1475101921
NULL

I have tried a number of reddit pages and get the same error each time.

**Comment by jtojnar** [comment]
Can you actually try [this quick patch](https://github.com/jtojnar/selfoss/tree/reddit-fix)? The reddit spout uses _http_ instead of _https_ for accessing reddit and when the reddit tries to redirect us the curl just dies silently, producing `null`.

**Comment by bouncingbunyip** [comment]
Just tried your patch, and it worked!  I am able to pull from the Reddit listed above and have items show up.
