### ISSUE TITLE
Reddit spout doesn't follow 301 directive

### ISSUE THREAD

**Issue by bouncingbunyip** [SSilence/selfoss#806]
I have added the /r/pics/ subreddit as a spout.

Some of the entries in the subreddit return a 301, and I see the following in the `items` table:
&lt;?xml version="1.0" standalone="yes"?&gt;
&lt;!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd"&gt;
301 Moved Permanently&#xd;
<h1>301 Moved Permanently</h1>&#xd;
nginx/1.4.7&#xd;

This is the 'share' link on reddit to the entry:
https://www.reddit.com/r/pics/comments/555nqo/get_a_hammock_they_said/?ref=share&ref_source=link

I have seen this on a few entries but I'm not sure how to reliably 'force' it to happen.

Reading through the issues, there's a suggestion to fix the instapaper spout with:
curl_setopt( $ch, CURLOPT_FOLLOWLOCATION, TRUE);

So I've added that to my reddit2.php file_get_contents_curl() method, to see if it works.  I'll keep you posted.

**Comment by jtojnar** [comment]
`CURLOPT_FOLLOWLOCATION` can help on some configs but not all (see `safe_mode`/`open_basedir` directives). Selfoss should migrate to something like [guzzle](https://packagist.org/packages/guzzlehttp/guzzle) which would solve those problems.

**Comment by niol** [comment]
Those problems have been solved for you in ```f3```. Please use the ```WebClient``` helper:

```
try {
     $foo = \helpers\WebClient::request($url);
}catch( \exception $e ) {
     \F3::get('logger')->log("failed to get foo: ".$e->getMessage(), \DEBUG);
}
```

**Comment by jtojnar** [comment]
`\helpers\WebClient` cannot establish a session though. It should be possible to do with `\Web` but it would be probably more productive to use [existing solution](https://packagist.org/search/?tags=curl) instead of creating our own.

**Comment by jtojnar** [comment]
Incidentally, #835 removes the need for redirect in reddit spout.
