### ISSUE TITLE
#sources showing multiple instances of each source

### ISSUE THREAD

**Issue by bouncingbunyip** [SSilence/selfoss#808]
I have 20 or so sources in the database.  When I click on the 'sources' link in the left nav I get a listing of the sources, where all of them are listed multiple times. You can see the behavior in the attached screenshot.
<img width="660" alt="screen shot 2016-10-04 at 5 19 40 pm" src="https://cloud.githubusercontent.com/assets/11684665/19097096/ce9daa16-8a56-11e6-9c01-b4b17f53896b.png">

If I call /sources/list directly then I get something like: 

 [{"id":"3","title":"Ars Technica","tags":"tech","spout":"spouts\\rss\\feed","params":{"url":"http:\/\/feeds.arstechnica.com\/arstechnica\/index"},"filter":"","error":"","lastentry":"1475600209","icon":"e0db86a3921b34d8fd0da6b821d1f57b.png"},{"id":"3","title":"Ars Technica","tags":"tech","spout":"spouts\\rss\\feed","params":{"url":"http:\/\/feeds.arstechnica.com\/arstechnica\/index"},"filter":"","error":"","lastentry":"1475600209","icon":"e0db86a3921b34d8fd0da6b821d1f57b.png"},{"id":"3","title":"Ars Technica","tags":"tech","spout":"spouts\\rss\\feed","params":{"url":"http:\/\/feeds.arstechnica.com\/arstechnica\/index"},"filter":"","error":"","lastentry":"1475600209","icon":"e0db86a3921b34d8fd0da6b821d1f57b.png"},{"id":"3","title":"Ars Technica","tags":"tech","spout":"spouts\\rss\\feed","params":{"url":"http:\/\/feeds.arstechnica.com\/arstechnica\/index"},"filter":"","error":"","lastentry":"1475600209","icon":"e0db86a3921b34d8fd0da6b821d1f57b.png"},{"id":"3","title":"Ars Technica","tags":"tech","spout":"spouts\\rss\\feed","params":{"url":"http:\/\/feeds.arstechnica.com\/arstechnica\/index"},"filter":"","error":"","lastentry":"1475600209","icon":"e0db86a3921b34d8fd0da6b821d1f57b.png"},{"id":"3","title":"Ars Technica","tags":"tech","spout":"spouts\\rss\\feed","params":{"url":"http:\/\/feeds.arstechnica.com\/arstechnica\/index"},"filter":"","error":"","lastentry":"1475600209","icon":"e0db86a3921b34d8fd0da6b821d1f57b.png"},{"id":"3","title":"Ars Technica","tags":"tech","spout":"spouts\\rss\\feed","params":{"url":"http:\/\/feeds.arstechnica.com\/arstechnica\/index"},"filter":"","error":"","lastentry":"1475600209","icon":"e0db86a3921b34d8fd0da6b821d1f57b.png"},{"id":"3","title":"Ars Technica","tags":"tech","spout":"spouts\\rss\\feed","params":{"url":"http:\/\/feeds.arstechnica.com\/arstechnica\/index"},"filter":"","error":"","lastentry":"1475600209","icon":"e0db86a3921b34d8fd0da6b821d1f57b.png"},{"id":"3","title":"Ars Technica","tags":"tech","spout":"spouts\\rss\\feed","params":{"url":"http:\/\/feeds.arstechnica.com\/arstechnica\/index"},"filter":"","error":"","lastentry":"1475600209","icon":"e0db86a3921b34d8fd0da6b821d1f57b.png"},{"id":"3","title":"Ars Technica","tags":"tech","spout":"spouts\\rss\\feed","params":{"url":"http:\/\/feeds.arstechnica.com\/arstechnica\/index"},"filter":"","error":"","lastentry":"1475600209","icon":"e0db86a3921b34d8fd0da6b821d1f57b.png"},{"id":"3","title":"Ars Technica","tags":"tech","spout":"spouts\\rss\\feed","params":{"url":"http:\/\/feeds.arstechnica.com\/arstechnica\/index"},"filter":"","error":"","lastentry":"1475600209","icon":"e0db86a3921b34d8fd0da6b821d1f57b.png"},{"id":"3","title":"Ars Technica","tags":"tech","spout":"spouts\\rss\\feed","params":{"url":"http:\/\/feeds.arstechnica.com\/arstechnica\/index"},"filter":"","error":"","lastentry":"1475600209","icon":"e0db86a3921b34d8fd0da6b821d1f57b.png"},{"id":"3","title":"Ars Technica","tags":"tech","spout":"spouts\\rss\\feed","params":{"url":"http:\/\/feeds.arstechnica.com\/arstechnica\/index"},"filter":"","error":"","lastentry":"1475600209","icon":"e0db86a3921b34d8fd0da6b821d1f57b.png"},{"id":"3","title":"Ars Technica","tags":"tech","spout":"spouts\\rss\\feed","params":{"url":"http:\/\/feeds.arstechnica.com\/arstechnica\/index"},"filter":"","error":"","lastentry":"1475600209","icon":"e0db86a3921b34d8fd0da6b821d1f57b.png"},{"id":"3","title":"Ars Technica","tags":"tech","spout":"spouts\\rss\\feed","params":{"url":"http:\/\/feeds.arstechnica.com\/arstechnica\/index"},"filter":"","error":"","lastentry":"1475600209","icon":"e0db86a3921b34d8fd0da6b821d1f57b.png"},{"id":"3","title":"Ars Technica","tags":"tech","spout":"spouts\\rss\\feed","params":{"url":"http:\/\/feeds.arstechnica.com\/arstechnica\/index"},"filter":"","error":"","lastentry":"1475600209","icon":"e0db86a3921b34d8fd0da6b821d1f57b.png"},{"id":"3","title":"Ars Technica","tags":"tech","spout":"spouts\\rss\\feed","params":{"url":"http:\/\/feeds.arstechnica.com\/arstechnica\/index"},"filter":"","error":"","lastentry":"1475600209","icon":"e0db86a3921b34d8fd0da6b821d1f57b.png"},{"id":"3","title":"Ars Technica","tags":"tech","spout":"spouts\\rss\\feed","params":{"url":"http:\/\/feeds.arstechnica.com\/arstechnica\/index"},"filter":"","error":"","lastentry":"1475600209","icon":"e0db86a3921b34d8fd0da6b821d1f57b.png"},{"id":"3","title":"Ars Technica","tags":"tech","spout":"spouts\\rss\\feed","params":{"url":"http:\/\/feeds.arstechnica.com\/arstechnica\/index"},"filter":"","error":"","lastentry":"1475600209","icon":"e0db86a3921b34d8fd0da6b821d1f57b.png"},{"id":"3","title":"Ars Technica","tags":"tech","spout":"spouts\\rss\\feed","params":

**Comment by jtojnar** [comment]
That is definitely odd. What version of selfoss and which database backend do you use?

**Comment by bouncingbunyip** [comment]
selfloss 2.15
mysql Server version: 5.5.51-38.2 - Percona Server (GPL), Release 38.2, Revision 727

**Comment by bouncingbunyip** [comment]
I figured it out.  The `items`.`id` column was set as int(11) without auto-increment and no primary key.  
I updated the table so `id` is auto-increment and is a primary key.  Everything works.

So how did the table get set up incorrectly?  Not sure, but my money is on operator error (that would be me).
