### ISSUE TITLE
Error at fetching private twitter list

### ISSUE THREAD

**Issue by severo** [SSilence/selfoss#810]
I use selfoss 2.15

I configured a new source, a Twitter List Timeline, and I get:

> error loading feed content: invalid twitter response

I only have the problem with private lists, not public lists.

**Comment by jtojnar** [comment]
Are you sure you have entered the keys of the user that has access to the list?

**Comment by severo** [comment]
I think so (consumer key and secret + username)

**Comment by jtojnar** [comment]
You can try this: https://github.com/jtojnar/selfoss/commit/485a28c927183c3b638fcb53f9a461c0f89a0484

**Comment by severo** [comment]
With this patch, it works perfectly! Thanks a lot for the quick work. Do you think it will be shipped with the next version?
