### ISSUE TITLE
Problems with Twitter spout for accounts with emojis

### ISSUE THREAD

**Issue by severo** [SSilence/selfoss#811]
For example, the tweet https://twitter.com/archiloque/status/794160285615616000 

![captura de pantalla de 2016-11-03 10 26 44](https://cloud.githubusercontent.com/assets/1676121/19969785/411af3ee-a1b0-11e6-99a7-9b36da2b8452.png)

appears the following way in selfoss:

![captura de pantalla de 2016-11-03 10 27 26](https://cloud.githubusercontent.com/assets/1676121/19969836/62f2a9ee-a1b0-11e6-8af5-ae40d2a877ce.png)

**Comment by jtojnar** [comment]
Do you use mysql? If so, you need to use `utf8mb4` instead of `utf8`. https://github.com/SSilence/selfoss/issues/534#issuecomment-54082599

**Comment by severo** [comment]
I did the  same as https://github.com/SSilence/selfoss/issues/534#issuecomment-172329123, but I get:

> Error PDOStatement: COLLATION 'utf8_bin' is not valid for CHARACTER SET 'utf8mb4'

**Comment by severo** [comment]
Some details on my configuration:

> mysql> SHOW VARIABLES LIKE '%char%';
> +--------------------------+----------------------------+
> | Variable_name            | Value                      |
> +--------------------------+----------------------------+
> | character_set_client     | utf8                       |
> | character_set_connection | utf8                       |
> | character_set_database   | utf8mb4                    |
> | character_set_filesystem | binary                     |
> | character_set_results    | utf8                       |
> | character_set_server     | latin1                     |
> | character_set_system     | utf8                       |
> | character_sets_dir       | /usr/share/mysql/charsets/ |
> +--------------------------+----------------------------+
> 8 rows in set (0.00 sec)
> 
> mysql>  SHOW VARIABLES LIKE '%collation%';
> +----------------------+--------------------+
> | Variable_name        | Value              |
> +----------------------+--------------------+
> | collation_connection | utf8_general_ci    |
> | collation_database   | utf8mb4_unicode_ci |
> | collation_server     | latin1_swedish_ci  |
> +----------------------+--------------------+
> 3 rows in set (0.00 sec)
> 
> 
> mysql> show variables like "character_set_database";
> +------------------------+---------+
> | Variable_name          | Value   |
> +------------------------+---------+
> | character_set_database | utf8mb4 |
> +------------------------+---------+
> 1 row in set (0.00 sec)
> 

> mysql> SELECT default_character_set_name FROM information_schema.SCHEMATA  WHERE schema_name = "selfoss";
> +----------------------------+
> | default_character_set_name |
> +----------------------------+
> | utf8mb4                    |
> +----------------------------+
> 1 row in set (0.00 sec)
> 
> mysql> SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_COLLATION     FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA="selfoss";
> +---------------+--------------+------------+--------------------+
> | TABLE_CATALOG | TABLE_SCHEMA | TABLE_NAME | TABLE_COLLATION    |
> +---------------+--------------+------------+--------------------+
> | def           | selfoss      | items      | utf8mb4_general_ci |
> | def           | selfoss      | sources    | utf8mb4_general_ci |
> | def           | selfoss      | tags       | utf8mb4_general_ci |
> | def           | selfoss      | version    | utf8mb4_general_ci |
> +---------------+--------------+------------+--------------------+
> 4 rows in set (0.00 sec)
> 
> ---------------+--------------+------------+-------------+--------------------+
> | TABLE_CATALOG | TABLE_SCHEMA | TABLE_NAME | COLUMN_NAME | COLLATION_NAME     |
> +---------------+--------------+------------+-------------+--------------------+
> | def           | selfoss      | items      | id          | NULL               |
> | def           | selfoss      | items      | datetime    | NULL               |
> | def           | selfoss      | items      | title       | utf8mb4_general_ci |
> | def           | selfoss      | items      | content     | utf8mb4_general_ci |
> | def           | selfoss      | items      | thumbnail   | utf8mb4_general_ci |
> | def           | selfoss      | items      | icon        | utf8mb4_general_ci |
> | def           | selfoss      | items      | unread      | NULL               |
> | def           | selfoss      | items      | starred     | NULL               |
> | def           | selfoss      | items      | source      | NULL               |
> | def           | selfoss      | items      | uid         | utf8mb4_general_ci |
> | def           | selfoss      | items      | link        | utf8mb4_general_ci |
> | def           | selfoss      | items      | updatetime  | NULL               |
> | def           | selfoss      | items      | author      | utf8mb4_general_ci |
> | def           | selfoss      | items      | shared      | NULL               |
> | def           | selfoss      | sources    | id          | NULL               |
> | def           | selfoss      | sources    | title       | utf8mb4_general_ci |
> | def           | selfoss      | sources    | tags        | utf8mb4_general_ci |
> | def           | selfoss      | sources    | spout       | utf8mb4_general_ci |
> | def           | selfoss      | sources    | params      | utf8mb4_general_ci |
> | def           | selfoss      | sources    | filter      | utf8mb4_general_ci |
> | def           | selfoss      | sources    | error       | utf8mb4_general_ci |
> | def           | selfoss      | sources    | lastupdate  | NULL               |
> | def           | selfoss      | sources    | lastentry   | NULL               |
> | def           | selfoss      | tags       | tag         | utf8mb4_general_ci |
> | def           | selfoss      | tags       | color       | utf8mb4_general_ci |
> | def           | selfoss      | version    | version     | NULL               |
> +---------------+--------------+------------+-------------+--------------------+
> 26 rows in set (0.00 sec)
>

**Comment by severo** [comment]
The request that produces the error is:

```
161103 15:05:39  1203 Connect   selfoss@localhost on selfoss
                 1203 Query     SET NAMES utf8mb4
                 1203 Query     SHOW TABLES
                 1203 Query     SELECT version FROM version ORDER BY version DESC LIMIT 0, 1
                 1203 Query     SELECT tag, color, COUNT(items.id) AS unread
                   FROM tags AS tags,
                        sources AS sources
                   LEFT OUTER JOIN items AS items
                       ON (items.source=sources.id AND items.unread=1)
                   WHERE CONCAT(',', sources.tags, ',') LIKE CONCAT('%,', tags.tag, ',%') COLLATE utf8_bin
                   GROUP BY tags.tag, tags.color
                   ORDER BY LOWER(tags.tag)
                 1203 Quit

```

**Comment by severo** [comment]
As I see:

```
$ grep -R utf8_bin .

./daos/mysql/Items.php:              $where .= " AND ( CONCAT( ',' , sources.tags , ',' ) LIKE _utf8 :tag COLLATE utf8_bin ) ";
./daos/mysql/Statements.php:        return "CONCAT(',', $column, ',') LIKE CONCAT('%,', $value, ',%') COLLATE utf8_bin";
./daos/mysql/Tags.php:            $where = 'WHERE tag = _utf8 :tag COLLATE utf8_bin';

```

Does it mean that I need to change to `utf8mb4_general_ci` in theses three files?
