### ISSUE TITLE
One feed gives an error

### ISSUE THREAD

**Issue by janw-oostendorp** [SSilence/selfoss#814]
I have one feed which gives an error: https://tommcfarlin.com/feed/

The debug log gives the following on manual refresh

```
11-04-16 10:40:23 Debug logged in using valid session
11-04-16 10:40:23 Debug Establish database connection
11-04-16 10:40:23 Debug ---
11-04-16 10:40:23 Debug start fetching source "Tom McFarlin (id: 95)
11-04-16 10:40:23 Debug spout successfully loaded: spouts\rss\feed
11-04-16 10:40:23 Debug fetch content
11-04-16 10:40:24 Error error loading feed content for Tom McFarlin: cURL error 22: The requested URL returned error: 400 Bad Request
11-04-16 10:40:24 Debug ---
```

Is this a known problem?
Does anybody else get the same error with this feed?  

Does anybody can help on my way where this error is actually thrown?
Maybe I can find it on my own.

**Comment by niol** [comment]
This is user agent filtering on the server side.

```
$ curl -I https://tommcfarlin.com/feed/
HTTP/1.1 200 OK
Server: nginx
Date: Fri, 04 Nov 2016 10:59:23 GMT
Content-Type: application/rss+xml; charset=UTF-8
Connection: keep-alive
X-Robots-Tag: noindex, follow
Link: <https://tommcfarlin.com/wp-json/>; rel="https://api.w.org/"
Last-Modified: Thu, 03 Nov 2016 18:22:59 GMT
Cache-Control: max-age=3600
Expires: Fri, 04 Nov 2016 11:59:23 GMT
Host-Header: 192fc2e7e50945beb8231a492d6a8024
Vary: Accept-Encoding

$ curl -I -A "Selfoss/2.16-SNAPSHOT (SimplePie/1.3.1; +http://selfoss.aditu.de)" https://tommcfarlin.com/feed/
HTTP/1.1 400 Bad Request
Server: nginx
Date: Fri, 04 Nov 2016 11:01:01 GMT
Content-Type: text/html
Content-Length: 1393
Connection: keep-alive
Last-Modified: Wed, 16 Mar 2016 09:07:51 GMT
ETag: "571-52e26d93027c0"
Accept-Ranges: bytes
Host-Header: 192fc2e7e50945beb8231a492d6a8024
```

The error page says:

> The page you are trying to access is restricted due to a security rule. If you believe the security rule is affecting the normal operation of your website, contact your host support team and provide detailed instructions how to recreate this error. They will be able to assist you with rectifying the problem and adjusting the security configuration if needed.

There's not much selfoss can do apart from making the user-agent configurable for specific feeds. But that's much work for working around something that should be fixed server side.

**Comment by janw-oostendorp** [comment]
I tried pinging the domain and didn't saw an error. This is helpful I'll contact the website owner.
