### ISSUE TITLE
New Version only work with MySQL 5.5.3 or later

### ISSUE THREAD

**Issue by mariohommel** [SSilence/selfoss#820]
After updating to the new release 2.16 I get an error when loading the selfoss homepage. Turning on debugging shows an SQL Error 1115 - unknown character set 'utf8mb4'.
This is because this charset is only available in MySQL 5.5.3 or later. This should be mentioned in the release notes or the code should be modified to work with databases missing this charset.

**Comment by jtojnar** [comment]
I cannot change the release notes, so here is the updated documentation #821.

**Comment by ziegenberg** [comment]
@SSilence:
Was solved in commit bfb2b206674768868b2ef35326dcdc8f1f6b0474. Ticket can be closed.
