### ISSUE TITLE
Unable to mark items as read

### ISSUE THREAD

**Issue by tgrosinger** [SSilence/selfoss#822]
I am no longer able to mark items as read. I am not sure what changed to prompt this to break, but I tried upgrading to latest but the problem did not go away.

Versions
------------
Selfoss Version: bfb2b206674768868b2ef35326dcdc8f1f6b0474 (latest commit)
Ubuntu 16.04 LTS
PHP 7.0.8-0ubuntu0.16.04.3
Apache/2.4.18

Details
---------

Adding new articles is still working properly, and the articles are listed and displayed correctly, so this does not seem to be a database issue.

When I click to open an article and mark it read, I get this response from the webserver (shown in the network tab of Chrome dev tools)

```
HTTP/1.1 403 Forbidden
Date: Fri, 09 Dec 2016 18:19:53 GMT
Server: Apache/2.4.18 (Ubuntu)
Strict-Transport-Security: max-age=15768000; includeSubDomains; preload
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Powered-By: Fat-Free Framework
X-XSS-Protection: 1; mode=block
Content-Length: 16
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: text/html; charset=UTF-8

an error occured
```

The Apache logs show simply:

```
[Fri Dec 09 10:19:53.552986 2016] [:error] [pid 10621] [client 10.8.0.6:41531] HTTP 403 (POST /mark/5041)
```

And the Selfoss logs show:

```
12-09-16 10:19:53 Error HTTP 403 (POST /mark/5041)
```

Any idea what is causing this or what I can do to fix it? Thank you.

**Comment by jtojnar** [comment]
Can you share your config file?

**Comment by tgrosinger** [comment]
```
server$ cat config.ini 
; see http://selfoss.aditu.de for more information about
; the configuration parameters
[globals]
db_type=pgsql
db_host=localhost
db_database=selfoss
db_username=selfoss
db_password=selfoss
db_port=5432
;db_type=mysql
;db_database=selfoss
;db_port=3306
db_prefix=
logger_level=ERROR
items_perpage=50
items_lifetime=30
base_url=
username=<redacted>
password=<redacted>
salt=<redacted>
public=
html_title=selfoss
rss_title=selfoss feed
rss_max_items=300
rss_mark_as_read=0
homepage=unread
language=0
auto_mark_as_read=1
auto_collapse=1
auto_stream_more=1
anonymizer=
use_system_font=
readability=
share=te
wallabag=
allow_public_update_access=1
unread_order=asc
load_images_on_mobile=0
auto_hide_read_on_mobile=1
env_prefix=selfoss_
```

**Comment by jtojnar** [comment]
I am not able to reproduce it. Can you enable `DEBUG` mode? Update common.php with `$f3->set('DEBUG',1);` and config.ini with `logger_level=DEBUG`.

**Comment by tgrosinger** [comment]
```
12-09-16 11:21:26 Debug logged in using valid session
12-09-16 11:21:26 Debug Establish database connection
12-09-16 11:21:30 Debug set cookie on cloud.grosinger.net/mark/ expiring in 2592000 seconds
12-09-16 11:21:30 Debug session does not contain valid auth
12-09-16 11:21:30 Error HTTP 403 (POST /mark/5054)
[libs/f3/f3.php:39] Base->error()
[controllers/Items.php:22] controllers\BaseController->needsLoggedIn()
[index.php:98] Base->run()
```

I'm not logged in? Not sure why I can see the article view then. I opened an incognito browser window and logged in again and it is working there.

On the window that is not working I cleared all cookies and re-logged in however the problem still exists.

**Comment by jtojnar** [comment]
The described behaviour makes little sense. [`/mark/:id`](https://github.com/SSilence/selfoss/blob/master/controllers/Items.php#L22) authorizes through [`needsLoggedIn`](https://github.com/SSilence/selfoss/blob/master/controllers/BaseController.php#L49) method which does essentially the same thing as [`authentication`](https://github.com/SSilence/selfoss/blob/master/controllers/Index.php#L113) method, used by the [article listings](https://github.com/SSilence/selfoss/blob/master/controllers/Index.php#L22). They should work as long as the underlying f3 framework does its job.

Moreover, I am not aware of any of the relevant components changing recently. Last thing that might affect you is the update of the f3 framework in July. What version of selfoss did you use previously?

Also, do other features like starring the items or updating sources work for you?

**Comment by tgrosinger** [comment]
I am unsure what version I had checked out previously. It was a couple months old, but definitely more recent than July.

Staring items and updating does work. It just won't let me mark as read.

**Comment by niol** [comment]
Can you compare the request headers of ```/star``` vs ```/mark``` and tell us what's different?

**Comment by tgrosinger** [comment]
Okay, I took out most of the information that was the same, leaving the User-Agent in case it was interesting. The difference here quite clearly is that for some reason the `/mark` endpoint is sending the same Cookie twice. I have no idea what could be causing this, but have deleted all the cookies from that page several times.

I made both of these requests from the same browser tab one right after the other. I omitted some of the cookie value for security.

**/mark**
```
POST /mark/5112 HTTP/1.1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36
Cookie: PHPSESSID=29844i8fhpti5q<omitted>; PHPSESSID=908qtegfgk9<omitted>
```

**/star**
```
POST /starr/5112 HTTP/1.1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36
Cookie: PHPSESSID=908qtegfgk9<omitted>
```

**Comment by niol** [comment]
I do not understand why you have two PHP session cookies. I see you are using Chrome. Can you go to Developer Tools, Application, and tell us which cookies you have for your selfoss installation, especially the domain and path attributes of those cookies?

**Comment by tgrosinger** [comment]
There is only one cookie listed. Again, leaving out some key details for security, but here is the general outline of the cookie:

* Name: `PHPSESSID`
* Value: `908qtegfgk9<omitted>`
* Domain: `.<mysub>.<mydomain>.net`
* Path: `/`

Additionally, both HTTP and Secure have a check in them. SameSite is empty.

**Comment by niol** [comment]
And id you visit ```/mark```, can you see that second ```PHPSESSID=29844i8fhpti5q<omitted>``` cookie in Developer tools ?

**Comment by tgrosinger** [comment]
No, I have no idea where that sessid is coming from. I have even tried using the Clear Storage section in the Chrome Developer tools a couple times but it still happens.

**Comment by niol** [comment]
My guess it that selfoss somehow registered a second cookie in you browser and I do not know why you cannot see it (different path? different domain?).

The cookie setting code behaves differently if running behind a reverse proxy. Are you using mod_php or something else?

I've made the patch below but I do not think it would solve your problem, but maybe prevent it from reappearing if you're not using a reverse proxy.

```diff
--- a/helpers/Authentication.php
+++ b/helpers/Authentication.php
@@ -37,8 +37,7 @@ class Authentication {
             $cookie_path = '/'.$_SERVER['SERVER_NAME'].preg_replace('/\/[^\/]+$/','',$_SERVER['PHP_SELF']).'/';
             $cookie_domain = $_SERVER['HTTP_X_FORWARDED_SERVER'];
         } else {
-            // cookie path is script dir.
-            $cookie_path = dirname($_SERVER['REQUEST_URI'])==='/'?'/':dirname($_SERVER['REQUEST_URI']).'/';
+            $cookie_path = \F3::get('BASE').'/';
             $cookie_domain = $_SERVER['SERVER_NAME'];
         }
         session_set_cookie_params($cookie_expire, $cookie_path, $cookie_domain,
```

**Comment by tgrosinger** [comment]
I am serving Selfoss through Apache, however I am just setting the document root, not using any reverse proxy.

Applying the patch did not solve the problem, like you guessed. Not sure how to test if it prevents it in the future.

**Comment by niol** [comment]
Another idea I have: if you try the cookies.txt Chrome extension, can you see your rogue PHPSESSID?

**Comment by tgrosinger** [comment]
Yes!

```
.selfoss.mydomain	TRUE	/mark/	TRUE	1483892178	PHPSESSID	29844i8f<omitted>
photos.mydomain	FALSE	/	FALSE	0	PHPSESSID	d0u76ecfdgh<omitted>
.cloud.mydomain	TRUE	/	TRUE	1484762630	PHPSESSID	1g7mnhso07<omitted>
```

Does it seem strange that there is a cookie on `/mark/`? How do I remove that?

**Comment by niol** [comment]
Then, my guess is that the following happened:

1. You were logged in and using selfoss.
2. Your session expired or you cleared your cookies.
3. While you continued using selfoss, you marked an item read, which sent a `/mark/<itemid>` request, which created a new session as the old one was expired or deleted, which set a cookie in the `/mark` path. You got a `403 Forbidden` error.
4. You logged back in with a new session cookie with the `/` path, but the `/mark` was still there and does not contain a valid session. However, it gets used for all requests to `/mark` and below, and thus the bug you were experiencing.

My patch prevents this from happening again as all cookies use the app root path.

However, to get rid of your cookie in the `/mark` path, I would suggest navigating to `/mark/42` (random number). You should see both cookies (hopefully) and be able to clear them.

**Comment by tgrosinger** [comment]
That worked, both of the cookies were there and I could delete the `/mark/` one.
Thank you very much for your help with this strange issue.
