### ISSUE TITLE
Symbol "<" in tweet badly managed in twitter spout

### ISSUE THREAD

**Issue by severo** [SSilence/selfoss#825]
As far as I could investigate, the presence of a "<" symbol in a tweet AND of an embedded media (image, RT) implies that selfoss displays the link HTML code:

In twitter (https://twitter.com/pbeyssac/status/808353491697733633):

![View in twitter](https://cloud.githubusercontent.com/assets/1676121/21112697/135e7ea8-c07d-11e6-904c-894e02b245f6.png)

In selfoss (2.16):

![View in selfoss](https://cloud.githubusercontent.com/assets/1676121/21112653/f3d19e76-c07c-11e6-8574-41bedabc6f32.png)

**Comment by jtojnar** [comment]
Probably htmLawed interference. Possible fix:

```diff
diff --git a/spouts/twitter/usertimeline.php b/spouts/twitter/usertimeline.php
index 456fe47..02d38d1 100644
--- a/spouts/twitter/usertimeline.php
+++ b/spouts/twitter/usertimeline.php
@@ -326,6 +326,7 @@ class usertimeline extends \spouts\spout {
      * @param string $text unformated text
      */
     public function formatLinks($text) {
+        $text = htmlspecialchars($text);
         $text = preg_replace("/([\w-?&;#~=\.\/]+\@(\[?)[a-zA-Z0-9\-\.]+\.([a-zA-Z]{2,3}|[0-9]{1,3})(\]?))/i","<a href=\"mailto:$1\">$1</a>",$text);
         $text = str_replace("http://www.","www.",$text);
         $text = str_replace("www.","http://www.",$text);
```
