### ISSUE TITLE
problems with files /public/all-v*.{js,css}

### ISSUE THREAD

**Issue by hemathor** [SSilence/selfoss#827]
hey,

i use selfoss probably since version 2.4 (earliest zip file found in my archive).
i don't remember all the steps i did in the past to make selfoss work, so let's stay on my most recent update from 2.15 to 2.16.

although the update guide says to delete the aforementioned files, after each update selfoss fails with the 'an error occurred' message in the browser, and the apache log file says:

> [Mon Dec 19 12:44:06.788369 2016] [:error] [pid 8635] [client 10.1.1.1:12345] file_put_contents(/path/to/selfoss/public/all-v2.16.js): failed to open stream: Permission denied

and /data/logs/default.log also says:

> 12-19-16 12:44:06 Error file_put_contents(/path/to/selfoss/public/all-v2.16.js): failed to open stream: Permission denied

after copying the old files and rename them accordingly everything works fine.

what does this mean?

greetings...

**Comment by niol** [comment]
It means that you have skipped step 2 of the installation instructions:

> Make the directories data/cache, data/favicons, data/logs, data/thumbnails, data/sqlite and public/ writeable [by the user which your application server is running under]

**Comment by hemathor** [comment]
thanks!

i did step 2, but didn't read public/, so i missed that directory... now it works fine.

greetings...

**Comment by einufo** [comment]
Same issue can be cause by running Apache without the rewrite module enabled.
