### ISSUE TITLE
external links don't work anymore in 2.16

### ISSUE THREAD

**Issue by hemathor** [SSilence/selfoss#828]
hey,

after updating to version 2.16, i recognized that the external links (links to the article source) don't work any longer.
is there any change in the settings i have to be aware about?

until this is resolved, i return to 2.15.

greetings...

**Comment by niol** [comment]
This works for me. Maybe you are using outdated versions of js files which would be the case if working around your problem described in #827 by copying older files.

**Comment by hemathor** [comment]
no, these two issues don't seem to be related, because (thanks to your help) my other issue is fixed, but not this one.

greetings...

**Comment by hemathor** [comment]
ok, all is fine now, and has probably been before.

the link is now on a different place than it was before. i had to figure that out first...

greetings...

**Comment by alfredbuehler** [comment]
@hemathor Thanks for pointing this out. I had exactly the same problem.
