### ISSUE TITLE
all-v2.16.js missing but needed in templates

### ISSUE THREAD

**Issue by fschwind** [SSilence/selfoss#830]
After updating from 2.14 to 2.16 Selfoss stopped working with following error in the default.log

12-27-16 23:00:03 Error file_put_contents(/home/jester/public_html/selfoss/public/all-v2.16.js): failed to open stream: Permission denied

According to the update instructions this file should be deleted (and it is not included in the selfoss_2.16.zip). But it seems like there is a function getGlobalJsFileName() in helpers/View.php:128 which is used be several templates:

jester@server:~/public_html/selfoss$ grep -irsHn getGlobalJsFileName *
templates/login.phtml:66:    <script src="<?PHP echo \helpers\View::getGlobalJsFileName(); ?>"></script>
templates/home.phtml:167:    <script src="<?PHP echo \helpers\View::getGlobalJsFileName(); ?>"></script>
templates/opml.phtml:47:        <script src="<?PHP echo \helpers\View::getGlobalJsFileName(); ?>"></script> 

Not sure if this is a BUG or what I can do to get it working again... beside rolling back to 2.14.

**Comment by fschwind** [comment]
Just one further info.. the templates in 2.14 don't use this getGlobalJsFileName() function!

**Comment by niol** [comment]
I'll cut and paste what I said in #827 :

It means that you have skipped step 2 of the installation instructions:

> Make the directories data/cache, data/favicons, data/logs, data/thumbnails, data/sqlite and **public/** writeable [by the user which your application server is running under]

**Comment by fschwind** [comment]
Thanks for the quick reply and the tip with the writability. Now it works like a charm again! 

Do you think it would be a good idea to include this step in the update instructions? I missed it because I didn't read the installation instructions where it is described.

**Comment by niol** [comment]
You surely can suggest documentation improvements if you'd like to using github.

**Comment by einufo** [comment]
Simular issue can also be cause by not having the Apache module rewrite enabled.
