### ISSUE TITLE
Typo on homepage: "ngnix"

### ISSUE THREAD

**Issue by sometoby** [SSilence/selfoss#831]
I didn't see a repo for the project homepage at first glance. I apologize if this isn't the right place to report a typo. On the main page, under "Requirements", it says:

> Apache Webserver (ngnix and lighttpd also possible)

Which should probably be:

> Apache Webserver (_nginx_ and lighttpd also possible)

**Comment by bendem** [comment]
That would be https://github.com/SSilence/selfoss/blob/master/_docs/website/index.html#L97
