### ISSUE TITLE
Cannot display selfoss properly after activating https

### ISSUE THREAD

**Issue by pierrrrrrre** [SSilence/selfoss#873]
I'm using:
- Selfoss 2.16
- PHP 7.1
- a MySQL database

I recently forced the use of https on my server after using Let's Encrypt to get a valid SSL certificate.

Since then, I'm facing issues with Selfoss because when accessing it on `https://my.server.com/selfoss/`, it looks like it tries to load some files (`fonts.css`, `all-v2.16.css`, `all-v2.16.js`) using port 80 instead of the https port.

The Firefox devtools are telling me when accessing `https://my.server.com/selfoss/`, it then tries to download `https://my.server.com:80/selfoss/css/fonts.css` and the like.

On the same server, I still have an old version of selfoss (v2.9) and this one loads all the files without any issue.

Thanks in advance for your help, and thanks for that great app!

**Comment by jtojnar** [comment]
There are some problems with detecting the domain name. For now you should be able to fix it by setting `base_url` in config.ini.

**Comment by pierrrrrrre** [comment]
Thanks! I edited `base_url` (`base_url=https://my.server.com/selfoss/`) and now it works properly!
