### ISSUE TITLE
Use proper types in API

### ISSUE THREAD

**Issue by jtojnar** [SSilence/selfoss#879]
Booleans should be `true` or `false`, not `"0"` or `"1"`. Similarly, numbers should not be transmitted as strings. Tags should be returned as a list, not a string of comma separated names.

**Comment by niol** [comment]
Some work about this is available at https://github.com/niol/selfoss/tree/ppr/apitypes . As it seems what is wanted here is a major rework of how selfoss is driven from JS (like not returning HTML but lists for instance), I will stop there for now and let new features I want to work on drive those changes (using new endpoints).

Maybe a spec should be worked on before or some common RSS reader API be used instead.

**Comment by jtojnar** [comment]
I would not go as far as using JSON instead of HTML now. I meant the tags in `/items` endpoint used by applications.

In the future building the UI client-side from the same endpoints applications use could be possible – that is actually one of the points I investigate in álmafoss – I do not consider it to be in the scope of this issue, though.

I have sent you an invite to álmafoss private repo in case you are interested. It is still very rough draft and I will not have time to finish it until June.

**Comment by niol** [comment]
I fixed the tags in ```/items``` in my branch.
Thanks for the invite, but for now, I will use my free time for new features I want rather than rewriting the frontend and learning a new development environment.

**Comment by jtojnar** [comment]
Mostly fixed in https://github.com/SSilence/selfoss/pull/948
