### ISSUE TITLE
Give a way to disable same origin policy

### ISSUE THREAD

**Issue by DaMastah** [SSilence/selfoss#880]
Is there any way of disabling same origin policy for selfoss ? 
Can't use it with my muximux setup :(

**Comment by jtojnar** [comment]
If I understand it correctly, you need to change `X-Frame-Options` header. The easy way is adding the following into your config.ini:

```ini
XFRAME=ALLOW-FROM https://example.com/
```

[Relevant f3 code](https://github.com/bcosca/fatfree/blob/e9a8e914177603bf636831e633c22e7870a66c5e/lib/base.php#L1111)

**Comment by DaMastah** [comment]
Thanks for your answer !
Added the following line XFRAME="ALLOWALL" to my config.ini and all is now working fine
