### ISSUE TITLE
Nginx error 500

### ISSUE THREAD

**Issue by sh1omi** [SSilence/selfoss#890]
I use the nginx config from here: https://github.com/SSilence/selfoss/wiki/nginx-configuration
and I get this error:
```2017/03/14 15:58:23 [error] 27440#27440: *3 rewrite or internal redirection cycle while internally redirecting to "/selfoss/index.php", client: 10.0.0.4, server: XXX, request: "GET /selfoss/ HTTP/2.0", host: "10.0.0.10"```

part of my nginx config:
```
location ~ \.php$ {
	fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
	fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root/$fastcgi_script_name;
}

location /selfoss {
    location ~ ^/selfoss/((favicons|thumbnails)/.+)$ {
        try_files /selfoss/data/$1 =404;
    }
    location ~ ^/selfoss/$ {
        index index.php;
    }
    location ~ ^/selfoss/(.+)$ {
        try_files /selfoss/public/$1 /selfoss/index.php$is_args$args;
    }
}
```

**Comment by jtojnar** [comment]
Could you try copying the `location ~ \.php$` section to the `location /selfoss` section?

**Comment by sh1omi** [comment]
Thanks thats fixed it.
why does it need to be inside the selfoss section?

**Comment by jtojnar** [comment]
I do not really know much about nginx, wild speculation ahead: I guess that `location ~ \.php$` is ignored because `location /selfoss` is more specific and then `index.php` from `location ~ ^/selfoss/$` will trigger `location ~ ^/selfoss/(.+)$` and that will loop.
