### ISSUE TITLE
Mixed-content error in selfoss support forum (https://selfoss.aditu.de/forum/)

### ISSUE THREAD

**Issue by AlexMeier99** [SSilence/selfoss#893]
Hi,
i just tried to search the [https://selfoss.aditu.de/forum/](selfoss support forum), first i saw only raw text:
![error-mixed-content-selfoss-forum3](https://cloud.githubusercontent.com/assets/17048656/24054861/20f76e56-0b3e-11e7-9025-f36d75134689.png)
Then i checked the Firefox Console (I'm using Firefox 52.0):
![error-mixed-content-selfoss-forum](https://cloud.githubusercontent.com/assets/17048656/24054889/40a5fff6-0b3e-11e7-8bd1-69300192b762.PNG)
And searched for the two indicated errors:
[https://developer.mozilla.org/de/docs/Sicherheit/MixedContent?utm_campaign=default&utm_medium=firefox-console-errors&utm_source=mozilla](Mixed Content Error - MDN)
So after the solution is just modifing these four tag lines in head of the main forum file:
`<link` rel="stylesheet" type="text/css" **href="http**s**://selfoss.aditu.de/forum/themes/default/style.min.css"** media="all">
<link rel="shortcut icon" href="http**s**://selfoss.aditu.de/forum/themes/default/images/favicon.ico">
<script src="http**s**://selfoss.aditu.de/forum/index.php?mode=js_defaults&amp;t=1449511328" type="text/javascript" charset="utf-8"></script>
<script src="http**s**://selfoss.aditu.de/forum/js/main.min.js" type="text/javascript" charset="utf-8"><div></div></script>`
Just add a 's' after each 'http': done!
By the way: Why did you put a '<div>' inside the '<script>' tag?
So, it would be verry nice if someone of the selfoss community could verify and commit these Modifications to the master branch. I'm sorry but i don't manage to do it myself.

**Comment by SSilence** [comment]
I changed the config. Now always https is used.

Thanks for reporting!
