### ISSUE TITLE
cliupdate.php fails with Fatal error: Class 'Readability' not found

### ISSUE THREAD

**Issue by rwky** [SSilence/selfoss#896]
When running cliupdate.php from the 2.17 release downloaded from the releases page I get the following error:

```
Fatal error: Class 'Readability' not found
[libs/fulltextrss/content-extractor/ContentExtractor.php:203] 
an error occured: Fatal error: Class 'Readability' not found
```
Assuming that line 203 should be Readability\Readability changing it to that generates the following error
```
Fatal error: Call to undefined method Readability\Readability::removeScripts()
[libs/fulltextrss/content-extractor/ContentExtractor.php:697] 
an error occured: Fatal error: Call to undefined method Readability\Readability::removeScripts()
```
Removing that line allows cliupdate.php to run, however I've not dug into what removeScripts and Readability are supposed to do so I've no idea if that's a correct fix.

**Comment by jtojnar** [comment]
Closing as a duplicate.
