### ISSUE TITLE
Minimal php version is now at least 5.4

### ISSUE THREAD

**Issue by mkyral** [SSilence/selfoss#899]
Webpage says:

> PHP 5.3 or higher with the php-gd and php-http extensions enabled

But after commit 1105a4f4a604b9e978e687401ee1df96984865ab it should be at least 5.4.
( according to http://php.net/manual/en/language.types.array.php )

```php
// as of PHP 5.4
$array = [
    "foo" => "bar",
    "bar" => "foo",
];
```

**Comment by jtojnar** [comment]
Thanks for reporting, 5.4 was actually required for a while now but we forgot to update the documentation.
