### ISSUE TITLE
Back button from Android Chrome not working

### ISSUE THREAD

**Issue by gerundt** [SSilence/selfoss#900]
Since Version 2.17 the _Back_ button from **Android Chrome** not working like before.

In the past he jump back to the overview if I opened a entry. Now he only jumps to the top of the entry page (if you scrolled down).

I like the old way more. ;)

**Comment by gerundt** [comment]
Mhh, I replace the `selfoss-events.js` file with your version, delete the `all-v*.js` file and reload the page on Android Chrome, but he still jumps only to the top of the page.

**Comment by niol** [comment]
I think you're not using the latest js. Please disable your browser's cache in your browser's developer tools or clear your browser's cache.

**Comment by gerundt** [comment]
Yes, you are right! I open an _Incognito_ tab and here it works like a charm. Thank you very much! :)
