### ISSUE TITLE
Adding more content

### ISSUE THREAD

**Issue by GeoZzNL** [SSilence/selfoss#901]
Hi guys,

I am trying to add my favorite news feed like NU.nl en AD.nl.... For some reason i only see the title, short description, date, author, link, picture (When synced). But the full content isnt showing up.

How can i intergrate this text?

Website rss ex.: www.nu.nl/rss/algemeen

I hope you know something, thank yyou

**Comment by jtojnar** [comment]
Both sites only contain short description in the feed. You will need to use the “RSS (with Full-Text-RSS)” spout. Unfortunately, the spout is broken in selfoss 2.17 so you will need [development version with a fix](https://github.com/SSilence/selfoss/issues/895#issuecomment-287515602).

**Comment by GeoZzNL** [comment]
Okay, thanks! It works
