### ISSUE TITLE
Content not loading on latest version

### ISSUE THREAD

**Issue by uncovery** [SSilence/selfoss#902]
I have recently upgraded to the latest release. Since then I frequently get an empty feed list that says "No items loaded, reload?". Reloading sometimes fixes the issue, sometimes I need to shift-reload the whole page. Eventually the content would pop back up.

**Comment by niol** [comment]
Do you have some errors in your browser's developpers console?

**Comment by uncovery** [comment]
No, there is nothing. 
From what I can say, it's almost 100% reproducible that an initial opening of the site returns an empty list. Only when I reload several times with clicking on the reload button on the bottom left or on the "no items loaded" or CTRL-reload the page, the contents will show up.

There is also nothing in the /data/logs file

**Comment by niol** [comment]
I think you're not using the latest js. Please disable your browser's cache in your browser's developer tools or clear your browser's cache.

**Comment by uncovery** [comment]
I think I have the right JS. I also cleared the cache again, still the same issue. Is there a way to check if I have the right version?

**Comment by jtojnar** [comment]
What version do you see in the sidebar? Could you try removing `all*.js` file in the public directory before force-refresh?

**Comment by uncovery** [comment]
I see version selfoss 2.17-SNAPSHOT in the sidebar.
I removed the .js file, cleared the cache. Same issue.

**Comment by niol** [comment]
Do you have access to you webserver logs? Can you provide the logs when it fails?

Can you provide a screenshot of the network tab of you browser developer tools when loading fails?

If you visit ```http://example.net/selfoss/?offset=0&itemsPerPage=25&search=&type=unread=&sourcesNav=false&ajax=true``` , does it always return something like starting like ```{"lastUpdate":"2017-03-23T15:17:45+01:00","hasMore":1```?

**Comment by uncovery** [comment]
{"lastUpdate":"2017-03-23T15:01:06+08:00", is from the URL,  about 7 minutes ago

This is the screenshot http://imgur.com/a/0LBkL

There is no relevant error in the log (only favicon not found etc)

This is a sample server access log:

 ```
- - [23/Mar/2017:22:55:51 +0800] "GET /selfoss/items/sync?since=2017-03-23T06%3A30%3A18.000Z&tags=true&sources=false&items_statuses=true HTTP/1.1" 200 43
 - - [23/Mar/2017:23:01:51 +0800] "GET /selfoss/items/sync?since=2017-03-23T06%3A30%3A18.000Z&tags=true&sources=false&items_statuses=true HTTP/1.1" 200 1825
 - - [23/Mar/2017:23:05:00 +0800] "GET /selfoss/ HTTP/1.1" 200 6253
 - - [23/Mar/2017:23:05:12 +0800] "GET /selfoss/ HTTP/1.1" 200 6253
 - - [23/Mar/2017:23:05:13 +0800] "GET /selfoss/css/fonts.css HTTP/1.1" 304 -
 - - [23/Mar/2017:23:05:13 +0800] "GET /selfoss/all-v2.17-SNAPSHOT.css HTTP/1.1" 304 -
 - - [23/Mar/2017:23:05:13 +0800] "GET /selfoss/all-v2.17-SNAPSHOT.js HTTP/1.1" 304 -
 - - [23/Mar/2017:23:05:14 +0800] "GET /selfoss/images/remove.png HTTP/1.1" 304 -
 - - [23/Mar/2017:23:05:14 +0800] "GET /selfoss/images/search.png HTTP/1.1" 304 -
 - - [23/Mar/2017:23:05:14 +0800] "GET /selfoss/images/nav-expanded.png HTTP/1.1" 304 -
 - - [23/Mar/2017:23:05:14 +0800] "GET /selfoss/images/bg.gif HTTP/1.1" 304 -
 - - [23/Mar/2017:23:05:14 +0800] "GET /selfoss/images/nav-collapsed.png HTTP/1.1" 304 -
 - - [23/Mar/2017:23:05:14 +0800] "GET /selfoss/images/logo.png HTTP/1.1" 304 -
 - - [23/Mar/2017:23:05:14 +0800] "GET /selfoss/images/nav-refresh.png HTTP/1.1" 304 -
 - - [23/Mar/2017:23:05:15 +0800] "GET /selfoss/images/nav-sources.png HTTP/1.1" 304 -
 - - [23/Mar/2017:23:05:15 +0800] "GET /selfoss/images/nav-logout.png HTTP/1.1" 304 -
 - - [23/Mar/2017:23:05:15 +0800] "GET /selfoss/images/ajax-loader-big.gif HTTP/1.1" 304 -
 - - [23/Mar/2017:23:08:24 +0800] "GET /selfoss?offset=0&itemsPerPage=25&search=&type=unread=&sourcesNav=false&ajax=true HTTP/1.1" 301 415
 - - [23/Mar/2017:23:05:12 +0800] "GET /selfoss/ HTTP/1.1" 200 6253
 - - [23/Mar/2017:23:05:13 +0800] "GET /selfoss/css/fonts.css HTTP/1.1" 304 -
 - - [23/Mar/2017:23:05:13 +0800] "GET /selfoss/all-v2.17-SNAPSHOT.css HTTP/1.1" 304 -
 - - [23/Mar/2017:23:05:13 +0800] "GET /selfoss/all-v2.17-SNAPSHOT.js HTTP/1.1" 304 -
 - - [23/Mar/2017:23:05:14 +0800] "GET /selfoss/images/remove.png HTTP/1.1" 304 -
 - - [23/Mar/2017:23:05:14 +0800] "GET /selfoss/images/search.png HTTP/1.1" 304 -
 - - [23/Mar/2017:23:05:14 +0800] "GET /selfoss/images/nav-expanded.png HTTP/1.1" 304 -
 - - [23/Mar/2017:23:05:14 +0800] "GET /selfoss/images/bg.gif HTTP/1.1" 304 -
 - - [23/Mar/2017:23:05:14 +0800] "GET /selfoss/images/nav-collapsed.png HTTP/1.1" 304 -
 - - [23/Mar/2017:23:05:14 +0800] "GET /selfoss/images/logo.png HTTP/1.1" 304 -
 - - [23/Mar/2017:23:05:14 +0800] "GET /selfoss/images/nav-refresh.png HTTP/1.1" 304 -
 - - [23/Mar/2017:23:05:15 +0800] "GET /selfoss/images/nav-sources.png HTTP/1.1" 304 -
 - - [23/Mar/2017:23:05:15 +0800] "GET /selfoss/images/nav-logout.png HTTP/1.1" 304 -
 - - [23/Mar/2017:23:05:15 +0800] "GET /selfoss/images/ajax-loader-big.gif HTTP/1.1" 304 -
 - - [23/Mar/2017:23:08:24 +0800] "GET /selfoss?offset=0&itemsPerPage=25&search=&type=unread=&sourcesNav=false&ajax=true HTTP/1.1" 301 415
```

**Comment by niol** [comment]
The status code for the last request is 301, and AJAX calls do not follow redirects it seems. This is because there's a missing trailing slash before the query string (before the ```?```): it should be ```GET /selfoss/?offset=0&itemsPerPag...```.

This url comes from ```base_url``` in the config but from looking at the code, a trailing slash should be added. If it is not set in the config, a trailing slash should also be added in the auto-detection code.

Can you view source on the selfoss main page and tell us what is in line 4? It should read something like the following with the trailing slash:
```<base href="https://example.net/selfoss/" />```

Why it works sometimes is perhaps that the 301 is somehow cached by the browser.

**Comment by jtojnar** [comment]
It is weird that the last access in the log misses `offset_from_datetime` and `offset_from_id` parameters – unless it is a manually visited URL.

**Comment by uncovery** [comment]
Line number 4 is 
`<base href="https://spiesshofer.com/selfoss/" />`

I found that one of the tags I have reliably returns an 'empty page' (i,e. the question if I want to reload) each time I click on it, even if the main page shows content and content for that tab.

**Comment by niol** [comment]
Again, I need the exact request ```GET /selfoss/?```... and the associated http status codes. If you could open that url in a new browser tab and tell us what you find there, it would be great.

The name of the failing tag would also be valuable if it has special characters (i.e. non-ASCII).

Also, you could set ```$f3->set('DEBUG', 1);``` in ```common.php``` and set ```log_level=DEBUG``` in your config file and tell us what you can find in the log.

**Comment by uncovery** [comment]
The tag is just "Company".
Here is the logfile after the changes in the file:

`[2017-03-24 17:02:45] selfoss.DEBUG: set cookie on domain.com/selfoss/ expiring in 2592000 seconds..
[2017-03-24 17:02:45] selfoss.DEBUG: logged in using valid session..
[2017-03-24 17:02:49] selfoss.DEBUG: set cookie on domain.com/selfoss/ expiring in 2592000 seconds..
[2017-03-24 17:02:49] selfoss.DEBUG: logged in using valid session..
[2017-03-24 17:02:49] selfoss.DEBUG: Establish database connection.`

the URL returns a LOT of content and reliably full contents.  looks more or less like this every time:

`{"lastUpdate":"2017-03-24T09:16:01+08:00","hasMore":1,"entries":"<div id=\"entry70147\"\n     data-entry-id=\"70147\"\n     data-entry-source=\"45\"\n     data-entry-datetime=\"2017-03-24T17:15:55+08:00\"\n     class=\"entry unread\" role=\"article\">\n\n    <!-- icon -->\n    <a href=\"http:\/\/www.tagesschau.de\/ausland\/london-festnahmen-101.html\" class=\"entry-icon\" tabindex=\"-1\">\n` [20 more pages cropped]

**Comment by niol** [comment]
And the status code of the XHR HTTP request is always 200 in the developer tools of the browser?

**Comment by uncovery** [comment]
yes, seems like that URL is reliably 200 but the website still shows the reload prompt often. 

I cannot put my finger on it when it's showing contents and when not except for that one tag.

**Comment by niol** [comment]
Is the URL 200 in the browser developer tools when it shows the prompt?
Also, the reload prompt is only shown together with a failure message at the top of the page with a red background starting with 
> Load list error:

and followed by a reason. If this error message does not show, please ensure that your CSS has been regenerated and loaded by your browser: remove ```public/all-v2.17-SNAPSHOT.css``` and clear your browser's cache for the selfoss installation.

**Comment by uncovery** [comment]
Yeah the CSS seems to have fixed it, thanks!

**Comment by uncovery** [comment]
So I need to re-open this issue. Everything worked fine over the weekend on my home PC.
Now I have gone back to work now and opened SelfOSS there at my office computer. It turns out that there I again had the same issue. So I deleted the cache, the cookies and so on and could not get contents. Then I opened that URL you mentioned and that worked fine. Then I went into the sources manager and it showed me the sources. In the network display, the CSS and JS files showed with status 200. 

But the content would still not load. Then I went on the server and removed the all-v2.17-SNAPSHOT.css and the all-v2.17-SNAPSHOT.js and suddenly everything popped back up, all fine.

Then I wanted to test and connected via teamviewer to my PC at home and tried to open SelfOSS there. And guess what? It's broken again. So I deleted the SNAPSHOT files again and reloaded on both PCs and it seems to work on both sides. 

If you think this is a non-issue, please let me know and close this, otherwise I'd be happy to help you debug this.

**Comment by uncovery** [comment]
Had the same issue again. switched to FreshRSS now, thanks for the help but it seems there is maybe an issue with my browser setup or something similar.
