### ISSUE TITLE
Feed items added multiple times

### ISSUE THREAD

**Issue by aminecmi** [SSilence/selfoss#905]
The items of [this feed](https://blog.google/rss/) are added multiple times. They are at least added twice, and this can go up to five times.

The items are added to the database, and appear multiple times on the app.

**Comment by niol** [comment]
Can you spot something different between the rows in the database referring to the same entry in the feed? (selfoss only compares the ```uid``` to check whether an item is already in the database).

**Comment by aminecmi** [comment]
Here is an SQL export of an article appearing multiple times.

`
INSERT INTO `items` (`id`, `datetime`, `title`, `content`, `thumbnail`, `icon`, `unread`, `starred`, `source`, `uid`, `link`, `updatetime`, `author`, `shared`) VALUES
(14613, '2017-03-22 13:00:00', 'Diverse protections for a diverse ecosystem: Android Security 2016 Year in Review', '<div><div><p>Today, we&rsquo;re sharing the third annual Android Security Year In Review, a comprehensive look at our work to protect more than 1.4 billion Android users and their data.</p><p>Our goal is simple: keep our users safe. In 2016, we improved our abilities to stop dangerous apps, built new security features into Android 7.0 Nougat, and collaborated with device manufacturers, researchers, and other members of the Android ecosystem. For more details, you can read the <a href="https://static.googleusercontent.com/media/source.android.com/en//security/reports/Google_Android_Security_2016_Report_Final.pdf">full Year in Review report</a> or <a href="https://youtu.be/kNRS6FAsagg">watch our webinar</a>.</p></div></div>\n<div>\n\n<div>\n    <div>\n        <div></div>\n        \n            \n                <img src="https://img.youtube.com/vi/kNRS6FAsagg/maxresdefault.jpg" alt="Android Security: 2016 Year in Review" /><div></div>\n\n            \n        \n    </div>\n    \n</div>\n</div>\n<div><div><h3>Protecting you from PHAs</h3><p>It&rsquo;s critical to keep people safe from&nbsp;<a href="https://blog.google/topics/safety-security/shielding-you-potentially-harmful-applications/">Potentially Harmful Apps</a>&nbsp;(PHAs) that may put their data or devices at risk. Our ongoing work in this area requires us to find ways to track and stop existing PHAs, and anticipate new ones that haven&rsquo;t even emerged yet.</p></div></div>\n<div><div>\n    <img src="https://storage.googleapis.com/gweb-uniblog-publish-prod/images/SecurityInfographic_Stat3_506x253.width-506.png" alt="PHA protections Android 2016" /></div>\n</div>\n<div><div><p>Over the years, we&rsquo;ve built a variety of systems to address these threats, such as application analyzers that constantly review apps for unsafe behavior, and Verify Apps which regularly checks users&rsquo; devices for PHAs. When these systems detect PHAs, we warn users, suggest they think twice about downloading a particular app, or even remove the app from their devices entirely.</p><p>We constantly monitor threats and improve our systems over time. Last year&rsquo;s data reflected those improvements: Verify Apps conducted 750 million daily checks in 2016, up from 450 million the previous year, enabling us to reduce the PHA installation rate in the top 50 countries for Android usage.</p><p>Google Play continues to be the safest place for Android users to download their apps. Installs of PHAs from Google Play decreased in nearly every category:<br /></p><ul><li>Now 0.016 percent of installs, trojans dropped by 51.5 percent compared to 2015<br /></li><li>Now 0.003 percent of installs, hostile downloaders dropped by 54.6 percent compared to 2015<br /></li><li>Now 0.003 percent of installs, backdoors dropped by 30.5 percent compared to 2015<br /></li><li>Now 0.0018 percent of installs, phishing apps dropped by 73.4 percent compared to 2015<br /></li></ul><p>By the end of 2016, only 0.05 percent of devices that downloaded apps exclusively from Play contained a PHA; down from 0.15 percent in 2015.</p><p>Still, there&rsquo;s more work to do for devices overall, especially those that install apps from multiple sources. While only 0.71 percent of all Android devices had PHAs installed at the end of 2016, that was a slight increase from about 0.5 percent in the beginning of 2015. Using improved tools and the knowledge we gained in 2016, we think we can reduce the number of devices affected by PHAs in 2017, no matter where people get their apps.</p></div></div>\n<div><div><h3>Working together to secure the Android ecosystem</h3></div></div>\n<div><div>\n    <img src="https://storage.googleapis.com/gweb-uniblog-publish-prod/images/SecurityInfographic_Stat4_506x253.width-506.png" alt="Android security updates in 2016" /></div>\n</div>\n<div><div><p>Sharing information about security threats between Google, device manufacturers, the research community, and others helps keep all Android users safer. In 2016, our biggest collaborations were via our monthly security updates program and ongoing partnership with the security research community.</p><p>Security updates are regularly highlighted as a pillar of mobile security&mdash;and rightly so. We <a href="https://android.googleblog.com/2015/08/an-update-to-nexus-devices.html">launched our monthly security updates program</a> in 2015, following the public disclosure of a bug in Stagefright, to help accelerate patching security vulnerabilities across devices from many different device makers. This program expanded significantly in 2016:</p><ul><li>More than 735 million devices from 200+ manufacturers received a platform security update in 2016.<br /></li><li>We released monthly Android security updates throughout the year for devices running Android 4.4.4 and up&mdash;that accounts for 86.3 percent of all active Android devices worldwide.<br /></li><li>Our carrier and hardware partners helped expand deployment of these updates, releasing updates for over half of the top 50 devices worldwide in the last quarter of 2016.<br /></li></ul><p>We provided monthly security updates for all supported Pixel and Nexus devices throughout 2016, and we&rsquo;re thrilled to see our partners invest significantly in regular updates as well. There&rsquo;s still a lot of room for improvement however. About half of devices in use at the end of 2016 had not received a platform security update in the previous year. We&rsquo;re working to increase device security updates by streamlining our security update program to make it easier for manufacturers to deploy security patches and releasing <a href="https://source.android.com/devices/tech/ota/ab_updates.html">A/B updates</a> to make it easier for users to apply those patches.</p><p>On the research side, our Android Security Rewards program grew rapidly: we <a href="https://security.googleblog.com/2017/01/vulnerability-rewards-program-2016-year.html">paid researchers nearly $1 million dollars</a> for their reports in 2016. In parallel, we worked closely with various security firms to identify and quickly fix issues that may have posed risks to our users.</p><p>We appreciate all of the hard work by Android partners, external researchers, and teams at Google that led to the progress the ecosystem has made with security in 2016. But it doesn&rsquo;t stop there. Keeping users safe requires constant vigilance and effort. We&rsquo;re looking forward to new insights and progress in 2017 and beyond.</p></div></div>', '341126775f6460fbec54865619680a27.jpg', '559c2da4927324576b4ec4c1e224eafb.png', 0, 0, 9, 'https://blog.google/topics/connected-workspaces/diverse-protections-diverse-ecosystem-android-security-2016-year-review/', 'https://blog.google/topics/connected-workspaces/diverse-protections-diverse-ecosystem-android-security-2016-year-review/', '2017-03-23 01:36:45', '', NULL),
(14542, '2017-03-22 12:30:30', 'Diverse protections for a diverse ecosystem: Android Security 2016 Year in Review', '<div><div><p>Today, we&rsquo;re sharing the third annual Android Security Year In Review, a comprehensive look at our work to protect more than 1.4 billion Android users and their data.</p><p>Our goal is simple: keep our users safe. In 2016, we improved our abilities to stop dangerous apps, built new security features into Android 7.0 Nougat, and collaborated with device manufacturers, researchers, and other members of the Android ecosystem. For more details, you can read the <a href="https://static.googleusercontent.com/media/source.android.com/en//security/reports/Google_Android_Security_2016_Report_Final.pdf">full Year in Review report</a> or <a href="https://youtu.be/kNRS6FAsagg">watch our webinar</a>.</p><h3>Protecting you from PHAs</h3><p>It&rsquo;s critical to keep people safe from&nbsp;<a href="https://blog.google/topics/safety-security/shielding-you-potentially-harmful-applications/">Potentially Harmful Apps</a>&nbsp;(PHAs) that may put their data or devices at risk. Our ongoing work in this area requires us to find ways to track and stop existing PHAs, and anticipate new ones that haven&rsquo;t even emerged yet.</p></div></div>\n<div><div>\n    <img src="https://storage.googleapis.com/gweb-uniblog-publish-prod/images/SecurityInfographic_Stat3_506x253.width-506.png" alt="PHA protections Android 2016" /></div>\n</div>\n<div><div><p>Over the years, we&rsquo;ve built a variety of systems to address these threats, such as application analyzers that constantly review apps for unsafe behavior, and Verify Apps which regularly checks users&rsquo; devices for PHAs. When these systems detect PHAs, we warn users, suggest they think twice about downloading a particular app, or even remove the app from their devices entirely.</p><p>We constantly monitor threats and improve our systems over time. Last year&rsquo;s data reflected those improvements: Verify Apps conducted 750 million daily checks in 2016, up from 450 million the previous year, enabling us to reduce the PHA installation rate in the top 50 countries for Android usage.</p><p>Google Play continues to be the safest place for Android users to download their apps. Installs of PHAs from Google Play decreased in nearly every category:<br /></p><ul><li>Now 0.016 percent of installs, trojans dropped by 51.5 percent compared to 2015<br /></li><li>Now 0.003 percent of installs, hostile downloaders dropped by 54.6 percent compared to 2015<br /></li><li>Now 0.003 percent of installs, backdoors dropped by 30.5 percent compared to 2015<br /></li><li>Now 0.0018 percent of installs, phishing apps dropped by 73.4 percent compared to 2015<br /></li></ul><p>By the end of 2016, only 0.05 percent of devices that downloaded apps exclusively from Play contained a PHA; down from 0.15 percent in 2015.</p><p>Still, there&rsquo;s more work to do for devices overall, especially those that install apps from multiple sources. While only 0.71 percent of all Android devices had PHAs installed at the end of 2016, that was a slight increase from about 0.5 percent in the beginning of 2015. Using improved tools and the knowledge we gained in 2016, we think we can reduce the number of devices affected by PHAs in 2017, no matter where people get their apps.</p></div></div>\n<div><div><h3>Working together to secure the Android ecosystem</h3></div></div>\n<div><div>\n    <img src="https://storage.googleapis.com/gweb-uniblog-publish-prod/images/SecurityInfographic_Stat4_506x253.width-506.png" alt="Android security updates in 2016" /></div>\n</div>\n<div><div><p>Sharing information about security threats between Google, device manufacturers, the research community, and others helps keep all Android users safer. In 2016, our biggest collaborations were via our monthly security updates program and ongoing partnership with the security research community.</p><p>Security updates are regularly highlighted as a pillar of mobile security&mdash;and rightly so. We <a href="https://android.googleblog.com/2015/08/an-update-to-nexus-devices.html">launched our monthly security updates program</a> in 2015, following the public disclosure of a bug in Stagefright, to help accelerate patching security vulnerabilities across devices from many different device makers. This program expanded significantly in 2016:</p><ul><li>More than 735 million devices from 200+ manufacturers received a platform security update in 2016.<br /></li><li>We released monthly Android security updates throughout the year for devices running Android 4.4.4 and up&mdash;that accounts for 86.3 percent of all active Android devices worldwide.<br /></li><li>Our carrier and hardware partners helped expand deployment of these updates, releasing updates for over half of the top 50 devices worldwide in the last quarter of 2016.<br /></li></ul><p>We provided monthly security updates for all supported Pixel and Nexus devices throughout 2016, and we&rsquo;re thrilled to see our partners invest significantly in regular updates as well. There&rsquo;s still a lot of room for improvement however. About half of devices in use at the end of 2016 had not received a platform security update in the previous year. We&rsquo;re working to increase device security updates by streamlining our security update program to make it easier for manufacturers to deploy security patches and releasing <a href="https://source.android.com/devices/tech/ota/ab_updates.html">A/B updates</a> to make it easier for users to apply those patches.</p><p>On the research side, our Android Security Rewards program grew rapidly: we <a href="https://security.googleblog.com/2017/01/vulnerability-rewards-program-2016-year.html">paid researchers nearly $1 million dollars</a> for their reports in 2016. In parallel, we worked closely with various security firms to identify and quickly fix issues that may have posed risks to our users.</p><p>We appreciate all of the hard work by Android partners, external researchers, and teams at Google that led to the progress the ecosystem has made with security in 2016. But it doesn&rsquo;t stop there. Keeping users safe requires constant vigilance and effort. We&rsquo;re looking forward to new insights and progress in 2017 and beyond.</p></div></div>', '341126775f6460fbec54865619680a27.jpg', 'b343be5e289fdf7feea056bde686577e.png', 0, 0, 9, 'http://www.blog.google:443/topics/connected-workspaces/diverse-protections-diverse-ecosystem-android-security-2016-year-review/', 'http://www.blog.google:443/topics/connected-workspaces/diverse-protections-diverse-ecosystem-android-security-2016-year-review/', '2017-03-22 13:04:46', '', NULL),
(14516, '2017-03-22 10:30:28', 'Diverse protections for a diverse ecosystem: Android Security 2016 Year in Review', '<div><div><p>Today, we&rsquo;re sharing the third annual Android Security Year In Review, a comprehensive look at our work to protect more than 1.4 billion Android users and their data.</p><p>Our goal is simple: keep our users safe. In 2016, we improved our abilities to stop dangerous apps, built new security features into Android 7.0 Nougat, and collaborated with device manufacturers, researchers, and other members of the Android ecosystem. For more details, you can read the <a href="https://static.googleusercontent.com/media/source.android.com/en//security/reports/Google_Android_Security_2016_Report_Final.pdf">full Year in Review report</a> or <a href="https://youtu.be/kNRS6FAsagg">watch our webinar</a>.</p><h3>Protecting you from PHAs</h3><p>It&rsquo;s critical to keep people safe from&nbsp;<a href="https://blog.google/topics/safety-security/shielding-you-potentially-harmful-applications/">Potentially Harmful Apps</a>&nbsp;(PHAs) that may put their data or devices at risk. Our ongoing work in this area requires us to find ways to track and stop existing PHAs, and anticipate new ones that haven&rsquo;t even emerged yet.</p></div></div>\n<div><div>\n    <img src="https://storage.googleapis.com/gweb-uniblog-publish-prod/images/SecurityInfographic_Stat3_506x253.width-506.png" alt="PHA protections Android 2016" /></div>\n</div>\n<div><div><p>Over the years, we&rsquo;ve built a variety of systems to address these threats, such as application analyzers that constantly review apps for unsafe behavior, and Verify Apps which regularly checks users&rsquo; devices for PHAs. When these systems detect PHAs, we warn users, suggest they think twice about downloading a particular app, or even remove the app from their devices entirely.</p><p>We constantly monitor threats and improve our systems over time. Last year&rsquo;s data reflected those improvements: Verify Apps conducted 750 million daily checks in 2016, up from 450 million the previous year, enabling us to reduce the PHA installation rate in the top 50 countries for Android usage.</p><p>Google Play continues to be the safest place for Android users to download their apps. Installs of PHAs from Google Play decreased in nearly every category:<br /></p><ul><li>Now 0.016 percent of installs, trojans dropped by 51.5 percent compared to 2015<br /></li><li>Now 0.003 percent of installs, hostile downloaders dropped by 54.6 percent compared to 2015<br /></li><li>Now 0.003 percent of installs, backdoors dropped by 30.5 percent compared to 2015<br /></li><li>Now 0.0018 percent of installs, phishing apps dropped by 73.4 percent compared to 2015<br /></li></ul><p>By the end of 2016, only 0.05 percent of devices that downloaded apps exclusively from Play contained a PHA; down from 0.15 percent in 2015.</p><p>Still, there&rsquo;s more work to do for devices overall, especially those that install apps from multiple sources. While only 0.71 percent of all Android devices had PHAs installed at the end of 2016, that was a slight increase from about 0.5 percent in the beginning of 2015. Using improved tools and the knowledge we gained in 2016, we think we can reduce the number of devices affected by PHAs in 2017, no matter where people get their apps.</p></div></div>\n<div><div><h3>Working together to secure the Android ecosystem</h3></div></div>\n<div><div>\n    <img src="https://storage.googleapis.com/gweb-uniblog-publish-prod/images/SecurityInfographic_Stat4_506x253.width-506.png" alt="Android security updates in 2016" /></div>\n</div>\n<div><div><p>Sharing information about security threats between Google, device manufacturers, the research community, and others helps keep all Android users safer. In 2016, our biggest collaborations were via our monthly security updates program and ongoing partnership with the security research community.</p><p>Security updates are regularly highlighted as a pillar of mobile security&mdash;and rightly so. We <a href="https://android.googleblog.com/2015/08/an-update-to-nexus-devices.html">launched our monthly security updates program</a> in 2015, following the public disclosure of a bug in Stagefright, to help accelerate patching security vulnerabilities across devices from many different device makers. This program expanded significantly in 2016:</p><ul><li>More than 735 million devices from 200+ manufacturers received a platform security update in 2016.<br /></li><li>We released monthly Android security updates throughout the year for devices running Android 4.4.4 and up&mdash;that accounts for 86.3 percent of all active Android devices worldwide.<br /></li><li>Our carrier and hardware partners helped expand deployment of these updates, releasing updates for over half of the top 50 devices worldwide in the last quarter of 2016.<br /></li></ul><p>We provided monthly security updates for all supported Pixel and Nexus devices throughout 2016, and we&rsquo;re thrilled to see our partners invest significantly in regular updates as well. There&rsquo;s still a lot of room for improvement however. About half of devices in use at the end of 2016 had not received a platform security update in the previous year. We&rsquo;re working to increase device security updates by streamlining our security update program to make it easier for manufacturers to deploy security patches and releasing <a href="https://source.android.com/devices/tech/ota/ab_updates.html">A/B updates</a> to make it easier for users to apply those patches.</p><p>On the research side, our Android Security Rewards program grew rapidly: we <a href="https://security.googleblog.com/2017/01/vulnerability-rewards-program-2016-year.html">paid researchers nearly $1 million dollars</a> for their reports in 2016. In parallel, we worked closely with various security firms to identify and quickly fix issues that may have posed risks to our users.</p><p>We appreciate all of the hard work by Android partners, external researchers, and teams at Google that led to the progress the ecosystem has made with security in 2016. But it doesn&rsquo;t stop there. Keeping users safe requires constant vigilance and effort. We&rsquo;re looking forward to new insights and progress in 2017 and beyond.</p></div></div>', '341126775f6460fbec54865619680a27.jpg', '6f9025fd46c38652938aefd771b03d42.png', 0, 0, 9, 'http://blog.google:443/topics/connected-workspaces/diverse-protections-diverse-ecosystem-android-security-2016-year-review/', 'http://blog.google:443/topics/connected-workspaces/diverse-protections-diverse-ecosystem-android-security-2016-year-review/', '2017-03-22 12:28:38', '', NULL);
`

**Comment by niol** [comment]
As said, selfoss compares the ```uid```. This particular item has probably seen its ```uid``` change with the following values:
- ```https://blog.google/topics/connected-workspaces/diverse-protections-diverse-ecosystem-android-security-2016-year-review/```
- ```http://www.blog.google:443/topics/connected-workspaces/diverse-protections-diverse-ecosystem-android-security-2016-year-review/```
- ```http://blog.google:443/topics/connected-workspaces/diverse-protections-diverse-ecosystem-android-security-2016-year-review/```

From what selfoss is seeing, this is a different entry. There's no obvious way to fix this.

**Comment by jtojnar** [comment]
It should probably be reported to Google.

**Comment by aminecmi** [comment]
Reported that on twitter, but no answer. I'll try another way.

Thanks anyway.
