### ISSUE TITLE
Title is empty

### ISSUE THREAD

**Issue by dlicois** [SSilence/selfoss#911]
Hello,

Some rss feed entries containing valid utf-8 characters end up having no title.
Here's a sample: https://www.nextinpact.com/rss/news.xml (entries starting with the 🔓 char). In mysql, the title is empty.

I set a default title when title is empty in item.phtml to play around it, but updater shouldn't handle utf-8 properly?

**Comment by niol** [comment]
World well with pgsql, so this is a db engine issue. I'll look into it.

**Comment by jtojnar** [comment]
This looks like you use “utf8” charset in your database. MySQL only supports full UTF-8 with “utf8mb4”. Not sure why your server was not updated, though.

**Comment by dlicois** [comment]
mysql items table:

+------------+--------------+------+-----+---------+----------------+
| Field      | Type         | Null | Key | Default | Extra          |
+------------+--------------+------+-----+---------+----------------+
| id         | int(11)      | NO   | PRI | NULL    | auto_increment |
| datetime   | datetime     | NO   |     | NULL    |                |
| title      | mediumtext   | NO   |     | NULL    |                |
| content    | longtext     | NO   |     | NULL    |                |
| thumbnail  | mediumtext   | YES  |     | NULL    |                |
| icon       | mediumtext   | YES  |     | NULL    |                |
| unread     | tinyint(1)   | NO   |     | NULL    |                |
| starred    | tinyint(1)   | NO   |     | NULL    |                |
| source     | int(11)      | NO   | MUL | NULL    |                |
| uid        | varchar(255) | NO   |     | NULL    |                |
| link       | mediumtext   | NO   |     | NULL    |                |
| updatetime | datetime     | YES  |     | NULL    |                |
| author     | varchar(255) | YES  |     | NULL    |                |
| shared     | tinyint(1)   | YES  |     | NULL    |                |
+------------+--------------+------+-----+---------+----------------+

SHOW VARIABLES WHERE Variable_name LIKE 'character\_set\_%' OR Variable_name LIKE 'collation%';

+--------------------------+-------------------+
| Variable_name            | Value             |
+--------------------------+-------------------+
| character_set_client     | utf8              |
| character_set_connection | utf8              |
| character_set_database   | latin1            |
| character_set_filesystem | binary            |
| character_set_results    | utf8              |
| character_set_server     | latin1            |
| character_set_system     | utf8              |
| collation_connection     | utf8_general_ci   |
| collation_database       | latin1_swedish_ci |
| collation_server         | latin1_swedish_ci |
+--------------------------+-------------------+


so no utf8mb4 indeed, I'll try this https://mathiasbynens.be/notes/mysql-utf8mb4#utf8-to-utf8mb4

**Comment by jtojnar** [comment]
We have [an upgrade script](https://github.com/SSilence/selfoss/blob/8219b63a6e21acc0bf7562dc1132c28bc9000306/daos/mysql/Database.php#L198-L204) that should do the work. What do you have in the `version` table?

**Comment by dlicois** [comment]
select * from version;

+---------+
| version |
+---------+
|       3 |
|       4 |
|       5 |
|       6 |
|       8 |
|       9 |
|      10 |
+---------+


I was on selfoss 2.9 and just upgraded to 2.17 (thinking it might fix the issue).

**Comment by jtojnar** [comment]
When using `utf8` encoding MySQL simply drops everything following the Unicode character. When the database is converted to `utf8mb4` it will work for new items but not for the old ones since those are lost.

We started using `utf8mb4` in 2.16, I think. If you fetched the items before, there is not any way we can recover the data, or even know whether there was any data loss. You would have to remove the items from database and fetch them again.

**Comment by dlicois** [comment]
I'll watch if new items are ok, thank you.
