### ISSUE TITLE
Frequent session expiration

### ISSUE THREAD

**Issue by realgeek** [SSilence/selfoss#918]
When I click or use keyboard to open new article after laptop was sleeping or browser restart, article stays unread, and several seconds go by before getting red banner with error messages. Log messages look like 
  [2017-04-17 18:52:31] selfoss.ERROR: HTTP 403 (GET /items/sync)
  [2017-04-17 18:52:47] selfoss.ERROR: HTTP 403 (POST /mark/1345)
  [2017-04-17 18:52:53] selfoss.ERROR: HTTP 403 (POST /mark/1345)
  [2017-04-17 18:53:31] selfoss.ERROR: HTTP 403 (GET /items/sync)

At this point, I have to manually edit the URL to /selfoss/ and log back in. I am running 2.17 on Debian Jessie, Apache, php7.0-fpm, sqlite.

.htaccess can't pass php variables to FPM, so I created a .user.ini in the base directory and have in it:
  session.cookie_lifetime  = 604800
  session.cache_limiter    = public
  session.cache_expire     = 604800
but it seems to have no effect.

**Comment by jtojnar** [comment]
This seems to be a duplicate of #563. Could you also try increasing the `session.gc_maxlifetime` flag?

**Comment by realgeek** [comment]
I put the three lines above and session.gc_maxlifetime = 604800 into the global php config and it seems to be working! Thanks!!
