### ISSUE TITLE
Class 'Elphin\IcoFileLoader\IcoFileService' not found

### ISSUE THREAD

**Issue by kolydart** [SSilence/selfoss#937]
Master branch, when running `php cliupdate.php` I get the error:

> PHP Fatal error:  Class 'Elphin\IcoFileLoader\IcoFileService' not found in helpers/Image.php on line 125
> Fatal error: Class 'Elphin\IcoFileLoader\IcoFileService' not found

When I checkout to older commits (for ex. 815e8435) the error is not appearing, and the update is done.

**Comment by jtojnar** [comment]
We replaced the library for handling favicons for a more robust one. You will need to run `composer install` or get the updated vendor directory from the [built package](https://github.com/SSilence/selfoss#download).

**Comment by kolydart** [comment]
I run `composer install` and the issue is resolved. 
Thank you
