### ISSUE TITLE
 selfoss.ERROR: PDOStatement: Trigger does not exist

### ISSUE THREAD

**Issue by dwydler** [SSilence/selfoss#950]
Hi everybody,
i updated my installation to the latest master (git pull). After the update i login to my site and recieve follow error message: Load list error: error Internal Server Error

I look into the log file from selfoss ./data/logs/default.log and found follow entries:
[2017-06-17 15:24:33] selfoss.ERROR: PDOStatement: Trigger does not exist
[2017-06-17 15:25:55] selfoss.ERROR: PDOStatement: Trigger does not exist
[2017-06-17 15:25:56] selfoss.ERROR: PDOStatement: Trigger does not exist
[2017-06-17 15:25:59] selfoss.ERROR: PDOStatement: Trigger does not exist
[2017-06-17 15:32:42] selfoss.ERROR: PDOStatement: Trigger does not exist
[2017-06-17 15:33:39] selfoss.ERROR: PDOStatement: Trigger does not exist

I have proceeded the update as follow:
1) Backup directory and the mysql database
2) Rename the directory to selfoss.backup
3) Create a new git repo and execute git pull
4) change into the directory and run composer install
5) change in to public and run npm install
6) Customize the config.ini for my installation

Any ideas what i did wrong?

**Comment by jtojnar** [comment]
This definitely should not happen. Do you know what commit/version did you use before upgrading?

**Comment by dwydler** [comment]
Can you explain me, where i can found this information?!

**Comment by jtojnar** [comment]
You would see something like the following when issuing `git pull`:

```
From https://github.com/SSilence/selfoss
 * branch            master     -> FETCH_HEAD
Updating 176e8b2..08d5f15
```

The previous commit would be 176e8b2.

Alternately, if you still have the `selfoss.backup` directory, you can issue `git show`, which will show you the information about the latest commit there.

**Comment by dwydler** [comment]
Ah... i found it out. :-)

(17:09:14) [selfoss.backup2] git show
commit f78be3b5e0b16aeaa3809ac6e725a86d954b1fbc
Author: Amine Bou <aminecmi@gmail.com>
Date:   Thu Mar 23 14:37:46 2017 +0100
    Added the other android app link to the selfoss website.

**Comment by jtojnar** [comment]
I am unable to reproduce it. Could you also share the SQL dump of the original database? You can remove the private credentials and send it to jtojnar@gmail.com.

**Comment by dwydler** [comment]
Which private credentials do you mean? I used it only for rss feeds.

**Comment by jtojnar** [comment]
Then it should be alright, some people also have Twitter API keys, which they might not want to share.

**Comment by dwydler** [comment]
It's on the way to you.... few minutes.

**Comment by jtojnar** [comment]
Hmm, looks like you have been missing the triggers for a long time, for some reason. The `updatetime` is `NULL` for every item.

It should be safe to remove [these two lines](https://github.com/SSilence/selfoss/blob/08d5f15a6f9671f56f23fc69a0345e60a7343644/daos/mysql/Database.php#L211-L212) during the update.

**Comment by dwydler** [comment]
How can i correct the database? 
With our workaround i would have the same issue again, right?

**Comment by jtojnar** [comment]
Removing the `DROP` statements would fix the database.

The code is only run once when upgrading from database structure version 10 or lower. The database structure is expected to contain the triggers, which is why they need to be removed to add a new version of them. When the database does not contain them, they do not need to be removed.

**Comment by dwydler** [comment]
I comment out this lines.  Works as it should.
Thanks for your support.
