### ISSUE TITLE
Do you use PHP 5.4?

### ISSUE THREAD

**Issue by jtojnar** [SSilence/selfoss#962]
selfoss still targets PHP 5.4 because it is still supported by some LTS distributions:¹

|        Version         | PHP version |     EOL      | PHP EOL |   Status   |
|------------------------|-------------|--------------|---------|------------|
| ~~Debian 6 “Squeeze”~~ | 5.3         | 2016-02-29   | 2014    | EOL        |
| Debian 7 “Wheezy”      | 5.4         | 2018-05-31   | 2015    | LTS        |
| Debian 8 “Jessie”      | 5.6         | April 2020   | 2018    | Future LTS |
| RHEL 5                 | 5.1?        | 2020-11-30   | wut?    | LTS        |
| Debian 9 “Stretch”     | 7.0         | June 2022    | 2019    | Stable     |
| RHEL 6                 | 5.3         | Spring 2024? | 2014    | LTS        |
| RHEL 7                 | 5.4         | Autumn 2027? | 2015    | Stable     |

Switching to PHP 5.6 is not that interesting feature-wise² but the main reason for dropping old versions is libraries support. We already need to maintain [TwitterOAuth](https://github.com/fossar/twitteroauth-php54) ourselves and the list of incompatible libraries will only grow. [Another one](https://github.com/j0k3r/graby/pull/112#discussion_r123944220) of our dependencies is removing support for PHP 5.4 soon.

For comparison, Nextcloud [supports](https://docs.nextcloud.com/server/12/admin_manual/installation/system_requirements.html) 5.6+, Wallabag is switching to PHP 5.6 [in the next version](https://github.com/wallabag/wallabag/pull/3126) (2.3). Wordpress is very conservative, supporting [5.2.4+](https://wordpress.org/about/requirements/).

According to [Seldaek](https://seld.be/notes/php-versions-stats-2017-1-edition) PHP 5.4 has around 3 percent share but the data come from packagist which the users that want PHP 5.4 probably do not use.

**Is PHP 5.4 still relevant?**

-----

1. Source for [Debian EOL](https://wiki.debian.org/LTS) and [their PHP versions](https://wiki.debian.org/PHP#Available_versions). Dates for RHEL were estimated from [RHEL Life Cycle](https://access.redhat.com/support/policy/updates/errata/#Life_Cycle_Dates) and PHP versions taken from [here](https://wiki.centos.org/FAQ/CentOS5#head-8b85501ca7f023bc0eeb0fef98143e10fb6adefc), [here](https://developers.redhat.com/blog/2013/08/01/php-5-4-on-rhel-6-using-rhscl/) and [here](https://centos-packages.com/7/package/php/). Official PHP dates from [PHP website](https://secure.php.net/supported-versions.php).
2. PHP 5.5 introduces [`password_hash`](https://secure.php.net/manual/en/function.password-hash.php), which will be used in selfoss 3.0 but there is a [polyfill](https://github.com/ircmaxell/password_compat). If we dropped 5.4, we may as well kick 5.5, then we will also get [generators](https://secure.php.net/manual/en/migration55.new-features.php#migration55.new-features.generators), which I could use them for refactoring spouts.

**Comment by niol** [comment]
I do not use PHP 5.4.

**Comment by Koopzington** [comment]
Active Support for 5.6 has stopped in Jan 2017. Security Support ends Dec 2018.
Why should one even bother supporting PHP versions that aren't even officially supported by PHP itself anymore? PHP frameworks are already preparing to set the minimum version to 7.0 in their next versions.
Using 7.0 alone brings huge performance improvements. Even if it wouldn't use everything available in 7.0 and would theoretically still run on 5.6 i think pushing the minimum required version is imo a step in the right direction to peacefully force users to upgrade their ancient unsecure systems.

**Comment by jtojnar** [comment]
@Koopzington Not being supported by PHP team does not mean much in classic distributions like Debian or RHEL. Packages on those systems do not usually use official updates anyway, important stuff is backported.

Moreover, while I personally prefer upstream packages, some of our users, especially in poorer countries, may use cheapest servers available that often use oldest supported LTS version at best. Switching to better provider might not be a possibility for them.

**Comment by schmanat** [comment]
I'm using PHP 7.0, because its in the repo from Ubuntu 16.04 LTS

**Comment by jtojnar** [comment]
Does not seem to be an issue for users here so I will add the following message in 2.18 for PHP < 5.6.

> We are considering dropping support of older PHP versions. If you cannot upgrade, please let us know in the [issue tracker](https://github.com/SSilence/selfoss/issues/962).

If there is not a big fuss, 3.0 will raise the requirements.

**Comment by daftaupe** [comment]
Hello, I use PHP 5.4 as I'm using CentOS 7. That's what in the official repos, though one can use SCL to get up to PHP 7.1 if I'm correct.

**Comment by guzzisti** [comment]
No need for PHP 5.4 on my side :)
