### ISSUE TITLE
Investigate scroll linked effect

### ISSUE THREAD

**Issue by jtojnar** [SSilence/selfoss#972]
I see the following warning in Firefox browser console when visiting my selfoss instance:

> This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features!

It might explain the occasional compositing slowness when scrolling.

What exactly produces this warning? Is this effect really necessary? Can it be re-implemented in a more performance friendly way?

**Comment by squatica** [comment]
I could not replicate the warning in Firefox 71.0 on Ubuntu with neither the stable 2.18 nor the current master - seems like it was fixed by something else.
If anyone still gets the warning, speak now or forever hold your peace.

**Comment by jtojnar** [comment]
I cannot reproduce it either. I would not be surprised if we got rid of it on master but 2.18 is weird. I would assume Firefox stopped warning about it but just saw it on another web page. :woman_shrugging:
