### ISSUE TITLE
Double text on sources page in Firefox 55

### ISSUE THREAD

**Issue by klundry** [SSilence/selfoss#975]
I have just updated to Firefox 55.0.1 on Arch and now when I go to the sources page I get a weird double text over top of some of the sources.  But not all.  This may be similar to a closed issue from a couple years ago #536.

![screenshot_20170815_194007](https://user-images.githubusercontent.com/15848724/29342696-debbce76-81f1-11e7-8cad-703f88192ce2.png)

**Comment by jtojnar** [comment]
These are the alt texts for the missing favicons. We can safely make the alt text empty like we did in the [item view](https://github.com/SSilence/selfoss/commit/dd728f5e1ba32eab3f28fbbb4abdda7f3822065e#diff-54b142d967ca3f42bd5e69ff20b48f02L24).

In the future we might want to do something about the missing icons, like re-fetching them or saving them to the db.
