### ISSUE TITLE
error: jquery missing after heroku deploy following wiki instructions

### ISSUE THREAD

**Issue by ppoppitz** [SSilence/selfoss#982]
I tried deploying selfoss following the wiki page for PaaS. 
Steps to reproduce:
- create free heroku app with postgresql
- follow wiki instructions (env variables pushed with $ heroku config:push)
- app site shows generic error message and in logfiles I found:
> Missing file “public/node_modules/jquery/dist/jquery.js”. Did you install the dependencies using npm? [/app/helpers/View.php:150]

Sorry if this related to  a simple misunderstanding on my side and not a selfoss issue. I just thought it might be useful to know that the wiki instructions might be outdated or unclear for a rookie like me.

**Comment by jtojnar** [comment]
If I recall correctly, heroku detects buildpack by checking the presence of files like `package.json`. Unfortunately the client side `package.json` is in a subdirectory, thus not installed by Heroku.

Could you try the following branch: https://github.com/SSilence/selfoss/tree/heroku-fix

**Comment by ppoppitz** [comment]
thanks for the quick response. Unfortunately, I still get the same error. 
If I interpret the build log correctly, the dependencies are not installed:

> remote: Building source:
> remote: 
> remote: -----> PHP app detected
> remote: -----> Bootstrapping...
> remote: -----> Installing platform packages...
> remote:        - php (7.1.9)
> remote:        - ext-gd (bundled with php)
> remote:        - ext-mbstring (bundled with php)
> remote:        - apache (2.4.20)
> remote:        - nginx (1.8.1)
> remote: -----> Installing dependencies...
> remote:        Composer version 1.5.1 2017-08-09 16:07:22
> remote:        Loading composer repositories with package information
> remote:        Installing dependencies from lock file
> remote:        Package operations: 30 installs, 0 updates, 0 removals
> remote:          - Installing bcosca/fatfree-core (v3.6.0): Loading from cache
> remote:          - Installing react/promise (v2.5.0): Loading from cache
> remote:          - Installing guzzlehttp/streams (3.0.0): Loading from cache
> remote:          - Installing guzzlehttp/ringphp (1.1.0): Loading from cache
> remote:          - Installing guzzlehttp/guzzle (5.3.1): Loading from cache
> remote:          - Installing ddeboer/transcoder (1.0.0): Loading from cache
> remote:          - Installing fossar/guzzle-transcoder (0.0.3): Loading from cache
> remote:          - Installing fossar/twitteroauth-php54 (0.7.3-beta): Loading from cache
> remote:          - Installing psr/log (1.0.2): Loading from cache
> remote:          - Installing guzzlehttp/log-subscriber (1.0.1): Loading from cache
> remote:          - Installing fossar/tcpdf-parser (6.2.16): Loading from cache
> remote:          - Installing symfony/polyfill-mbstring (v1.3.0): Loading from cache
> remote:          - Installing true/punycode (v2.1.1): Loading from cache
> remote:          - Installing symfony/options-resolver (v2.8.18): Loading from cache
> remote:          - Installing smalot/pdfparser (v0.9.26): Loading from cache
> remote:          - Installing simplepie/simplepie (1.4.3): Loading from cache
> remote:          - Installing monolog/monolog (1.22.1): Loading from cache
> remote:          - Installing j0k3r/safecurl (2.0.2): Loading from cache
> remote:          - Installing j0k3r/php-readability (1.1.7): Loading from cache
> remote:          - Installing symfony/finder (v2.8.18): Loading from cache
> remote:          - Installing j0k3r/graby-site-config (1.0.32): Loading from cache
> remote:          - Installing htmlawed/htmlawed (1.1.22): Loading from cache
> remote:          - Installing j0k3r/graby (1.6.2): Loading from cache
> remote:          - Installing linkorb/jsmin-php (1.0.0): Loading from cache
> remote:          - Installing lordelph/icofileloader (1.1.0): Loading from cache
> remote:          - Installing mibe/feedwriter (v1.1.1): Loading from cache
> remote:          - Installing natxet/cssmin (v3.0.4): Loading from cache
> remote:          - Installing smottt/wideimage (1.1.3): Loading from cache
> remote:          - Installing tracy/tracy (v2.4.6): Loading from cache
> remote:          - Installing willwashburn/phpamo (1.0.1): Loading from cache
> remote:        Generating optimized autoload files
> remote: -----> Preparing runtime environment...
> remote: -----> Checking for additional extensions to install...
> remote: -----> Discovering process types
> remote:        Procfile declares types -> web
> remote: 
> remote: -----> Compressing...
> remote:        Done: 22.4M
> remote: -----> Launching...
> remote:        Released v13

**Comment by jtojnar** [comment]
Okay, does not seem like nodejs is detected. Can you try `heroku buildpacks:add --index 1 heroku/nodejs`, see https://devcenter.heroku.com/articles/using-multiple-buildpacks-for-an-app

**Comment by ppoppitz** [comment]
Thank you! Everything is working fine now.

**Comment by jtojnar** [comment]
Thanks for testing. I updated the wiki page.
