### ISSUE TITLE
[API] Marking an item as read fails some times

### ISSUE THREAD

**Issue by aminecmi** [SSilence/selfoss#990]
Hi,

Some api calls to the ["mark item as read"](https://github.com/SSilence/selfoss/wiki/Restful-API-for-Apps-or-any-other-external-access#items_mark_as_read) route fail. 

`{isSuccess: false}` is returned, and this is the error:
`
Fatal error: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead.
`

As it isn't happening all the time, I'm not sure what could be done.

**Comment by jtojnar** [comment]
See also #565

**Comment by aminecmi** [comment]
So it's an issue on old versions of the web app.

Thanks. I will close this now.

**Comment by jtojnar** [comment]
It cannot really be prevented server-side without modifying php.ini or patching fatfree framework. You need to make sure your client sends `Content-Type` header.

**Comment by aminecmi** [comment]
Ok, thanks. I'll try this.
